dchbx/enroll

app/models/effective/datatables/premium_billing_report_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16703](https://devops.dchbx.org/redmine/issues/16703) |

16703: Employer receives 500 error when attempting to run Enrollment Report 

---

script/set_consumer_role_incorrect_bookmark_url.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16977](https://devops.dchbx.org/redmine/issues/16977) |

16977: error message: the page you are looking for does not exist 

---

app/models/plan_year.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16397](https://devops.dchbx.org/redmine/issues/16397) |

16397: June 2017 Termination due to Non-payment

---

app/views/financial_assistance/applicants/steps.yml
app/views/financial_assistance/benefits/steps.yml
app/views/financial_assistance/deductions/steps.yml
app/views/financial_assistance/incomes/steps.yml
app/views/insured/family_members/_financial_assistance_row.html.erb
app/views/insured/family_members/index.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17348](https://devops.dchbx.org/redmine/issues/17348) |
| Ticket Author | @maheshkurma |

17348: FAA- Changes in UI

---

app/data_migrations/remove_ssn.rb
lib/tasks/remove_ssn.rake
spec/data_migrations/remove_ssn_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13912](https://devops.dchbx.org/redmine/issues/13912) |

13912: Remove fake SSN for HBX ID 

---

app/controllers/financial_assistance/applications_controller.rb
app/models/financial_assistance/application.rb
app/views/events/financial_assistance/_benefit.xml.haml
app/views/financial_assistance/applicants/other_questions.html.erb
lib/schemas/common.xsd
lib/schemas/financial_assistance.xsd
lib/schemas/individual.xsd
lib/schemas/links.xsd
lib/schemas/organization.xsd
lib/schemas/plan.xsd
lib/schemas/verification_services.xsd

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17365](https://devops.dchbx.org/redmine/issues/17365) |
| Ticket Author | @chriswiseman-dcgov |

17365: FAA CV Generation:  Validate Payload Before Submitting

---

app/controllers/financial_assistance/applications_controller.rb
app/models/financial_assistance/application.rb
app/views/events/financial_assistance/_benefit.xml.haml
app/views/financial_assistance/applicants/other_questions.html.erb
app/views/insured/families/personal.js.erb
app/views/insured/family_members/index.html.erb
lib/schemas/common.xsd
lib/schemas/financial_assistance.xsd
lib/schemas/individual.xsd
lib/schemas/links.xsd
lib/schemas/organization.xsd
lib/schemas/plan.xsd
lib/schemas/verification_services.xsd

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17370](https://devops.dchbx.org/redmine/issues/17370) |

17370: Primary Edit Cancel Button

---

app/assets/javascripts/consumer_verification.js
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/vlp_document.rb
app/views/insured/families/verification/_verification.html.erb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17081](https://devops.dchbx.org/redmine/issues/17081) |

17081: Verification Action "Return for Deficiency" to be changed and labelled as "Reject"

---

app/assets/javascripts/consumer_verification.js
app/controllers/insured/verification_documents_controller.rb
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/vlp_document.rb
app/views/insured/families/verification/_verification.html.erb
spec/helpers/verification_helper_spec.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14254](https://devops.dchbx.org/redmine/issues/14254) |

14254: Verification Type: Outstanding state

---

app/models/insured_eligible_for_benefit_rule.rb
app/views/insured/families/verification/_verification.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16802](https://devops.dchbx.org/redmine/issues/16802) |

16802: Non-applicant asked to verify immigration status

---

app/data_migrations/delink_broker.rb
lib/tasks/migrations/delink_broker.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17225](https://devops.dchbx.org/redmine/issues/17225) |

17225: Broker accounts are linked when they should not be

---

app/assets/stylesheets/financial_assistance.scss.erb
app/views/financial_assistance/applicants/other_questions.html.erb
app/views/financial_assistance/benefits/index.html.erb
app/views/financial_assistance/benefits/steps.yml
app/views/financial_assistance/deductions/index.html.erb
app/views/financial_assistance/deductions/steps.yml
app/views/financial_assistance/incomes/index.html.erb
app/views/financial_assistance/incomes/steps.yml
components/ui_helpers/app/views/workflow/_dropdown.html.erb
components/ui_helpers/app/views/workflow/_input.html.erb
components/ui_helpers/app/views/workflow/_input_date.html.erb
components/ui_helpers/lib/ui_helpers/workflow/cell.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17466](https://devops.dchbx.org/redmine/issues/17466) |
| Ticket Author | @shaibazalisyed |

17466: Ui issues for Financial Assistance application.

---

app/data_migrations/update_book_mark_url_for_employee_role.rb
lib/tasks/migrations/update_book_mark_url_for_employee_role.rake
spec/data_migrations/update_book_mark_url_for_employee_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16993](https://devops.dchbx.org/redmine/issues/16993) |

16993: Error upon login

---

app/data_migrations/remove_incorrect_person_relationship.rb
lib/tasks/migrations/remove_incorrect_person_relationship.rake
spec/data_migrations/remove_invalid_person_relationship_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17138](https://devops.dchbx.org/redmine/issues/17138) |
| Ticket Author | Grace A Cudjoe |

17138: Unable to plan shop with SEP: HBX - 19898136

---

app/data_migrations/add_new_eligibility_determination.rb
lib/tasks/add_new_eligibility_determination.rake
spec/data_migrations/add_new_eligibility_determination_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17078](https://devops.dchbx.org/redmine/issues/17078) |
| Ticket Author | Liz Burman |

17078: Terminate APTC/CSR in EA effective 8/1

---

app/assets/javascripts/financial_assistance/step_conditionals.js
app/controllers/financial_assistance/applicants_controller.rb
app/models/financial_assistance/applicant.rb
app/views/financial_assistance/applicants/other_questions.html.erb
config/routes.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17326](https://devops.dchbx.org/redmine/issues/17326) |

17326: Conditional Display 

---

app/data_migrations/change_aasm_state_dot_census_employee.rb
app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_aasm_state_dot_census_employee.rake
spec/data_migrations/change_aasm_state_dot_census_employee_spec.rb
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17380](https://devops.dchbx.org/redmine/issues/17380) |

17380: Revert Employee termination performed in error- Analyticx LLC

---

app/controllers/documents_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17532](https://devops.dchbx.org/redmine/issues/17532) |

17532: admin's Verification screen "Complete Verification for Enrollment" button throwing error when clicked

---

app/models/plan_year.rb
app/notices/pdf_templates/conditional_eligibility_notice.rb
app/notices/pdf_templates/eligibility_notice.rb
app/notices/pdf_templates/employee_notice.rb
app/notices/pdf_templates/employer_notice.rb
app/notices/pdf_templates/enrollment.rb
app/notices/pdf_templates/individual.rb
app/notices/shop_employee_notice.rb
app/notices/shop_employee_notices/notify_employee_of_initial_employer_ineligibility.rb
app/views/notices/shared/_address.html.erb
app/views/notices/shop_employee_notices/notification_to_employee_due_to_initial_employer_ineligibility.html.erb
db/seedfiles/notice_triggers_seed.rb
spec/notices/shop_employee_notices/notify_employee_of_initial_employer_ineligibility_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15813](https://devops.dchbx.org/redmine/issues/15813) |

15813: (NOTICE ID 10047) Notify Initial Employees that Employer's SHOP will not go into effect due to ineligibility- HIGH PRIORITY

---

app/data_migrations/update_person_name.rb
lib/tasks/migrations/update_person_name.rake
spec/data_migrations/update_person_name_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17212](https://devops.dchbx.org/redmine/issues/17212) |

17212: POC name correction

---

app/assets/javascripts/financial_assistance/step_conditionals.js
app/helpers/financial_assistance_helper.rb
app/views/financial_assistance/applications/steps.yml
components/ui_helpers/app/views/workflow/_section.html.erb
components/ui_helpers/app/views/workflow/_signature_inputs.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Submit application page- elec signature

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/helpers/application_helper.rb
app/models/employer_profile.rb
project_gems/effective_datatables-2.6.14/app/assets/javascripts/effective_datatables/bulk_actions.js.coffee
project_gems/effective_datatables-2.6.14/app/views/effective/datatables/_bulk_actions_column.html.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17589](https://devops.dchbx.org/redmine/issues/17589) |

17589: HBX Admin button to initiate "Binder Paid" state transition is not behaving as designed

---

app/controllers/insured/group_selection_controller.rb
app/models/hbx_enrollment.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16462](https://devops.dchbx.org/redmine/issues/16462) |

16462: SEP Dashboard - Coverage Effective Date Option Not Working for SHOP

---

app/data_migrations/reinstate_plan_year.rb
app/models/plan_year.rb
lib/tasks/migrations/reinstate_plan_year.rake
spec/data_migrations/reinstate_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17604](https://devops.dchbx.org/redmine/issues/17604) |

17604: Reinstatement after termination for Non-payment- Centurion Group DC

---

app/models/rule_set/hbx_enrollment/individual_market_verification.rb
spec/models/rule_set/hbx_enrollment/individual_market_verificiation_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17499](https://devops.dchbx.org/redmine/issues/17499) |
| Ticket Author | @lisyk |

17499: wrong enrollment transition for enrolled contingent

---

app/data_migrations/add_coverage_household_member.rb
app/data_migrations/terminate_census_employee_with_no_hbx_enrollment.rb
lib/tasks/migrations/terminate_census_employee_with_no_hbx_enrollment.rake
spec/data_migrations/terminate_census_employee_spec.rb
spec/data_migrations/terminate_census_employee_with_no_hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17069](https://devops.dchbx.org/redmine/issues/17069) |
| Ticket Author | Grace A Cudjoe |

17069: Unable to plan shop with SEP: HBX - 19797186

---

app/assets/stylesheets/custom.scss.erb
app/assets/stylesheets/financial_assistance.scss.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17667](https://devops.dchbx.org/redmine/issues/17667) |

17667: Active Links

---

app/assets/javascripts/financial_assistance/step_conditionals.js
app/controllers/financial_assistance/incomes_controller.rb
app/models/financial_assistance/income.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17717](https://devops.dchbx.org/redmine/issues/17717) |

17717: Phone Number Input

---

app/views/employers/employer_profiles/my_account/_benefits.html.erb
spec/views/employers/employer_profiles/my_account/benefits.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16289](https://devops.dchbx.org/redmine/issues/16289) |

16289: BQT fast follow- Turn off Claim quote when PY in in Enrolling State

---

app/data_migrations/change_last_portal_visited.rb
lib/tasks/change_last_portal_visited.rake
spec/data_migrations/change_last_portal_visited_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17551](https://devops.dchbx.org/redmine/issues/17551) |

17551: No Employer Found Received for existing terminated EE that is seeking IVL coverage

---

app/helpers/verification_helper.rb
app/views/insured/families/verification/_verification.html.erb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16007](https://devops.dchbx.org/redmine/issues/16007) |

16007: Verifications- Display Curam verified indicator to HBX-Admin

---

app/data_migrations/update_user_or_person_records.rb
lib/tasks/update_user_or_person_records.rake
spec/data_migrations/update_user_or_person_records_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17282](https://devops.dchbx.org/redmine/issues/17282) |

17282: DOB update

---

app/views/insured/group_selection/new.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17633](https://devops.dchbx.org/redmine/issues/17633) |

17633: SEP event date showing instead of effective date

---

app/controllers/financial_assistance/applications_controller.rb
app/models/financial_assistance/application.rb
spec/controllers/financial_asistance/applications_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17730](https://devops.dchbx.org/redmine/issues/17730) |

17730: COPY Application Functionality

---

app/views/exchanges/hbx_profiles/_index_verification.html.erb
app/views/exchanges/hbx_profiles/_outstanding_verification_family.json.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17712](https://devops.dchbx.org/redmine/issues/17712) |

17712: Remove the Federal Hub details column from the Documents screen

---

app/views/insured/consumer_roles/ridp_agreement.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #17737 Changes default on Experian authorization page to I agree

---

app/assets/stylesheets/eligibility_results.scss.erb
app/assets/stylesheets/financial_assistance.scss.erb
app/assets/stylesheets/main.scss.erb
app/views/financial_assistance/applications/eligibility_results.html.erb
app/views/financial_assistance/applications/index.html.erb
app/views/financial_assistance/shared/_status.html.erb
components/ui_helpers/app/views/workflow/_section.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17873](https://devops.dchbx.org/redmine/issues/17873) |
| Ticket Author | @shaibazalisyed |

17873: Eligibility Page styling 

---

app/controllers/broker_agencies/profiles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17293](https://devops.dchbx.org/redmine/issues/17293) |

17293: Update broker information

---

app/helpers/verification_helper.rb
app/views/exchanges/hbx_profiles/_outstanding_verification_family.json.erb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17710](https://devops.dchbx.org/redmine/issues/17710) |

17710: Update the Documents column logic to show number of uploaded documents for household

---

app/helpers/financial_assistance_helper.rb
components/ui_helpers/app/views/workflow/_claimed_as_dependent_by_dropdown.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17733](https://devops.dchbx.org/redmine/issues/17733) |

17733: Tax Dependent Cannot Claim A Tax Dependent

---

app/data_migrations/change_hbx_id.rb
lib/tasks/migrations/change_hbx_id.rake
spec/data_migrations/change_hbx_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17485](https://devops.dchbx.org/redmine/issues/17485) |

17485: Update HBX ID for spouse (R. Khurana 19831652 // 19822661)

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16972](https://devops.dchbx.org/redmine/issues/16972) |

16972: EnrollApp - IVL account update

---

app/controllers/insured/group_selection_controller.rb
app/helpers/insured/group_selection_helper.rb
spec/helpers/insured/group_selection_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17512](https://devops.dchbx.org/redmine/issues/17512) |

17512: EE on two rosters Cannot Select Dental Plan through QLE

---

app/data_migrations/build_shop_enrollment.rb
app/helpers/insured/group_selection_helper.rb
app/views/insured/group_selection/_select_employer.html.erb
app/views/insured/group_selection/new.html.erb
spec/data_migrations/build_shop_enrollment_spec.rb
spec/helpers/insured/group_selection_helper_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17636](https://devops.dchbx.org/redmine/issues/17636) |

17636: Employee of Renewing Employer unable to shop Dental

---

app/controllers/documents_controller.rb
app/views/insured/families/verification/_verification.html.erb
config/routes.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17126](https://devops.dchbx.org/redmine/issues/17126) |

17126: Document verification 'Send documents for review' button update

---

app/data_migrations/reinstate_plan_year.rb
app/models/plan_year.rb
spec/data_migrations/reinstate_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17774](https://devops.dchbx.org/redmine/issues/17774) |

17774: Transition plan year to active- Atlas Manufacturing, Inc

---

app/helpers/verification_helper.rb
app/views/exchanges/hbx_profiles/_outstanding_verification_family.json.erb
lib/tasks/hbx_reports/outstanding_documents_report.rake
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16760](https://devops.dchbx.org/redmine/issues/16760) |

16760: Documents screen admin ability to view all records ad hoc report until a view all ability functions 

---

app/models/plan_year.rb
app/notices/shop_employer_notices/renewal_employer_open_enrollment_completed.rb
app/views/notices/shop_employer_notices/renewal_employer_open_enrollment_completed.html.erb
config/settings.yml
db/seedfiles/notice_triggers_seed.rb
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb
spec/notices/shop_employer_notices/renewal_employer_open_enrollment_completed_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15202](https://devops.dchbx.org/redmine/issues/15202) |

15202: Shop 18-Renewal Employee Open Enrollment Completed (with minimum participation) & non-owner enrollee- Medium Priorty

---

app/data_migrations/remove_congress_census_employee.rb
lib/tasks/remove_congress_census_employee.rake
spec/data_migrations/remove_congress_census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17719](https://devops.dchbx.org/redmine/issues/17719) |

17719: Congressional Employee receiving 500 error when attempting to match User to Person

---

app/assets/javascripts/financial_assistance/step_conditionals.js
features/financial_assistance/faa_application_checklist.feature
features/financial_assistance/faa_household_info.feature
features/financial_assistance/faa_left_nav.feature
features/financial_assistance/financial_assistance_flow.feature
features/step_definitions/faa_aaplication_checklist.steps.rb
features/step_definitions/faa_household_info_steps.rb
features/step_definitions/faa_left_nav_steps.rb
features/step_definitions/financial_assistance_flow_steps.rb
features/support/worlds/financial_assistance_world.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Faa cucumbers

---

app/models/financial_assistance/application.rb
app/views/events/financial_assistance/_assistance_tax_household.xml.haml
app/views/events/financial_assistance/_assistance_tax_household_member.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17632](https://devops.dchbx.org/redmine/issues/17632) |
| Ticket Author | @chriswiseman-dcgov |

17632: FAA CV Generation:  FAA CV XML Tax Household Member in Multiple Tax Households

---

lib/tasks/hbx_reports/lawful_alien_docs.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17113](https://devops.dchbx.org/redmine/issues/17113) |

17113: Create query to pull 'document_type' data for all consumer role lawfully present individuals active on plans

---

spec/models/subscribers/family_application_completed_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18002](https://devops.dchbx.org/redmine/issues/18002) |

18002: CURAM Importer Specs

---

app/data_migrations/make_benefit_group_assignment_active.rb
lib/tasks/make_benefit_group_assignment_active.rake
spec/data_migrations/make_benefit_group_assignment_active_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17890](https://devops.dchbx.org/redmine/issues/17890) |

17890: Customer receives 500 error when attempting to Enroll through a QLE

---

app/controllers/application_controller.rb
app/controllers/financial_assistance/applicants_controller.rb
app/controllers/financial_assistance/applications_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/helpers/application_helper.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18060](https://devops.dchbx.org/redmine/issues/18060) |

18060: Bookmark URL for FAA Intake Pages

---

app/data_migrations/change_broker_details.rb
lib/tasks/migrations/change_broke_details.rake
spec/data_migrations/change_broker_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16461](https://devops.dchbx.org/redmine/issues/16461) |

16461: Change broker applicant Ozea Brooks' market kinds from Both to Individual and update email address

---

app/models/consumer_role.rb
app/models/lawful_presence_determination.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17039](https://devops.dchbx.org/redmine/issues/17039) |
| Ticket Author | @nisanthyaganti9 |

17039: populate user id while recording state machine events on consumer role model

---

features/financial_assistance/fa_not_applying.feature
features/step_definitions/fa_not_applying.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17543](https://devops.dchbx.org/redmine/issues/17543) |

17543: Applicant Creation Using Previous Link

---

lib/tasks/migrations/IVL_policy_end_date_update.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16303](https://devops.dchbx.org/redmine/issues/16303) |

16303: EnrollApp - IVL Policy End Date Updates

---

app/assets/stylesheets/family_relationships.scss.erb
app/assets/stylesheets/main.scss.erb
app/views/insured/family_relationships/_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18008](https://devops.dchbx.org/redmine/issues/18008) |

18008: Incorporate CSS design for Household Relationship page

---

app/controllers/insured/family_members_controller.rb
app/controllers/insured/group_selection_controller.rb
app/views/insured/family_members/index.html.erb
app/views/insured/group_selection/new.html.erb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16235](https://devops.dchbx.org/redmine/issues/16235) |

16235: Improve visibility of Effective Date on Plan Shopping and Household Coverage Pages

---

app/models/qualifying_life_event_kind.rb
app/models/special_enrollment_period.rb
spec/models/special_enrollment_period_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17989](https://devops.dchbx.org/redmine/issues/17989) |

17989: Effective dates for loss of other coverage SEP not working

---

spec/factories/eligibility_determinations.rb
spec/factories/financial_assistance_benefits.rb
spec/factories/tax_households.rb
spec/models/financial_assistance/applicant_spec.rb
spec/models/financial_assistance/application_spec.rb
spec/models/financial_assistance/benefit_spec.rb
spec/models/household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18005](https://devops.dchbx.org/redmine/issues/18005) |

18005: Model Specs

---

lib/tasks/hbx_reports/special_enrollment_employee_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17526](https://devops.dchbx.org/redmine/issues/17526) |

17526: Missing 7/1 Renewal Enrollments

---

app/controllers/employers/plan_years_controller.rb
spec/controllers/employers/plan_years_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16815](https://devops.dchbx.org/redmine/issues/16815) |

16815: Notice triggers multiple times

---

app/data_migrations/change_census_employee_details.rb
lib/tasks/change_census_employee_details.rake
spec/data_migrations/change_census_employee_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17028](https://devops.dchbx.org/redmine/issues/17028) |

17028: Termination Date Correction- Tokyo Electric Power Company

---

app/models/consumer_role.rb
app/models/insured_eligible_for_benefit_rule.rb
app/models/resident_role.rb
spec/models/consumer_role_spec.rb
spec/models/insured_eligible_for_benefit_rule_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17549](https://devops.dchbx.org/redmine/issues/17549) |

17549: No silver plans displaying for user in plan shopping

---

app/views/exchanges/hbx_profiles/_get_employer_info.html.erb
app/views/exchanges/hbx_profiles/_get_user_info.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16569](https://devops.dchbx.org/redmine/issues/16569) |

16569: Remove 'User Role' field from the admin 'View Username and Email" action display on the 'Families' and 'Employers' data table

---

app/controllers/insured/consumer_roles_controller.rb
app/views/financial_assistance/applicants/other_questions.html.erb
app/views/financial_assistance/applications/application_checklist.html.erb
app/views/financial_assistance/applications/edit.html.erb
app/views/financial_assistance/applications/eligibility_response_error.html.erb
app/views/financial_assistance/applications/help_paying_coverage.html.erb
app/views/financial_assistance/applications/review_and_submit.html.erb
app/views/insured/consumer_roles/_form.html.erb
app/views/insured/consumer_roles/match.html.haml
app/views/insured/consumer_roles/no_match.html.haml
app/views/insured/consumer_roles/ridp_agreement.html.erb
app/views/insured/consumer_roles/search.html.haml
app/views/insured/family_members/show.js.erb
app/views/insured/family_relationships/index.html.erb
app/views/insured/interactive_identity_verifications/new.html.haml
app/views/layouts/financial_assistance.html.erb
components/ui_helpers/app/views/workflow/step.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18157](https://devops.dchbx.org/redmine/issues/18157) |

18157: Consumer Intake Column Alignment

---

app/models/benefit_coverage_period.rb
app/models/hbx_profile.rb
app/views/insured/group_selection/terminate_confirm.html.erb
spec/models/benefit_coverage_period_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17889](https://devops.dchbx.org/redmine/issues/17889) |

17889: Allow self-serve terminations for IVL plans for current or any future date instead of 14-day rule

---

app/models/queries/named_policy_queries.rb
app/models/queries/shop_monthly_enrollments.rb
config/settings.yml
spec/models/queries/named_policy_queries_spec.rb
spec/models/queries/shop_monthly/monthly_enrollment_query_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16445](https://devops.dchbx.org/redmine/issues/16445) |

16445: For SHOP initial employers, there needs to be a 'quiet' period

---

app/models/benefit_group.rb
app/models/employer_profile.rb
app/models/plan_year.rb
config/settings.yml
spec/factories/benefit_groups.rb
spec/models/benefit_group_spec.rb
spec/models/employer_profile_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17856](https://devops.dchbx.org/redmine/issues/17856) |

17856: Create event for employer broadcast on the 15th of each month

---

app/data_migrations/correct_employees_with_incorrect_waivers.rb
app/data_migrations/update_plan_years_with_dental_offerings.rb
app/models/factories/family_enrollment_renewal_factory.rb
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb
spec/data_migrations/triggering_auto_renewals_for_specific_employer_spec.rb
spec/models/factories/family_enrollment_renewal_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17089](https://devops.dchbx.org/redmine/issues/17089) |

17089: Discontinue generation of automatic passive waivers under specified scenarios

---

app/views/events/v2/employers/_owner_contact.xml.haml
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16616](https://devops.dchbx.org/redmine/issues/16616) |

16616: XML incorrectly includes POC's address

---

app/data_migrations/remove_family_member_from_coverage_household.rb
lib/tasks/migrations/remove_family_member_from_coverage_household.rake
spec/data_migrations/remove_family_member_from_coverage_household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18086](https://devops.dchbx.org/redmine/issues/18086) |
| Ticket Author | Diane Santiago |

18086: Remove duplicate Dependents: HBX 19937379

---

features/financial_assistance/view_eligibility.feature
features/step_definitions/view_eligibility_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18187](https://devops.dchbx.org/redmine/issues/18187) |

18187: View Eligibility

---

app/data_migrations/remove_duplicate_broker_agency_accounts.rb
lib/tasks/remove_duplicate_broker_agency_accounts.rake
spec/data_migrations/remove_duplicate_broker_agency_accounts_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14747](https://devops.dchbx.org/redmine/issues/14747) |

14747: Brokers should be disassociated from IVL and Employer when they are decertified

---

lib/tasks/hbx_reports/test_employer_group_enrollment_data.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16400](https://devops.dchbx.org/redmine/issues/16400) |

16400: Check for Active Enrollments associated with Test Employer Groups in Production

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18172](https://devops.dchbx.org/redmine/issues/18172) |

18172: Transition Employee Enrollments to active in EA

---

app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml
app/views/events/v2/shared/_enrollee.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18357](https://devops.dchbx.org/redmine/issues/18357) |
| Ticket Author | Alix Pereira |

18357: SHOP Roster Terms Not Flowing

---

lib/tasks/ivl_enrollment_clean_up.rake
lib/tasks/shop_enrollment_clean_up.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17778](https://devops.dchbx.org/redmine/issues/17778) |

17778: Enrollment Data Clean Up followup

---

Gemfile.lock
app/notices/ivl_notices/second_ivl_renewal_notice.rb
app/views/notices/ivl/projected_eligibility_notice.html.erb
app/views/notices/shared/_unordered_family_listing.html.erb
db/seedfiles/notice_triggers_seed.rb
script/projected_eligibility_notice_aqhp.rb
spec/notices/ivl_notices/second_ivl_renewal_notice_spec.rb
spec/test_data/notices/second_ivl_renewal_notice_test_data.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18440](https://devops.dchbx.org/redmine/issues/18440) |

18440: IVL AQHP Projected Eligibility Notices

---

app/data_migrations/fix_citizen_for_hub_responses.rb
spec/data_migrations/fix_citizen_for_hub_responses_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15018](https://devops.dchbx.org/redmine/issues/15018) |

15018: Correct remaining non_native_not_lawfully_present_in_us values

---

app/data_migrations/define_permissions.rb
app/models/effective/datatables/employer_datatable.rb
app/models/effective/datatables/family_data_table.rb
app/models/permission.rb
app/policies/family_policy.rb
lib/tasks/define_permissions.rake
spec/data_migrations/permissions_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18395](https://devops.dchbx.org/redmine/issues/18395) |

18395: Admin ability to View Usernames

---

app/assets/javascripts/group_selection.js
features/group_selection/ivl_plan_shopping.feature
features/step_definitions/individual_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18540](https://devops.dchbx.org/redmine/issues/18540) |

18540: Child-only enrollment blocked for dual-role user

---

app/models/forms/time_keeper.rb
spec/controllers/exchanges/hbx_profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17973](https://devops.dchbx.org/redmine/issues/17973) |

17973: Timetravel triggered via the UI is synchronous

---

Gemfile.lock
app/models/employer_profile.rb
app/models/queries/named_policy_queries.rb
app/models/queries/shop_monthly_enrollments.rb
app/models/subscribers/shop_initial_employer_quiet_period_ended.rb
app/models/time_keeper.rb
config/application.rb
spec/models/queries/shop_monthly/monthly_quiet_period_enrollments_query_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18302](https://devops.dchbx.org/redmine/issues/18302) |

18302: Process quiet period enrollments for Initial Employers

---

app/models/plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18595](https://devops.dchbx.org/redmine/issues/18595) |

18595: When applicant plan years are denied eligibility they erronously try to change the state of employer profiles

---

lib/tasks/hbx_reports/shop_monthly_enrollments.rake
spec/lib/tasks/hbx_reports/shop_monthly_enrollments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18364](https://devops.dchbx.org/redmine/issues/18364) |

18364: Generate employer report for Shop automation

---

features/step_definitions/broker_employee_quote_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18759](https://devops.dchbx.org/redmine/issues/18759) |
| Ticket Author | @harshared |

18759: Cucumber Failure: features/brokers/create_quote.feature

---

app/assets/javascripts/financial_assistance/step_conditionals.js
features/financial_assistance/left_nav_checkmark_faa.feature
features/step_definitions/left_nav_checkmark_faa_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17669](https://devops.dchbx.org/redmine/issues/17669) |

17669: No Checkmark for Not Necessary

---

Gemfile.lock
app/models/time_keeper.rb
lib/tasks/hbx_reports/gapped_new_hire_enrollments.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18602](https://devops.dchbx.org/redmine/issues/18602) |

18602: Generate a report with gated new hire enrollments

---

app/models/family.rb
app/models/plan_cost_decorator_congress.rb
features/employee/employee_plan_shopping.feature
features/step_definitions/integration_steps.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18211](https://devops.dchbx.org/redmine/issues/18211) |

18211: 500 error received during plan shopping 

---

app/views/shared/_reference_plans_list.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [7492](https://devops.dchbx.org/redmine/issues/7492) |
| Start Date | 05/18/2016 |

7492: Unable to View Reference Plans With Same Plan Offerings Unless You Switch Plan Offerings First

---

app/assets/stylesheets/financial_assistance.scss.erb
app/helpers/financial_assistance_helper.rb
app/views/financial_assistance/applications/review_and_submit.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18256](https://devops.dchbx.org/redmine/issues/18256) |

18256: Income & Deductions Display

---

app/controllers/employers/employer_profiles_controller.rb
app/models/employer_profile.rb
app/models/forms/employer_profile.rb
app/models/forms/organization_signup.rb
app/views/employers/employer_profiles/_employer_contact_preferences.html.erb
app/views/employers/employer_profiles/_employer_form.html.erb
app/views/employers/employer_profiles/_form.html.erb
features/step_definitions/integration_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13513](https://devops.dchbx.org/redmine/issues/13513) |

13513: Give Employer option for paper& Electronic notices 

---

app/data_migrations/fix_hub_verified_consumer.rb
app/data_migrations/terminate_employee_from_employer.rb
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/person.rb
features/step_definitions/verification_process_steps.rb
spec/data_migrations/fix_hub_verified_consumer_spec.rb
spec/models/person_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Refs 15577 STAGE FIX

---

app/controllers/broker_agencies/profiles_controller.rb
app/models/broker_role.rb
app/models/person.rb
app/views/employers/broker_agency/_active_broker.html.erb
app/views/employers/employer_profiles/_employer_broker_widget.html.erb
spec/controllers/broker_agencies/profiles_controller_spec.rb
spec/models/broker_role_spec.rb
spec/views/employers/employer_profiles/_employer_broker_widget.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18764](https://devops.dchbx.org/redmine/issues/18764) |

18764: Broker Agency not updating and Broker Agency changes not flowing to Choose Broker functionality

---

app/data_migrations/disable_person_account.rb
spec/data_migrations/disable_person_account_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13968](https://devops.dchbx.org/redmine/issues/13968) |
| Ticket Author | Camille Gray |

13968: Disable duplicate EA accounts

---

app/views/broker_agencies/profiles/_menu.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18558](https://devops.dchbx.org/redmine/issues/18558) |

18558: Hide "Agency Mail" tab in Broker Agency Accounts

---

app/models/queries/named_policy_queries.rb
spec/models/queries/named_policy_queries_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18536](https://devops.dchbx.org/redmine/issues/18536) |

18536: Correct Renewal Query to Provide Final Disposition of Enrollments as of midnight of the 15th

---

app/assets/javascripts/application.js.erb
app/assets/stylesheets/custom.scss.erb
app/views/insured/family_members/_dependent_form.html.erb
app/views/people/landing_pages/_personal.html.erb
app/views/shared/_is_applying_for_coverage.html.erb
app/views/shared/person/_consumer_information.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18521](https://devops.dchbx.org/redmine/issues/18521) |

18521: Relationship CSS for the Household Info Form

---

app/views/employers/census_employees/_member_fields.html.erb
app/views/employers/people/_search_fields.html.erb
app/views/general_agencies/profiles/new_agency.html.erb
app/views/general_agencies/profiles/new_agency_staff.html.erb
app/views/insured/consumer_roles/search.html.haml
app/views/insured/family_members/_dependent_form.html.erb
app/views/people/_dependent.html.erb
app/views/people/landing_pages/_add_family_member_form.html.erb
app/views/people/landing_pages/_personal.html.erb
app/views/shared/_census_dependent_fields.html.erb
app/views/shared/_person_name_fields.html.erb
app/views/shared/person/_consumer_information.html.erb
app/views/shared/person/_personal_information.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14118](https://devops.dchbx.org/redmine/issues/14118) |

14118: Disable Auto Fill for specific fields

---

lib/tasks/hbx_reports/census_ee_enrollments_with_invalid_hbx_members.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10828](https://devops.dchbx.org/redmine/issues/10828) |
| Start Date | 09/14/2016 |

10828: Renewal/Conversion EEs renewed with Dependents despite ineligibility. 

---

app/data_migrations/terminate_a_census_employee.rb
lib/tasks/terminate_a_census_employee.rake
spec/data_migrations/terminate_a_census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18436](https://devops.dchbx.org/redmine/issues/18436) |

18436: User unable to create user_record to link with EE person record

---

app/models/subscribers/policy_terminations_subscriber.rb
config/application.rb
spec/models/subscribers/policy_terminations_subscriber_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19142](https://devops.dchbx.org/redmine/issues/19142) |

19142: Create enroll listener to consume policy termination events

---

app/controllers/insured/families_controller.rb
app/controllers/insured/family_members_controller.rb
app/models/family.rb
app/views/insured/families/_shop_for_plans_widget.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/controllers/insured/family_members_controller_spec.rb
spec/factories/special_enrollment_periods.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18630](https://devops.dchbx.org/redmine/issues/18630) |

18630: Wrong effective date for loss of other coverage SEP

---

app/views/insured/families/verification/_documents_verification_list.html.erb
features/step_definitions/verification_process_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18556](https://devops.dchbx.org/redmine/issues/18556) |

18556: Addition to Docs FAQ for DC residency

---

app/data_migrations/fix_hub_verified_consumer.rb
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/person.rb
spec/data_migrations/fix_hub_verified_consumer_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18606](https://devops.dchbx.org/redmine/issues/18606) |

18606: Local Residency Title Change

---

app/controllers/insured/family_members_controller.rb
app/controllers/people_controller.rb
app/data_migrations/correct_citizen_with_ssn.rb
app/data_migrations/correct_non_citizen_with_ssn.rb
app/data_migrations/fix_citizen_for_hub_responses.rb
app/data_migrations/fix_hub_verified_consumer.rb
app/data_migrations/update_verification_types.rb
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/family.rb
app/models/person.rb
app/models/subscribers/local_residency.rb
spec/controllers/documents_controller_spec.rb
spec/controllers/insured/family_members_controller_spec.rb
spec/controllers/people_controller_spec.rb
spec/data_migrations/add_native_american_verification_spec.rb
spec/data_migrations/fix_hub_verified_consumer_spec.rb
spec/helpers/verification_helper_spec.rb
spec/models/consumer_role_spec.rb
spec/models/person_spec.rb
spec/models/subscribers/lawful_presence_spec.rb
spec/models/subscribers/local_residency_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18870](https://devops.dchbx.org/redmine/issues/18870) |

18870: Local Residency- "Attested" Residency is showing a due date

---

app/controllers/insured/family_members_controller.rb
app/controllers/people_controller.rb
app/data_migrations/correct_citizen_with_ssn.rb
app/data_migrations/correct_non_citizen_with_ssn.rb
app/data_migrations/fix_citizen_for_hub_responses.rb
app/data_migrations/fix_hub_verified_consumer.rb
app/data_migrations/update_verification_types.rb
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/family.rb
app/models/person.rb
app/models/subscribers/local_residency.rb
spec/controllers/documents_controller_spec.rb
spec/controllers/insured/family_members_controller_spec.rb
spec/controllers/people_controller_spec.rb
spec/data_migrations/add_native_american_verification_spec.rb
spec/data_migrations/fix_hub_verified_consumer_spec.rb
spec/helpers/verification_helper_spec.rb
spec/models/consumer_role_spec.rb
spec/models/person_spec.rb
spec/models/subscribers/lawful_presence_spec.rb
spec/models/subscribers/local_residency_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18867](https://devops.dchbx.org/redmine/issues/18867) |

18867: Local Residency- Children under 19 need to show an "Attested" status 

---

app/views/insured/families/verification/_documents_verification_list.html.erb
features/step_definitions/verification_process_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18902](https://devops.dchbx.org/redmine/issues/18902) |

18902: Open DMV attestation form in separate tab

---

app/data_migrations/change_office_phone_number.rb
app/models/phone.rb
lib/tasks/migrations/change_office_phone_number.rake
spec/data_migrations/change_office_phone_number_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18459](https://devops.dchbx.org/redmine/issues/18459) |

18459: Change contact person and phone number for two General Agency accounts

---

script/ivl_sep_query.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18722](https://devops.dchbx.org/redmine/issues/18722) |
| Ticket Author | Saadi Mirza |

18722: Update IVL enrollments query to pick up passive renewals

---

app/assets/javascripts/group_selection.js
app/helpers/insured/families_helper.rb
app/views/insured/families/_no_role_navigation.html.erb
app/views/insured/families/_shop_for_plans_widget.html.erb
app/views/insured/group_selection/new.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19422](https://devops.dchbx.org/redmine/issues/19422) |

19422: Remove "open enrollment is closed" and bypass SEP flow during OE

---

app/assets/stylesheets/custom.scss.erb
app/controllers/insured/consumer_roles_controller.rb
app/helpers/consumer_roles_helper.rb
app/models/family.rb
app/views/insured/consumer_roles/_form.html.erb
features/admin/curam_mobile_application.feature
features/admin/step_definitions/curam_mobile_application_steps.rb
features/step_definitions/individual_steps.rb
features/step_definitions/phone_application_steps.rb
spec/controllers/insured/consumer_roles_controller_spec.rb
spec/views/insured/consumer_roles/_form.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19087](https://devops.dchbx.org/redmine/issues/19087) |

19087: CURAM/Mobile Application

---

app/data_migrations/fix_plan_year.rb
lib/tasks/migrations/fix_plan_year.rake
spec/data_migrations/fix_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19447](https://devops.dchbx.org/redmine/issues/19447) |

19447: Fix PYs for Groups with Term Dates before Start Dates

---

app/models/benefit_group.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19117](https://devops.dchbx.org/redmine/issues/19117) |

19117: Investigate Why Employer Estimated Cost Times Out - Industry Dive

---

db/seedfiles/plans-sbcs.csv
plans-sbcs.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19553](https://devops.dchbx.org/redmine/issues/19553) |
| Ticket Author | Kenneth Taylor |

19553: CSR Variant SBC's not populating when eligible consumer enrolls. 

---

app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15490](https://devops.dchbx.org/redmine/issues/15490) |

15490: Admin "Phone" Action

---

app/data_migrations/create_renewal_plan_year_and_enrollment.rb
lib/tasks/migrations/create_renewal_plan_year_and_enrollment.rake
spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19358](https://devops.dchbx.org/redmine/issues/19358) |

19358: Generate 1/1/2018 renewal plan year

---

app/models/person.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19494](https://devops.dchbx.org/redmine/issues/19494) |

19494: User blocked from Account Access - We're Sorry Something Went Wrong Received after Login

---

app/models/factories/plan_year_renewal_factory.rb
spec/models/factories/plan_year_renewal_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19426](https://devops.dchbx.org/redmine/issues/19426) |
| Due Date | 11/17/2017  |

19426: Update Renewal Logic when Renewal Dental Plan Year not found

---

app/data_migrations/trigger_broker_invitation_url.rb
lib/tasks/migrations/trigger_broker_invitation_url.rake
spec/data_migrations/trigger_broker_invitation_url_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19502](https://devops.dchbx.org/redmine/issues/19502) |
| Due Date | 11/09/2017  |

19502: Approved broker never received magic URL invitation

---

app/data_migrations/change_person_family_member_linkage.rb
lib/tasks/change_person_family_member_linkage.rake
spec/data_migrations/change_person_family_member_linkage_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18804](https://devops.dchbx.org/redmine/issues/18804) |
| Ticket Author | @blackeaglejs |

18804: Update SSN

---

app/helpers/portal_header_helper.rb
spec/helpers/portal_header_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19442](https://devops.dchbx.org/redmine/issues/19442) |

19442: Clicking on "I'm an Employer" banner navigates to wrong URL

---

app/views/broker_agencies/quotes/_edit_form.html.erb
features/brokers/create_quote.feature
features/step_definitions/broker_employee_quote_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

BQT disable quote type- client and cucumber fix

---

app/models/admin/aptc.rb
spec/models/admin/aptc_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19866](https://devops.dchbx.org/redmine/issues/19866) |

19866: APTC Tool Current Year Configuration & Access

---

app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19688](https://devops.dchbx.org/redmine/issues/19688) |

19688: APTC admin tool access. 

---

features/step_definitions/integration_steps.rb
spec/factories/users.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fix cucumber in consumer_requests_enrollment.feature

---

app/helpers/events_helper.rb
app/models/hbx_enrollment.rb
spec/views/events/hbx_enrollment/policy.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19396](https://devops.dchbx.org/redmine/issues/19396) |

19396: Include cobra event date in enrollment event xmls

---

app/views/insured/consumer_roles/ridp_agreement.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19576](https://devops.dchbx.org/redmine/issues/19576) |

19576: minor text change auth and consent

---

app/data_migrations/change_broker_npn.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18885](https://devops.dchbx.org/redmine/issues/18885) |

18885: Please change broker's NPN in EA

---

app/controllers/broker_agencies/quotes_controller.rb
spec/controllers/broker_agencies/quotes_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18128](https://devops.dchbx.org/redmine/issues/18128) |
| Ticket Author | Error Reporting Robot |

18128: BSON::ObjectId::Invalid ('undefined' is an invalid ObjectId.):

---

app/models/family.rb
app/models/financial_assistance/application.rb
config/settings.yml
spec/models/family_spec.rb
spec/models/financial_assistance/application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20048](https://devops.dchbx.org/redmine/issues/20048) |

20048: FAA: Application Year is 2019

---

app/models/hbx_enrollment.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20130](https://devops.dchbx.org/redmine/issues/20130) |

20130: 2018 plans displaying for 2017 plan shopping

---

app/data_migrations/reinstate_plan_year.rb
lib/tasks/migrations/reinstate_plan_year.rake
spec/data_migrations/reinstate_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19933](https://devops.dchbx.org/redmine/issues/19933) |

19933: Reinstatement after termination for Non-payment- Washington Surgical Clinic

---

app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14689](https://devops.dchbx.org/redmine/issues/14689) |
| Ticket Author | @blackeaglejs |

14689: Responsible Party Enrollments lack relationship data

---

app/controllers/insured/group_selection_controller.rb
spec/controllers/insured/group_selection_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18819](https://devops.dchbx.org/redmine/issues/18819) |

18819: IVL users allowed to enter termination dates in the past

---

app/views/insured/families/_navigate_to_curam_for_documents.html.erb
app/views/insured/families/inbox.html.erb
app/views/insured/families/verification.html.erb
features/insured/individual_curam_document.feature
features/insured/step_definitions/individual_curam_document_steps.rb
spec/views/insured/families/_navigate_to_curam_for_documents.html.erb_spec.rb
spec/views/insured/families/inbox.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19176](https://devops.dchbx.org/redmine/issues/19176) |
| Due Date | 11/01/2017  |

19176: Add buttons to connect to Curam from Messages and Docs tabs

---

app/data_migrations/update_person_relationship_kind.rb
spec/data_migrations/update_person_relationship_kind_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19827](https://devops.dchbx.org/redmine/issues/19827) |

19827: Primary blocked from enrolling by family relationships error

---

app/views/insured/consumer_roles/_form.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #19087 check for e_case_id

---

app/data_migrations/move_user_account_between_two_people_accounts.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19195](https://devops.dchbx.org/redmine/issues/19195) |

19195: merge ER and EE accounts - 19829091

---

Gemfile
Gemfile.lock
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/hbx_enrollment.rb
app/models/history_action_tracker.rb
app/models/history_tracker.rb
app/models/lawful_presence_determination.rb
app/models/person.rb
app/models/vlp_document.rb
app/views/insured/families/verification/_verification.html.erb
app/views/insured/families/verification/_verification_history.html.erb
config/initializers/mongoid_history.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17242](https://devops.dchbx.org/redmine/issues/17242) |

17242: View Verification Type History-Ability to store Verifications history in EA database 

---

script/cobra_enrollment_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20285](https://devops.dchbx.org/redmine/issues/20285) |
| Ticket Author | Saadi Mirza |

20285: Operationalize daily COBRA Reports

---

app/views/exchanges/hbx_profiles/_family_index_datatable.html.erb
features/cover_all/consumer_requests_enrollment.feature
features/step_definitions/cover_all_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15492](https://devops.dchbx.org/redmine/issues/15492) |
| Due Date | 10/16/2017  |

15492: Admin Action: Disable "Paper" Action

---

app/views/insured/interactive_identity_verifications/_outstanding_ridp_documents.html.erb
app/views/insured/ridp_documents/destroy.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20250](https://devops.dchbx.org/redmine/issues/20250) |
| Ticket Author | @sudhirreddysama |

20250: When Admin click on delete icon in Experian Error Screen page not reloading

---

app/models/consumer_role.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19491](https://devops.dchbx.org/redmine/issues/19491) |
| Ticket Author | Cudjoe . |

19491: DC Residency: Verified shows Due Date

---

app/models/consumer_role.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20029](https://devops.dchbx.org/redmine/issues/20029) |

20029: Congressional EE Blocked by "The change you wanted was rejected" Error

---

app/helpers/time_helper.rb
app/models/special_enrollment_period.rb
spec/helpers/time_helper_spec.rb
spec/models/special_enrollment_period_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20296](https://devops.dchbx.org/redmine/issues/20296) |

20296: Unable to get SEP effective date in the past

---

app/models/hbx_enrollment.rb
app/models/subscribers/policy_terminations_subscriber.rb
spec/models/hbx_enrollment_spec.rb
spec/models/subscribers/policy_terminations_subscriber_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20215](https://devops.dchbx.org/redmine/issues/20215) |

20215: Update PolicyTerminationSubscriber to trigger correct transition

---

app/controllers/insured/consumer_roles_controller.rb
spec/controllers/insured/consumer_roles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20376](https://devops.dchbx.org/redmine/issues/20376) |

20376: CURAM/Mobile Application - Assisted Portal scenario

---

app/models/eligibility/employee_benefit_packages.rb
app/models/factories/enrollment_renewal_builder.rb
app/models/factories/shop_enrollment_renewal_factory.rb
app/models/hbx_enrollment.rb
features/employee/employee_passive_renewal_update.feature
features/step_definitions/new_hire_steps.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20371](https://devops.dchbx.org/redmine/issues/20371) |

20371: There can only be one passive renewal per enrollment period

---

app/data_migrations/fix_is_subscriber_for_responsible_party_enrollments.rb
app/models/hbx_enrollment.rb
app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml
lib/tasks/migrations/fix_is_subscriber_for_responsible_party_enrollments.rake
spec/data_migrations/fix_is_subscriber_for_responsible_party_enrollments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10690](https://devops.dchbx.org/redmine/issues/10690) |
| Ticket Author | Saadi Mirza |

10690: EDI for Responsible party enrollments in the IVL market must flow automatically.

---

app/views/insured/interactive_identity_verifications/_outstanding_ridp_documents.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20661](https://devops.dchbx.org/redmine/issues/20661) |
| Ticket Author | @sudhirreddysama |

20661: In RIDP Document upload screen when click attached file Not downloading

---

app/controllers/documents_controller.rb
app/models/special_verification.rb
script/ivl_renewal_notices.rb
spec/factories/special_verifications.rb
spec/models/special_verification_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20486](https://devops.dchbx.org/redmine/issues/20486) |
| Due Date | 12/20/2017  |

20486: Update past-due deadlines for FRE notice

---

app/data_migrations/move_due_date_to_verification_type_level.rb
lib/tasks/migrations/move_due_date_to_verification_type_level.rake
spec/data_migrations/move_due_date_to_verification_type_level_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18855](https://devops.dchbx.org/redmine/issues/18855) |

18855: Need to create a rake task to update existing outstanding verifications in EA that are at the enrollment level

---

app/helpers/insured/families_helper.rb
app/views/insured/families/_sep_message.html.erb
app/views/insured/families/_shop_for_plans_widget.html.erb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20294](https://devops.dchbx.org/redmine/issues/20294) |

20294: Dual role user not seeing IVL SEP

---

app/data_migrations/remove_coverage_household_member.rb
app/data_migrations/remove_dependent.rb
lib/tasks/migrations/remove_coverage_household_member.rake
lib/tasks/migrations/remove_dependent.rake
spec/data_migrations/remove_coverage_household_member_spec.rb
spec/data_migrations/remove_dependent_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18421](https://devops.dchbx.org/redmine/issues/18421) |

18421: Remove duplicate dependent in EA

---

script/opted_for_paper_communication_in_shop.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18872](https://devops.dchbx.org/redmine/issues/18872) |

18872: Need a report of employer and employees that have elected "electronic + paper communications"

---

app/models/factories/family_enrollment_clone_factory.rb
spec/models/factories/family_enrollment_clone_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20353](https://devops.dchbx.org/redmine/issues/20353) |

20353: Cobra switchovers cause premium re-calculation

---

spec/models/hbx_enrollment_spec.rb
spec/models/plan_year_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

spec fix plan year and hbx enrollment

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20347](https://devops.dchbx.org/redmine/issues/20347) |

20347: EnrollApp - Policy End Date Silent Updates (12-11-17)

---

app/models/organization.rb
app/notices/shop_employer_notice.rb
spec/factories/office_locations.rb
spec/models/organization_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20592](https://devops.dchbx.org/redmine/issues/20592) |

20592: DC SHOP Notice Cover Sheet - Pull Mailing Address

---

app/views/notices/ivl/documents_section.html.erb
app/views/notices/ivl/final_eligibility_notice_uqhp_aqhp.html.erb
script/ivl_renewal_notices.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20498](https://devops.dchbx.org/redmine/issues/20498) |

20498: AQHP Final Eligibility Notice (Renewal) - IVL_FRE

---

app/data_migrations/import_2019_ivl_benefit_package.rb
lib/tasks/import_2019_ivl_benefit_package.rake
spec/data_migrations/import_2019_ivl_benefit_package_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20808](https://devops.dchbx.org/redmine/issues/20808) |
| Ticket Author | @Battula |

20808: Create 2019 IVL benefit packages

---

app/data_migrations/move_phone_between_person_accounts.rb
app/data_migrations/remove_employer_staff_role_from_person.rb
lib/tasks/migrations/move_phone_between_person_accounts.rake
lib/tasks/migrations/remove_employer_staff_role_from_person.rake
spec/data_migrations/move_phone_between_person_accounts_spec.rb
spec/data_migrations/remove_employer_staff_role_from_person_sepc.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18642](https://devops.dchbx.org/redmine/issues/18642) |

18642: Duplicate Person_Record - Clean Up

---

app/views/financial_assistance/applications/steps.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19655](https://devops.dchbx.org/redmine/issues/19655) |
| Ticket Author | Tatyana Lukasheva |

19655: Submit Your Application page 

---

app/models/hbx_enrollment.rb
app/views/events/hbx_enrollment/_policy.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20698](https://devops.dchbx.org/redmine/issues/20698) |

20698: Make sure enroll includes previous policy id tag for re-instates

---

app/views/events/individuals/_individual.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20675](https://devops.dchbx.org/redmine/issues/20675) |

20675: Ensure individual resource in enroll includes person relationships

---

app/assets/javascripts/financial_assistance/income.js
app/views/financial_assistance/shared/_left_nav.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19037](https://devops.dchbx.org/redmine/issues/19037) |

19037: FAA: Duplicate instances created when adding additional other incomes

---

app/models/admin/aptc.rb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19701](https://devops.dchbx.org/redmine/issues/19701) |
| Ticket Author | Mark Joseph |

19701: Applied APTC greater than Premium

---

app/data_migrations/delink_broker_agency.rb
lib/tasks/delink_broker_agency.rake
spec/data_migrations/delink_broker_agency_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20694](https://devops.dchbx.org/redmine/issues/20694) |

20694: we're sorry enrollment blocker 

---

app/data_migrations/correct_employees_with_incorrect_waivers.rb
lib/tasks/migrations/correct_employees_with_incorrect_waivers.rake
spec/data_migrations/correct_employees_with_incorrect_waivers_spec.rb
spec/lib/object_builders/qhp_rate_builder_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_aqhp_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_renewal_aqhp_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_renewal_uqhp_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_uqhp_spec.rb
spec/notices/shop_employer_notices/employer_renewal_eligibility_denial_notice_spec.rb
spec/notices/shop_employer_notices/renewal_employer_eligibility_notice_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Spex fixes master

---

script/broker_assignment_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18626](https://devops.dchbx.org/redmine/issues/18626) |
| Start Date | 10/02/2017 |
| Due Date | 10/02/2017  |

18626: Broker Assignment Report - October

---

script/general_agency_assignment_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18645](https://devops.dchbx.org/redmine/issues/18645) |
| Start Date | 10/02/2017 |
| Due Date | 10/02/2017  |

18645: General Agency Assignments for SHOP - October

---

app/helpers/events_helper.rb
app/models/hbx_enrollment.rb
app/models/queries/named_policy_queries.rb
app/models/queries/shop_monthly_enrollments.rb
app/views/events/enrollment_event.xml.haml
app/views/events/hbx_enrollment/_policy.xml.haml
app/views/events/hbx_enrollment/policy.xml.haml
app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml
script/shop_sep_query.rb
spec/models/queries/named_policy_queries_spec.rb
spec/views/events/hbx_enrollment/policy.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20715](https://devops.dchbx.org/redmine/issues/20715) |

20715: Master tracking ticket for enroll status for cobra edi code

---

db/seedfiles/notice_triggers_seed.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20986](https://devops.dchbx.org/redmine/issues/20986) |

20986: Update Subject Lines for 2nd, 3rd, and 4th Reminder Notices

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20303](https://devops.dchbx.org/redmine/issues/20303) |
| Ticket Author | Diane Santiago |

20303:  HBX 158622 please add enrollment ID: 935532 effective 1/4/18 that's in glue to  EA

---

app/controllers/insured/group_selection_controller.rb
app/models/benefit_coverage_period.rb
spec/controllers/insured/group_selection_controller_spec.rb
spec/models/benefit_coverage_period_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20996](https://devops.dchbx.org/redmine/issues/20996) |

20996: Mid-month termination dates being changed to 1/31/2018

---

app/notices/ivl_notices/reminder_notice.rb
spec/notices/ivl_notices/reminder_notice_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20898](https://devops.dchbx.org/redmine/issues/20898) |

20898: Citizenship document type not populated in docs need in Reminder Notice

---

app/views/financial_assistance/applications/review_and_submit.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21122](https://devops.dchbx.org/redmine/issues/21122) |
| Ticket Author | Joshua Karper |

21122: Correct Applicant level Pencil Links on the "Review Your Application" page

---

lib/tasks/hbx_reports/families_with_invalid_plan.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20041](https://devops.dchbx.org/redmine/issues/20041) |
| Ticket Author | Luis Vasquez |

20041: Changing Network Field Value from Nationwide to DC Metro

---

app/data_migrations/remove_coverage_household_member.rb
app/models/coverage_household.rb
spec/data_migrations/remove_coverage_household_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20789](https://devops.dchbx.org/redmine/issues/20789) |

20789: Dependent showing up twice in plan shopping when only selected once

---

app/data_migrations/change_enrollment_details.rb
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20829](https://devops.dchbx.org/redmine/issues/20829) |

20829: silent cancel in EA

---

app/helpers/financial_assistance_helper.rb
features/financial_assistance/display_of_family_relationships_link.feature
features/financial_assistance/review_your_application_page.feature
features/financial_assistance/step_definitions/review_your_application_page_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20445](https://devops.dchbx.org/redmine/issues/20445) |

20445: Additional Scenarios: Review Your Application 

---

app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21165](https://devops.dchbx.org/redmine/issues/21165) |

21165: Coverage expired enrollments have empty end date tags

---

lib/tasks/migrations/create_published_plan_years_for_certain_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21191](https://devops.dchbx.org/redmine/issues/21191) |

21191: Transition 2/1 Renewal Group (FEIN 520943763) to Renewing_Enrolling

---

features/financial_assistance/step_definitions/review_your_application_page_steps.rb
features/financial_assistance/step_definitions/your_preferences_page_steps.rb
features/financial_assistance/your_preferences_page.feature
features/step_definitions/financial_assistance_flow_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21322](https://devops.dchbx.org/redmine/issues/21322) |
| Ticket Author | Joshua Karper |

21322: Add cucumber scenarios : FAA - Your Preferences

---

app/views/financial_assistance/applications/review_and_submit.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21290](https://devops.dchbx.org/redmine/issues/21290) |

21290: Non-applicant changed to applicant during FAA

---

Gemfile
Gemfile.lock

We've been using this for almost a year, make it official and move off
of development.

Use stable gem.

---

app/data_migrations/trigger_shop_notices.rb
lib/tasks/trigger_shop_notices.rake
spec/data_migrations/trigger_shop_notices_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21241](https://devops.dchbx.org/redmine/issues/21241) |

21241: DC SHOP Notice Trigger Bug - DIG020 - Initial ER OE failed minimum participation/non-owner not triggering for 2/1/2018 ERs

---

app/data_migrations/correct_decertified_agencies.rb
app/models/effective/datatables/general_agency_data_table.rb
app/views/broker_agencies/profiles/_employer_datatable_entry.json.erb
app/views/general_agencies/profiles/_index.html.erb
lib/tasks/correct_decertified_agencies.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21217](https://devops.dchbx.org/redmine/issues/21217) |

21217: Brokers unable to access their clients who have Insurance Marketing Center assigned as a GA

---

app/models/person.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21318](https://devops.dchbx.org/redmine/issues/21318) |

21318: Pending Brokers incorrectly displaying on the Certified Brokers tab

---

app/data_migrations/clone_consumer_role.rb
lib/tasks/clone_consumer_role.rake
spec/data_migrations/clone_consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20272](https://devops.dchbx.org/redmine/issues/20272) |

20272: Duplicate Person_Record - Clean Up

---

app/controllers/session_timeout_controller.rb
app/models/effective/datatables/employer_datatable.rb
app/views/devise/sessions/session_expiration_warning.js.erb
app/views/devise/sessions/sign_out_user.js.erb
app/views/layouts/_header.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17925](https://devops.dchbx.org/redmine/issues/17925) |

17925: Check time until logout loop eventually checks continually

---

app/models/plan.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18636](https://devops.dchbx.org/redmine/issues/18636) |
| Ticket Author | Error Reporting Robot |

18636: NoMethodError (undefined method `by_nationwide' for #<Mongoid::Criteria:0x007fccc4b60858>):

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17952](https://devops.dchbx.org/redmine/issues/17952) |

17952: EA - COBRA renewal premium correction

---

spec/data_migrations/clone_consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21558](https://devops.dchbx.org/redmine/issues/21558) |

21558: make spec pass consistently on Jenkins Build

---

features/financial_assistance/other_questions_page.feature
features/financial_assistance/step_definitions/other_questions_page_steps.rb
features/support/env.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21519](https://devops.dchbx.org/redmine/issues/21519) |

21519: FAA Cucumbers: Other Questions and Conditionals

---

app/data_migrations/link_employees_to_employer.rb
lib/tasks/link_employees_to_employer.rake
spec/data_migrations/link_employees_to_employer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20351](https://devops.dchbx.org/redmine/issues/20351) |
| Ticket Author | Kionna Spann |

20351: No Account Linked Display Issue

---

app/models/financial_assistance/benefit.rb
app/models/financial_assistance/deduction.rb
app/models/financial_assistance/income.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21613](https://devops.dchbx.org/redmine/issues/21613) |

21613: Income is stored as an integer

---

app/data_migrations/change_broker_details.rb
spec/data_migrations/change_broker_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21324](https://devops.dchbx.org/redmine/issues/21324) |

21324: Fix issue to properly display individual brokers 

---

app/views/financial_assistance/benefits/index.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21272](https://devops.dchbx.org/redmine/issues/21272) |

21272: Income type listed twice 

---

app/views/financial_assistance/applications/help_paying_coverage.html.erb
app/views/insured/family_members/index.html.erb
app/views/shared/_left_nav.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20977](https://devops.dchbx.org/redmine/issues/20977) |

20977: UQHP Household Info Page

---

lib/tasks/hbx_reports/newly_registered_persons_data_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21659](https://devops.dchbx.org/redmine/issues/21659) |
| Due Date | 01/31/2018  |

21659: Generate Report for 11/1/17 to Present- Add ee and ivl role indicators to reports-new-people

---

app/notices/shop_employer_notices/employer_invoice_available.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21444](https://devops.dchbx.org/redmine/issues/21444) |
| Due Date | 02/01/2018  |

21444: Turn off emails to brokers/GAs when DC SHOP Notice DAG021 - Monthly Invoice Available - Non-implementation Cycle

---

app/models/plan_year.rb
spec/models/plan_year_publishing_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21248](https://devops.dchbx.org/redmine/issues/21248) |

21248: Port 16782 from MA into DC.

---

app/notices/shop_employee_notices/notify_employee_of_initial_employer_ineligibility.rb
app/notices/shop_employer_notices/initial_employer_denial_notice.rb
app/notices/shop_employer_notices/initial_employer_eligibility_notice.rb
spec/notices/shop_employer_notices/initial_employer_eligibility_notice_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21630](https://devops.dchbx.org/redmine/issues/21630) |

21630: DC SHOP Notice Bug - DIG002 Approval notice has incorrect dates DupontStudios (462690344)

---

app/controllers/insured/consumer_roles_controller.rb
app/views/shared/_individual_progress.html.haml
features/insured/individual_ridp_verification.feature
features/step_definitions/individual_ridp_verification_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21182](https://devops.dchbx.org/redmine/issues/21182) |

21182: RIDP- Consumer able to upload an identity document ONLY and proceed

---

app/models/tax_household.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21869](https://devops.dchbx.org/redmine/issues/21869) |

21869: Performance Issue on selecting Plan for APTC cases.

---

app/models/household.rb
app/models/tax_household.rb
config/mongoid.yml
lib/tasks/create_tax_household.rake
spec/models/household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21624](https://devops.dchbx.org/redmine/issues/21624) |

21624: Build Task for Eligibility Creation of Individual Cases

---

app/data_migrations/upload_notice_to_employer_account.rb
lib/tasks/upload_notice_for_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21147](https://devops.dchbx.org/redmine/issues/21147) |

21147: Upload Termination Notice to Employer Secured Message Inbox in EA-  January 2018

---

app/data_migrations/change_renewing_plan_year_aasm_state.rb
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21264](https://devops.dchbx.org/redmine/issues/21264) |

21264: Transition 2/1/2018 Groups to "Renewing_Enrolled"

---

features/financial_assistance/other_income_page.feature
features/financial_assistance/step_definitions/other_income_page_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21521](https://devops.dchbx.org/redmine/issues/21521) |

21521: FAA Cucumber: Other Income Page

---

script/enrollment_affected_people.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20897](https://devops.dchbx.org/redmine/issues/20897) |

20897: Report of all cases impacted by ENR notice not populating citizenship documentation requirement (bug 20845)

---

app/data_migrations/fix_plan_year.rb
lib/tasks/migrations/fix_plan_year.rake
spec/data_migrations/fix_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21867](https://devops.dchbx.org/redmine/issues/21867) |

21867: Group Clean Up Needed  - GLOBAL BUSINESS SCHOOL NETWORK

---

app/models/eligibility/census_employee.rb
app/models/special_enrollment_period.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12772](https://devops.dchbx.org/redmine/issues/12772) |

12772: Employee on two conversion ER rosters cannot proceed to match page when creating their account - 500 Error Received

---

app/views/events/financial_assistance/_applicant_information.xml.haml
app/views/events/financial_assistance/_benefit.xml.haml
app/views/events/financial_assistance/_income.xml.haml
app/views/events/financial_assistance_application.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22301](https://devops.dchbx.org/redmine/issues/22301) |

22301: Conditional Transmission of FAA fields. 

---

app/data_migrations/add_new_eligibility_determination.rb
spec/data_migrations/add_new_eligibility_determination_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18868](https://devops.dchbx.org/redmine/issues/18868) |
| Ticket Author | Grizelda Mejia |

18868: CSR and Aptc reset

---

script/get_resident_enrollments_in_ea.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20944](https://devops.dchbx.org/redmine/issues/20944) |

20944: Report of all users with resident role

---

script/reminder_notice_issue.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20900](https://devops.dchbx.org/redmine/issues/20900) |

20900: Report of cases where Citizenship document type not populated in docs need in Reminder Notice

---

app/notices/notice.rb
app/views/notices/shared/_address.html.erb
app/views/notices/shared/_cover_page.html.erb
app/views/notices/shared/_shop_address.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21928](https://devops.dchbx.org/redmine/issues/21928) |

21928: IVL_ENR Enrollment Notice Address is not fitting within the address window of the envelope

---

app/views/insured/interactive_identity_verifications/failed_validation.html.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21993](https://devops.dchbx.org/redmine/issues/21993) |

21993: Remove duplicate "Help me sign up" on identity/app doc upload page

---

app/data_migrations/change_initial_plan_year_aasm_state.rb
lib/tasks/migrations/change_initial_plan_year_aasm_state.rake
spec/data_migrations/change_initial_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22245](https://devops.dchbx.org/redmine/issues/22245) |

22245: Transition 3/1 group to enrolled - Office Of The Military, Naval & Air Attache, Embassy Of Myanmar

---

app/data_migrations/reinstate_plan_year.rb
lib/tasks/migrations/reinstate_plan_year.rake
spec/data_migrations/reinstate_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22394](https://devops.dchbx.org/redmine/issues/22394) |

22394: Reinstatement after termination for Non-payment- Law Offices Of Kurosh Nasseri PLLC

---

app/models/family.rb
app/models/household.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22146](https://devops.dchbx.org/redmine/issues/22146) |

22146: Modify Eligibility Creation Task to not consider inactive FamilyMembers when creating THHMs

---

app/views/financial_assistance/applications/steps.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21291](https://devops.dchbx.org/redmine/issues/21291) |

21291: Text changes for voter registration in FAA

---

app/data_migrations/remove_dependent.rb
spec/data_migrations/remove_dependent_spec.rb
spec/factories/families.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22258](https://devops.dchbx.org/redmine/issues/22258) |

22258: Unable to Remove Duplicate Family Member

---

app/helpers/application_helper.rb
app/models/tax_household.rb
app/models/tax_household_member.rb
lib/tasks/update_tax_household_member.rake
spec/helpers/application_helper_spec.rb
spec/models/tax_household_member_spec.rb
spec/models/tax_household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22465](https://devops.dchbx.org/redmine/issues/22465) |

22465: Create a Rake Task to update APTC / Medicaid Eligibilities on Tax Household Member

---

app/models/subscribers/financial_assistance_application_eligibility_response.rb
spec/controllers/insured/verification_documents_controller_spec.rb
spec/models/admin/aptc_spec.rb
spec/models/family_spec.rb
spec/models/subscribers/financial_assistance_application_eligibility_response_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

faa specs fixed

---

app/data_migrations/add_primary_family.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

spec fixed

---

lib/tasks/hbx_reports/families_with_invalid_plan.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22118](https://devops.dchbx.org/redmine/issues/22118) |

22118: Critical CareFirst "Plus" Plan Network Update Needed - Nationwide to DC Metro

---

app/data_migrations/change_enrollment_member_applicant_id.rb
app/data_migrations/remove_family_member_from_coverage_household.rb
lib/tasks/change_enrollment_member_applicant_id.rake
lib/tasks/migrations/remove_family_member_from_coverage_household.rake
spec/data_migrations/change_enrollment_member_applicant_id_spec.rb
spec/data_migrations/remove_family_member_from_coverage_household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20140](https://devops.dchbx.org/redmine/issues/20140) |

20140: Remove duplicate dependents in EA

---

app/assets/javascripts/financial_assistance/step_conditionals.js
features/financial_assistance/applicant_level_navigation.feature
features/financial_assistance/other_income_page.feature
features/financial_assistance/step_definitions/applicant_level_navigation_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21281](https://devops.dchbx.org/redmine/issues/21281) |

21281: Not sure pop-up

---

app/views/events/enrollment_event.xml.haml
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13216](https://devops.dchbx.org/redmine/issues/13216) |

13216: Exchange ID is incorrect in the enrollment_event resource xml

---

app/controllers/application_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/families_controller.rb
app/controllers/insured/family_members_controller.rb
app/controllers/insured/group_selection_controller.rb
app/controllers/insured/plan_shoppings_controller.rb
app/helpers/consumer_roles_helper.rb
app/models/consumer_role.rb
app/views/insured/consumer_roles/upload_ridp_document.html.haml
app/views/insured/interactive_identity_verifications/failed_validation.html.haml
app/views/insured/interactive_identity_verifications/service_unavailable.html.haml
features/insured/individual_ridp_verification.feature
features/step_definitions/individual_ridp_verification_steps.rb
spec/helpers/consumer_roles_helper_spec.rb
spec/views/insured/interactive_identity_verifications/failed_validation.html.haml_spec.rb
spec/views/insured/interactive_identity_verifications/service_unavailable.html.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22089](https://devops.dchbx.org/redmine/issues/22089) |
| Ticket Author | Cudjoe . |

22089: Admin & Customer unable to view my account page

---

app/helpers/application_helper.rb
app/models/plan_year.rb
spec/helpers/application_helper_spec.rb
spec/models/plan_year_spec.rb
spec/views/employers/employer_profiles/my_account/home_tab.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21796](https://devops.dchbx.org/redmine/issues/21796) |

21796: Increase EE count that disables the enrollment and waiver meter

---

app/controllers/employers/broker_agency_controller.rb
spec/controllers/employers/broker_agency_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18750](https://devops.dchbx.org/redmine/issues/18750) |
| Ticket Author | Error Reporting Robot |

18750: ActionView::MissingTemplate (Missing template employers/broker_agency/index, application/index with 

---

app/views/exchanges/hbx_profiles/_get_user_info.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19840](https://devops.dchbx.org/redmine/issues/19840) |

19840: Can't see full e-case ID and person role for Curam cases in EA families tab

---

app/controllers/broker_agencies/inboxes_controller.rb
spec/controllers/broker_agencies/inboxes_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21365](https://devops.dchbx.org/redmine/issues/21365) |

21365: Unable to open secure message and notices in prod

---

app/models/effective/datatables/outstanding_verification_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22134](https://devops.dchbx.org/redmine/issues/22134) |

22134: Date format on verifications tab changes after searching

---

app/views/notices/ivl/documents_section.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22310](https://devops.dchbx.org/redmine/issues/22310) |

22310: Minor text changed needed to Documents Needed insert

---

app/data_migrations/match_coverage_household_with_family_member.rb
lib/tasks/migrations/match_coverage_household_with_family_member.rake
spec/data_migrations/match_coverage_household_with_family_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22917](https://devops.dchbx.org/redmine/issues/22917) |

22917: 404 Error Received during SEP shopping

---

app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/families_controller.rb
app/views/insured/consumer_roles/upload_ridp_document.html.haml
app/views/insured/interactive_identity_verifications/failed_validation.html.haml
app/views/insured/interactive_identity_verifications/service_unavailable.html.haml
app/views/shared/_application_types_list.html.erb
config/routes.rb
spec/controllers/insured/consumer_roles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22247](https://devops.dchbx.org/redmine/issues/22247) |

22247: Admin unable to change application type on application started by consumer

---

config/settings.yml

Enable individual market, dental market, general agencies.
* (Required!)
* ()
* ()
```
```
*
---
---

Update settings.yml for DC related values

---

components/sponsored_benefits/app/models/sponsored_benefits/benefit_markets/aca_individual_configuration.rb
components/sponsored_benefits/app/models/sponsored_benefits/benefit_markets/aca_shop_configuration.rb
components/sponsored_benefits/app/models/sponsored_benefits/benefit_markets/aca_shop_initial_application_configuration.rb
components/sponsored_benefits/app/models/sponsored_benefits/benefit_markets/aca_shop_renewal_application_configuration.rb
components/sponsored_benefits/app/models/sponsored_benefits/benefit_markets/benefit_market.rb
components/sponsored_benefits/spec/factories/sponsored_benefits_benefit_markets_aca_shop_initial_application_configurations.rb
components/sponsored_benefits/spec/factories/sponsored_benefits_benefit_markets_aca_shop_renewal_application_configurations.rb
components/sponsored_benefits/spec/models/sponsored_benefits/benefit_markets/aca_shop_configuration_spec.rb
components/sponsored_benefits/spec/models/sponsored_benefits/benefit_markets/aca_shop_initial_application_configuration_spec.rb
components/sponsored_benefits/spec/models/sponsored_benefits/benefit_markets/aca_shop_renewal_application_configuration_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22983](https://devops.dchbx.org/redmine/issues/22983) |
| Ticket Author | @billy-ran-away |

22983: Start and finish AcaShopConfiguration specs

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23096](https://devops.dchbx.org/redmine/issues/23096) |
| Ticket Author | @billy-ran-away |

23096: On Click of any Employer - We are sorry message is displayed

---

app/controllers/exchanges/residents_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/families_controller.rb
app/controllers/people_controller.rb
app/data_migrations/change_incorrect_bookmark_url_in_consumer_role.rb
app/models/forms/family_member.rb
app/models/importers/transcripts/person_transcript.rb
app/models/person.rb
app/models/transcripts/comparison_result.rb
app/models/transcripts/person_transcript.rb
app/notices/ivl_notices/final_eligibility_notice_renewal_uqhp.rb
app/notices/ivl_notices/final_eligibility_notice_uqhp.rb
app/views/shared/_address_fields_for_dependent.html.erb
app/views/shared/_consumer_home_address_fields.html.erb
app/views/shared/_resident_home_address_fields.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/models/forms/family_member_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23008](https://devops.dchbx.org/redmine/issues/23008) |

23008: Homeless/Temporarily Out of State Model Update

---

app/assets/javascripts/consumer_role.js
app/assets/stylesheets/application.scss.erb
app/controllers/exchanges/residents_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/families_controller.rb
app/controllers/people_controller.rb
app/data_migrations/change_incorrect_bookmark_url_in_consumer_role.rb
app/models/forms/family_member.rb
app/models/importers/transcripts/person_transcript.rb
app/models/person.rb
app/models/transcripts/comparison_result.rb
app/models/transcripts/person_transcript.rb
app/notices/ivl_notices/final_eligibility_notice_renewal_uqhp.rb
app/notices/ivl_notices/final_eligibility_notice_uqhp.rb
app/views/shared/_address_fields_for_dependent.html.erb
app/views/shared/_consumer_home_address_fields.html.erb
app/views/shared/_resident_home_address_fields.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/models/forms/family_member_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22529](https://devops.dchbx.org/redmine/issues/22529) |

22529: FAA UI: Is_temp_out_of_state

---

app/data_migrations/add_family_member_to_coverage_household.rb
lib/tasks/migrations/add_family_member_to_coverage_household.rake
spec/data_migrations/add_family_member_to_coverage_household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22988](https://devops.dchbx.org/redmine/issues/22988) |

22988: APTC Availability

---

app/data_migrations/remove_resident_role.rb
lib/tasks/migrations/remove_resident_role.rake
spec/data_migrations/remove_resident_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21038](https://devops.dchbx.org/redmine/issues/21038) |

21038: Test removal of CoverAll DC roles

---

app/assets/javascripts/financial_assistance/income.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23286](https://devops.dchbx.org/redmine/issues/23286) |

23286: Unable to uncheck checkboxes in FAA branch

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

change ma to dc for s3 and exchange hbx id

---

app/controllers/documents_controller.rb
app/data_migrations/fix_document_status_on_family.rb
app/views/insured/families/verification/_verification.html.erb
lib/tasks/fix_document_status_on_family.rake
spec/controllers/documents_controller_spec.rb
spec/data_migrations/fix_document_status_on_family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22136](https://devops.dchbx.org/redmine/issues/22136) |
| Ticket Author | Selamawit Teka |

22136: Outstanding verification item for immigration showing under 'fully uploaded' tab on the verification page

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23066](https://devops.dchbx.org/redmine/issues/23066) |

23066: Seeding Fails in Master

---

app/views/documents/destroy.js.erb
app/views/insured/families/verification/_verification.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20572](https://devops.dchbx.org/redmine/issues/20572) |
| Ticket Author | @sudhirreddysama |

20572: When click on delete Icon in Documents screen of a user's account not updating in view history

---

app/data_migrations/change_census_employee_details.rb
app/models/census_employee.rb
lib/tasks/change_census_employee_details.rake
spec/data_migrations/change_census_employee_details_spec.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21214](https://devops.dchbx.org/redmine/issues/21214) |

21214: Senate Employee - Account Merge Needed

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

removed the error message while running the spec

---

app/assets/javascripts/qle.js.erb
app/views/insured/families/_qle_detail.html.erb
app/views/insured/families/_qle_detail_for_existing_sep.erb
features/admin/admin_sep_selection.feature
features/insured/individual_sep_signup.feature
features/step_definitions/individual_steps.rb
features/step_definitions/outstanding_verifications.rb
spec/factories/qualifying_life_event_kinds.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19939](https://devops.dchbx.org/redmine/issues/19939) |

19939: SEP admin tool issue 

---

config/mongoid.yml

* (Required!)
* ()
* ()
```
```
*
---
---

changed  mongoid.yml settings for database

---

lib/tasks/hbx_reports/employer_roster_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21255](https://devops.dchbx.org/redmine/issues/21255) |

21255: er_roster_report additions

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23283](https://devops.dchbx.org/redmine/issues/23283) |
| Ticket Author | Prem Shaganti |

23283: Footer and should reflect DC changes on PVT env.

---

app/views/insured/family_members/_dependent_coverall.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22343](https://devops.dchbx.org/redmine/issues/22343) |
| Ticket Author | India Anderson |

22343: Unable to utilize manage family tab in EA for HBX:175668

---

app/controllers/insured/employee_roles_controller.rb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23653](https://devops.dchbx.org/redmine/issues/23653) |
| Ticket Author | @jayreddy519 |

23653: Signup URL redirecting to Wrong page

---

app/data_migrations/update_py_announced_externally_flag.rb
app/models/employer_profile.rb
app/models/plan_year.rb
lib/tasks/migrations/update_py_announced_externally_flag.rake
spec/data_migrations/update_py_announced_externally_flag_spec.rb
spec/models/employer_profile_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22349](https://devops.dchbx.org/redmine/issues/22349) |

22349: Give Plan Years the Ability to Remember if they have been announced externally

---

app/controllers/financial_assistance/applications_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22830](https://devops.dchbx.org/redmine/issues/22830) |

22830: Demo Mock Eligibility 

---

config/settings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

settings values for DC

---

app/notices/shop_employer_notices/employer_invoice_available.rb
spec/notices/shop_employer_notices/employer_invoice_available_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21524](https://devops.dchbx.org/redmine/issues/21524) |

21524: DC SHOP Notice Trigger Bug - DAG021 - Monthly Invoice Available - Non-implementation Cycle - Trigger to groups in all PY states

---

lib/tasks/upload_notice_for_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22843](https://devops.dchbx.org/redmine/issues/22843) |
| Ticket Author | Chad Morton |

22843: Upload Termination Notice to Employer Secured Message Inbox in EA- March 2018 (3-6-2018)

---

app/views/events/individuals/_individual.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23788](https://devops.dchbx.org/redmine/issues/23788) |

23788: Relationship Structure in CV Incorrect

---

lib/tasks/verification_reports/verified_verification_reports.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22754](https://devops.dchbx.org/redmine/issues/22754) |

22754: Retro Report Generation - February

---

app/data_migrations/invoke_hub_response.rb
lib/tasks/invoke_hub_response.rake
spec/data_migrations/invoke_hub_response_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22234](https://devops.dchbx.org/redmine/issues/22234) |

22234: Outstanding verification due date missing

---

app/helpers/insured/group_selection_helper.rb
spec/helpers/insured/group_selection_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18207](https://devops.dchbx.org/redmine/issues/18207) |

18207: We're sorry error when trying to terminate IVL plan using plan badge

---

app/helpers/verification_helper.rb
app/models/family.rb
features/insured/individual_verification.feature
features/step_definitions/integration_steps.rb
features/step_definitions/verification_process_steps.rb
lib/documents_verification_status.rb
spec/helpers/verification_helper_spec.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21368](https://devops.dchbx.org/redmine/issues/21368) |

21368: Change text in UI from Curam to External Source

---

app/data_migrations/change_date_of_hire.rb
lib/tasks/change_date_of_hire.rake
spec/data_migrations/change_date_of_hire_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23712](https://devops.dchbx.org/redmine/issues/23712) |

23712: Investigate - Employees receiving error message when attempting to enroll in 5/1 coverage

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23359](https://devops.dchbx.org/redmine/issues/23359) |

23359: Fully verified customer in enrolled_contingent

---

app/controllers/employers/broker_agency_controller.rb
app/controllers/exchanges/broker_applicants_controller.rb
app/helpers/exchanges/broker_applicants_helper.rb
app/views/employers/broker_agency/_broker_agencies_listing.html.erb
app/views/exchanges/broker_applicants/index.js.erb
app/views/shared/brokers/_applicants.html.erb
spec/controllers/employers/broker_agency_controller_spec.rb
spec/helpers/exchanges/broker_applicants_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21968](https://devops.dchbx.org/redmine/issues/21968) |
| Peer Review Story Points | 2 |

21968: Brokers page and Browse Broker function in ER accounts in preprod not loading

---

app/data_migrations/update_curam_user_records.rb
lib/tasks/update_curam_user_records.rake
spec/data_migrations/update_curam_user_records_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22510](https://devops.dchbx.org/redmine/issues/22510) |

22510: User blocked from claiming account - Username already in exists 

---

app/data_migrations/change_broker_assignment_date.rb
lib/tasks/change_broker_assignment_date.rake
spec/data_migrations/change_broker_assignment_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23114](https://devops.dchbx.org/redmine/issues/23114) |
| Ticket Author | Luis Vasquez |

23114: Retroactive Assignment of Broker to IVL Member's Account

---

app/invoices/employer_invoice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16390](https://devops.dchbx.org/redmine/issues/16390) |

16390: Remove invoice available message for initial invoice

---

app/models/consumer_role.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22473](https://devops.dchbx.org/redmine/issues/22473) |

22473: Admin receives "The change you wanted was rejected" when attempting to access person on families index

---

app/controllers/employers/employer_profiles_controller.rb
spec/controllers/employers/employer_profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19929](https://devops.dchbx.org/redmine/issues/19929) |

19929: Former broker has access to terminated employees account

---

components/benefit_sponsors/app/controllers/benefit_sponsors/inboxes/messages_controller.rb
components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller.rb
components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
components/benefit_sponsors/app/helpers/benefit_sponsors/application_helper.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/message_service.rb
components/benefit_sponsors/app/views/benefit_sponsors/inboxes/messages/destroy.js.erb
components/benefit_sponsors/app/views/benefit_sponsors/inboxes/messages/show.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/inboxes/messages/show.js.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/inbox.js.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/messages.js.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_primary_nav.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/inbox.js.erb
components/benefit_sponsors/app/views/benefit_sponsors/shared/inboxes/_individual_message.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/shared/inboxes/_message.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/shared/inboxes/_message_list.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/shared/inboxes/_messages_list.html.erb
components/benefit_sponsors/config/routes.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23226](https://devops.dchbx.org/redmine/issues/23226) |
| Ticket Author | Angus Irvine |

23226: InboxesController

---

app/models/financial_assistance/applicant.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24177](https://devops.dchbx.org/redmine/issues/24177) |
| Ticket Author | Joshua Karper |

24177:  "Is living in State"  attribute should be defaulted to false

---

app/helpers/exchanges/hbx_profiles_helper.rb
app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24180](https://devops.dchbx.org/redmine/issues/24180) |
| Ticket Author | @harshared |

24180: CoverAll DC Part 2 - Update person roles in UI According to family Transition changes

---

app/controllers/general_agencies/profiles_controller.rb
app/models/forms/general_agency_profile.rb
app/views/general_agencies/profiles/_show.html.erb
app/views/general_agencies/profiles/edit.html.erb
features/general_agencies/step_definitions/ga_steps.rb
features/general_agencies/update_general_agency_profile.feature
spec/controllers/general_agencies/profiles_controller_spec.rb
spec/models/forms/general_agency_profile_spec.rb
spec/views/general_agencies/_show.html.erb_spec.rb
spec/views/general_agencies/edit.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22532](https://devops.dchbx.org/redmine/issues/22532) |
| Ticket Author | Andre Dixon |

22532: Add Edit Functionality to the General Agency UI 

---

app/models/plan_year.rb
app/models/subscribers/employee_enrollment_invitations_subscriber.rb
app/models/subscribers/employee_initial_enrollment_invitations_subscriber.rb
app/models/subscribers/employee_renewal_invitations_subscriber.rb
app/models/user.rb
config/application.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24305](https://devops.dchbx.org/redmine/issues/24305) |
| Ticket Author | Lokesh Reddy |

24305: Sending Invitations to renewal employees, initial employees and active employees

---

lib/tasks/migrations/updating_person_ssn.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23945](https://devops.dchbx.org/redmine/issues/23945) |
| Ticket Author | Catherine Ramirez |

23945: SSN Removal/Change 

---

app/views/events/individuals/_person.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24357](https://devops.dchbx.org/redmine/issues/24357) |

24357: Refactor HAML file 

---

app/controllers/insured/families_controller.rb
app/helpers/verification_helper.rb
app/models/family.rb
app/models/rule_set/coverage_household/individual_market_verification.rb
app/models/rule_set/hbx_enrollment/individual_market_verification.rb
spec/helpers/verification_helper_spec.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24330](https://devops.dchbx.org/redmine/issues/24330) |

24330: Active Consumer in Verified Status enrolls in a Cover All Enrollment 

---

components/benefit_sponsors/app/models/benefit_sponsors/organizations/issuer_profile.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_organizations_exempt_organizations.rb
db/migrate/20180503145357_carrier_profiles_migration.rb
spec/migrations/carrier_profiles_migration_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23860](https://devops.dchbx.org/redmine/issues/23860) |
| Ticket Author | Angus Irvine |

23860: carrier_profile -> profile

---

app/assets/javascripts/financial_assistance/deduction.js
app/views/financial_assistance/deductions/index.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23443](https://devops.dchbx.org/redmine/issues/23443) |

23443: Wrong adjustment type in error message

---

app/models/plan_year.rb
config/settings.yml
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19935](https://devops.dchbx.org/redmine/issues/19935) |

19935: Transition 12/1 groups to Renewing_enrolled

---

app/controllers/insured/plan_shoppings_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24112](https://devops.dchbx.org/redmine/issues/24112) |

24112: 500 Error before Plan Shopping

---

app/data_migrations/remove_consumer_role.rb
lib/tasks/migrations/remove_consumer_role.rake
spec/data_migrations/remove_consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24675](https://devops.dchbx.org/redmine/issues/24675) |

24675: Disassociate Consumer Role with Person Record

---

app/data_migrations/add_coverage_household_member.rb
app/models/special_enrollment_period.rb
lib/tasks/migrations/add_coverage_household_member.rake
spec/data_migrations/add_coverage_household_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24327](https://devops.dchbx.org/redmine/issues/24327) |

24327: Dependent not coming up during plan shopping

---

app/helpers/verification_helper.rb
app/views/insured/families/_navigation.html.erb
spec/models/tax_household_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24363](https://devops.dchbx.org/redmine/issues/24363) |

24363: "Upload Paper Application" option should only be available for families with at least 1 active resident

---

app/controllers/exchanges/broker_applicants_controller.rb
app/models/broker_role.rb
app/views/shared/brokers/_applicant.html.erb
spec/controllers/exchanges/broker_applicants_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24064](https://devops.dchbx.org/redmine/issues/24064) |

24064: Make checkboxes editable for broker accounts

---

app/data_migrations/updating_broker_agency_account_or_profile.rb
lib/tasks/migrations/updating_broker_agency_account_or_profile.rake
spec/data_migrations/updating_broker_agency_account_or_profile_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24009](https://devops.dchbx.org/redmine/issues/24009) |
| Ticket Author | Andre Dixon |

24009: Individual blocked from adding a broker to their account

---

app/models/forms/family_member.rb
app/views/insured/family_members/_dependent_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21990](https://devops.dchbx.org/redmine/issues/21990) |
| Ticket Author | @rabbittracey |

21990: FAA information format inconsistency between primary applicant and family members

---

features/financial_assistance/income_adjustments_page.feature
features/financial_assistance/step_definitions/income_adjustments_page_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21522](https://devops.dchbx.org/redmine/issues/21522) |

21522: FAA Cucumber:  Income Adjustments (deductions)

---

app/views/events/financial_assistance/_deduction.xml.haml
lib/schemas/individual.xsd

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23450](https://devops.dchbx.org/redmine/issues/23450) |

23450: Adjustments in FAA resulting in application submission failures

---

app/data_migrations/fix_plan_year.rb
spec/data_migrations/fix_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24787](https://devops.dchbx.org/redmine/issues/24787) |
| Ticket Author | Stephen  Bowden |

24787: Transmit Late Initial Group - Embassy of the Union of Myanmar

---

app/assets/javascripts/financial_assistance/income.js
app/views/financial_assistance/incomes/_self_employed_income_form.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23146](https://devops.dchbx.org/redmine/issues/23146) |

23146: Save on income instance enabled when frequency not selected

---

app/views/notices/ivl/enrollment_notice.html.erb
app/views/notices/ivl/final_eligibility_notice_aqhp.html.erb
app/views/notices/ivl/final_eligibility_notice_uqhp.html.erb
app/views/notices/ivl/final_eligibility_notice_uqhp_aqhp.html.erb
app/views/notices/ivl/projected_eligibility_notice.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21094](https://devops.dchbx.org/redmine/issues/21094) |

21094: Spacing in signature line in IVL market

---

app/views/notices/ivl/projected_eligibility_notice.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19000](https://devops.dchbx.org/redmine/issues/19000) |

19000: Updates to IVL_PRE Notice- Projected Eligibility

---

lib/tasks/verification_reports/verified_verification_reports.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23992](https://devops.dchbx.org/redmine/issues/23992) |
| Start Date | 04/19/2018 |
| Due Date | 04/20/2018  |

23992: Enrollment ID Extension

---

components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
db/migrate/20180517172333_cca_broker_agency_accounts_migration.rb
spec/migrations/cca_broker_agency_accounts_migration_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24048](https://devops.dchbx.org/redmine/issues/24048) |

24048: Accounts Migration

---

app/helpers/application_helper.rb
app/models/effective/datatables/family_data_table.rb
app/views/exchanges/hbx_profiles/_family_index_datatable.html.erb
config/cucumber.yml
config/settings.yml
features/cover_all/consumer_requests_enrollment.feature
features/cover_all/transition_family_member.feature
features/step_definitions/cover_all_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25077](https://devops.dchbx.org/redmine/issues/25077) |

25077: Disable Cover All functionality while Cover All Notices are being developed

---

spec/controllers/employers/employer_profiles_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

spec fix master

---

lib/tasks/verification_reports/outstanding_verifications_created.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21123](https://devops.dchbx.org/redmine/issues/21123) |

21123: Monthly report of outstanding verifications

---

app/data_migrations/remove_coverage_household_member.rb
lib/tasks/migrations/adding_employee_role.rake
lib/tasks/migrations/remove_coverage_household_member.rake
spec/data_migrations/remove_coverage_household_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24416](https://devops.dchbx.org/redmine/issues/24416) |

24416: EE Not Linked to Roster - 19892737

---

app/models/consumer_role.rb
app/reports/outstanding_types_report.rb
lib/tasks/outstanding_types_report.rake
spec/models/consumer_role_spec.rb
spec/reports/outstanding_types_report_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24502](https://devops.dchbx.org/redmine/issues/24502) |

24502: Point-in-time outstanding verifications report

---

app/views/notices/ivl/documents_verification_reminder.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21097](https://devops.dchbx.org/redmine/issues/21097) |

21097: Spacing in signature line in Reminder Notices

---

app/models/queries/named_enrollment_queries.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
script/force_publish_benefit_applications.rb
script/policies_for_employer_ies.rb
script/policies_for_employer_renewals.rb
script/policies_for_simulated_renewals.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25579](https://devops.dchbx.org/redmine/issues/25579) |
| Ticket Author | Saadi Mirza |

25579: Update scripts for NFP Provisional Passive renewals to accommodate new model changes

---

app/models/hbx_profile.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21157](https://devops.dchbx.org/redmine/issues/21157) |

21157: Extend 2/1 OE plan shopping deadline through 1/17 (individual market)

---

app/notices/pdf_templates/enrollment.rb
app/notices/shop_employee_notices/open_enrollment_notice_for_auto_renewal.rb
app/views/notices/shop_employee_notices/8a_renewal_open_enrollment_notice_for_employee.html.erb
spec/notices/shop_employee_notices/open_enrollment_notice_for_auto_renewal_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24238](https://devops.dchbx.org/redmine/issues/24238) |

24238: Enrolled employees not receiving "Your Health Plan Open Enrollment Period has Begun" notice for renewal 

---

app/data_migrations/change_census_employee_details.rb
lib/tasks/change_census_employee_details.rake
spec/data_migrations/change_census_employee_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23706](https://devops.dchbx.org/redmine/issues/23706) |

23706: Investigate - EE showing as not linked when linked

---

app/data_migrations/update_curam_user_records.rb
lib/tasks/update_curam_user_records.rake
spec/data_migrations/update_curam_user_records_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23469](https://devops.dchbx.org/redmine/issues/23469) |
| Ticket Author | Raymond Lam |

23469: Person is blocked from claiming user 

---

lib/tasks/hbx_reports/brokers_with_URL_from_admin_approval.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25964](https://devops.dchbx.org/redmine/issues/25964) |

25964: Refactor - Broker Magic URL Report

---

lib/tasks/hbx_reports/employer_poc_pending_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25966](https://devops.dchbx.org/redmine/issues/25966) |

25966: Refactor POC Pending Report

---

app/data_migrations/update_waiver_reason.rb
lib/tasks/migrations/update_waiver_reason.rake
spec/data_migrations/update_waiver_reason_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22266](https://devops.dchbx.org/redmine/issues/22266) |

22266: Display Issue - 'Reason Waived' selection requested to be changed

---

app/controllers/insured/families_controller.rb
app/jobs/ivl_notices_notifier_job.rb
app/models/consumer_role.rb
app/notices/ivl_notices/ivl_to_coverall_transition_notice_builder.rb
app/notices/pdf_templates/conditional_eligibility_notice.rb
app/notices/pdf_templates/individual.rb
app/views/insured/families/_transition_family_members_form.html.erb
app/views/notices/ivl/documents_section.html.erb
app/views/notices/ivl/ivl_to_coverall_notice.html.erb
app/views/notices/shared/_household_member_details.html.erb
db/seedfiles/notice_triggers_seed.rb
spec/models/consumer_role_spec.rb
spec/notices/ivl_notices/ivl_to_coverall_transition_notice_builder_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23076](https://devops.dchbx.org/redmine/issues/23076) |
| Due Date | 04/30/2018  |

23076: IVL Transition from IVL to CADC Notice IVL_CDC

---

app/data_migrations/creating_person_record.rb
lib/tasks/migrations/creating_person_record.rake
spec/data_migrations/creating_person_record_spec.rb
spec/test_data/person_test_record.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22075](https://devops.dchbx.org/redmine/issues/22075) |
| Ticket Author | Kionna Spann |

22075: Need user record in EA established with the HIX ID that already exists in Glue

---

app/helpers/verification_helper.rb
features/step_definitions/verification_process_steps.rb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27376](https://devops.dchbx.org/redmine/issues/27376) |

27376: Documents with due dates in review status should show this due date for the family

---

app/models/consumer_role.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27289](https://devops.dchbx.org/redmine/issues/27289) |

27289: Residency verification placed in processing status when SSA hub re-pinged for child

---

app/models/subscribers/local_residency.rb
spec/models/subscribers/local_residency_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26340](https://devops.dchbx.org/redmine/issues/26340) |

26340: "View History" is not displaying mock response for DC Residency.

---

app/models/importers/transcripts/enrollment_transcript.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27307](https://devops.dchbx.org/redmine/issues/27307) |
| Ticket Author | Stephen  Bowden |

27307: Employer/Employee Unable to View Employee Census Details from Roster (Reverse Data Migration from Glue Needed)- Embassy of the Union of Myanmar

---

app/models/family.rb
app/models/subscribers/family_application_completed.rb
app/models/verification_type.rb
app/views/insured/families/verification/_verification.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27253](https://devops.dchbx.org/redmine/issues/27253) |

27253: Case with no docs in review showing as "fully uploaded"

---

app/views/events/v2/employers/_benefit_group.xml.haml
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16597](https://devops.dchbx.org/redmine/issues/16597) |
| Ticket Author | Sheheryar Tariq |

16597: Update V2 Generation Schema to Include Benefit_group ID field

---

app/notices/ivl_notices/ivl_to_coverall_transition_notice_builder.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26028](https://devops.dchbx.org/redmine/issues/26028) |

26028: Refactor IVL_CDC and IVL_DCH to consider Verifications Refactor

---

app/data_migrations/create_renewal_plan_year_and_enrollment.rb
spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27963](https://devops.dchbx.org/redmine/issues/27963) |

27963: Auto-renewal Issue for EEs of Renewal Groups with >20 EEs on Roster

---

app/models/plan_year.rb
app/models/subscribers/employee_passive_renewals_subscriber.rb
config/application.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28830](https://devops.dchbx.org/redmine/issues/28830) |

28830: Modify Active Renewal Job

---

app/models/family.rb
app/models/hbx_id_generator.rb
app/models/payment_transaction.rb
spec/models/family_spec.rb
spec/models/hbx_id_generator_spec.rb
spec/models/payment_transaction_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25400](https://devops.dchbx.org/redmine/issues/25400) |

25400: Pay Now Kaiser-Store Transaction ID in EA DB

---

spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb
spec/data_migrations/triggering_auto_renewals_for_specific_employer_spec.rb
spec/data_migrations/triggering_auto_renewals_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29091](https://devops.dchbx.org/redmine/issues/29091) |
| Ticket Author | Lokesh Reddy |

29091: SPEC failure for, Bug #28830

---

app/controllers/insured/families_controller.rb
app/models/hbx_enrollment.rb
app/views/insured/families/_shop_for_plans_widget.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28197](https://devops.dchbx.org/redmine/issues/28197) |
| Ticket Author | Imani Williams |

28197: EE is Unable to Enroll in Renewal Coverage 

---

app/views/broker_agencies/profiles/_menu.html.erb
spec/views/broker_agencies/profiles/_menu.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25677](https://devops.dchbx.org/redmine/issues/25677) |

25677: Please hide the First Time Applications for Medicaid and Premium Tax Credits tab in the HBX EA prod Broker Agency menu

---

lib/tasks/verification_reports/outstanding_verifications_created.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27310](https://devops.dchbx.org/redmine/issues/27310) |

27310: Refactor Monthly report outstanding verifications 

---

app/views/financial_assistance/benefits/_esi_benefit_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21289](https://devops.dchbx.org/redmine/issues/21289) |

21289: Not able to continue with single instance of ESI

---

app/data_migrations/update_family_members_index.rb
lib/tasks/migrations/update_family_members_index.rake
spec/data_migrations/update_family_members_index_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28143](https://devops.dchbx.org/redmine/issues/28143) |

28143: Unable to submit enrollment - HIX ID 19922672

---

app/controllers/insured/families_controller.rb
app/models/hbx_enrollment.rb
app/views/insured/families/_shop_for_plans_widget.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29789](https://devops.dchbx.org/redmine/issues/29789) |

29789: SEP effective date rules not working

---

app/data_migrations/adding_dependents.rb
app/data_migrations/update_hbx_enrollment_benefit_group_assignment.rb
dependents.csv
lib/tasks/migrations/adding_dependents.rake
lib/tasks/migrations/update_hbx_enrollment_benefit_group_assignment.rake
spec/data_migrations/adding_dependents_spec.rb
spec/data_migrations/update_hbx_enrollment_benefit_group_assignment_spec.rb
spec/test_data/dependent_test_record.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27965](https://devops.dchbx.org/redmine/issues/27965) |
| Ticket Author | Kionna Spann |

27965: Employer/Employee Unable to View Employee Census Details from Roster (Reverse Data Migration from Glue Needed)- Embassy Of Suriname

---

app/data_migrations/reinstate_plan_year.rb
spec/data_migrations/reinstate_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30045](https://devops.dchbx.org/redmine/issues/30045) |
| Ticket Author | Stephen  Bowden |

30045: (Medical Need) Reinstatement after termination for Non-payment- DupontStudios

---

app/controllers/insured/plan_shoppings_controller.rb
app/models/family.rb
app/models/hbx_enrollment.rb
app/models/plan.rb
spec/controllers/insured/plan_shoppings_controller_spec.rb
spec/models/family_spec.rb
spec/models/hbx_enrollment_spec.rb
spec/models/plan_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29048](https://devops.dchbx.org/redmine/issues/29048) |

29048: CSR variant changes after using the enroll APTC tool is recalculating premiums

---

app/notices/ivl_notices/second_ivl_renewal_notice.rb
app/views/notices/ivl/projected_eligibility_notice.html.erb
script/projected_eligibility_notice_2.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30688](https://devops.dchbx.org/redmine/issues/30688) |

30688: IVL_PRE 2018 AQHP run

---

app/data_migrations/adding_dependents.rb
app/notices/ivl_notices/second_ivl_renewal_notice.rb
db/seedfiles/english_translations_seed.rb
script/projected_eligibility_notice_2.rb
spec/notices/ivl_notices/second_ivl_renewal_notice_spec.rb
spec/test_data/notices/second_ivl_renewal_notice_test_data.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30768](https://devops.dchbx.org/redmine/issues/30768) |

30768: AQHP IVL_PRE run- family with IC 4252569 didn't receive notice

---

app/models/benefit_group_assignment.rb
app/models/eligibility/employee_benefit_packages.rb
spec/models/benefit_group_assignment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25559](https://devops.dchbx.org/redmine/issues/25559) |

25559: Invalid Benefit Group - Embassy Of Equatorial Guinea

---

app/controllers/insured/group_selection_controller.rb
app/models/census_employee.rb
app/models/hbx_enrollment.rb
spec/models/census_employee_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [28930](https://devops.dchbx.org/redmine/issues/28930) |

28930: Admin receives error message when processing new EE COBRA enrollment

---

script/ivl_sep_query.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21777](https://devops.dchbx.org/redmine/issues/21777) |

21777: Res Party Enrollment won't flow from EA to Glue

---

app/models/hbx_enrollment.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22967](https://devops.dchbx.org/redmine/issues/22967) |

22967: EA not applying a silent end date on enrollment tiles for dep drops

---

app/data_migrations/remove_dependent.rb
spec/data_migrations/remove_dependent_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24777](https://devops.dchbx.org/redmine/issues/24777) |
| Ticket Author | Grizelda Mejia |

24777: Duplicate Family Members

---

app/models/factories/employer_open_enrollment_factory.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30827](https://devops.dchbx.org/redmine/issues/30827) |

30827: Large employers time-out during the renewal process in DC

---

app/controllers/concerns/vlp_doc.rb
app/controllers/insured/family_members_controller.rb
app/controllers/people_controller.rb
app/models/consumer_role.rb
spec/controllers/concerns/vlp_doc_spec.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27644](https://devops.dchbx.org/redmine/issues/27644) |

27644: Need to reping hub when citizenship in verified state is updated to no citizenship with eligible immigration status

---

app/views/insured/family_members/_dependent_form.html.erb
app/views/insured/family_members/new.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [6779](https://devops.dchbx.org/redmine/issues/6779) |
| Start Date | 04/18/2016 |

6779: Immigration document type information entered gets deleted if there's an error on the page

---

app/data_migrations/fix_plan_year.rb
spec/data_migrations/fix_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30638](https://devops.dchbx.org/redmine/issues/30638) |

30638: Supplement to Ticket #30152

---

script/force_publish_plan_years.rb
script/policies_for_employer_ies.rb
script/policies_for_employer_renewals.rb
script/policies_for_simulated_renewals.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27045](https://devops.dchbx.org/redmine/issues/27045) |
| Ticket Author | Sheheryar Tariq |

27045: Streamline and Automate NFP Passive Renewal Process 

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/models/consumer_role.rb
spec/controllers/exchanges/hbx_profiles_controller_spec.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [32899](https://devops.dchbx.org/redmine/issues/32899) |

32899: Cover All- Local Residency is being set to "Unverified" state during first time resident to IVL transition

---

app/views/users/_email_form.html.erb
app/views/users/_username_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29682](https://devops.dchbx.org/redmine/issues/29682) |

29682: Admin Ability to Update Username/Email-When Admin submits a username/email update, popup will appear to ensure Admin would like the change

---

app/views/users/_email_form.html.erb
app/views/users/_username_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29679](https://devops.dchbx.org/redmine/issues/29679) |

29679: Admin Ability to Update Username/Email-The current credentials of a user will be auto populated in the “Edit User Credentials” table

---

app/data_migrations/define_permissions.rb
app/models/permission.rb
app/policies/hbx_profile_policy.rb
app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
lib/tasks/define_permissions.rake
spec/data_migrations/permissions_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29674](https://devops.dchbx.org/redmine/issues/29674) |

29674: Admin Ability to Update Username/Email- Admin Permissions

---

app/controllers/application_controller.rb
app/controllers/insured/interactive_identity_verifications_controller.rb
features/insured/individual_ridp_verification.feature
spec/controllers/insured/interactive_identity_verifications_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [31565](https://devops.dchbx.org/redmine/issues/31565) |

31565: RIDP- Update Landing page so that ID Verified=My Account page bookmark

---

lib/tasks/migrations/updating_person_ssn.rake

Hi Kevin, updated the duplicate SSN on the rake. Can you please merge this commit.

refs #updating ssn rake

---

app/models/consumer_role.rb
app/models/hbx_enrollment.rb
script/ivl_sep_query.rb
spec/models/consumer_role_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [25820](https://devops.dchbx.org/redmine/issues/25820) |

25820: ENR notice not sent when dependent without SSN added

---

app/controllers/insured/group_selection_controller.rb
app/models/consumer_role.rb
app/models/hbx_enrollment.rb
script/ivl_sep_query.rb
spec/models/consumer_role_spec.rb
spec/models/hbx_enrollment_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Merge fix 23778

---

app/data_migrations/update_census_employee_id.rb
lib/tasks/update_census_employee_id.rake
spec/data_migrations/app/update_census_employee_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [31338](https://devops.dchbx.org/redmine/issues/31338) |
| Due Date | 10/10/2018  |

31338: Unable to Link EE to Roster - General Services, Inc.

---

lib/tasks/download_ridp_documents.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [27548](https://devops.dchbx.org/redmine/issues/27548) |
| Due Date | 08/17/2018  |

27548: RIDP- Admin Ability to View Application and Identity Documents After Consumer is Verified- Rake Task Creation

---

app/helpers/insured/families_helper.rb
app/models/hbx_enrollment.rb
app/notices/ivl_notices/final_eligibility_notice_renewal_aqhp.rb
app/notices/ivl_notices/reminder_notice.rb
script/final_eligibility_notice_report_unassisted.rb
script/set_verification_due_date_on_family.rb
spec/data_migrations/remove_enrolled_contingent_state_spec.rb
spec/models/hbx_enrollment_spec.rb
spec/views/insured/families/_enrollment.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [33618](https://devops.dchbx.org/redmine/issues/33618) |

33618: Enrolled Contingent Renewals-Refactor listener and renewal script to update the new field

---

app/models/family_member.rb
app/models/hbx_enrollment.rb
app/models/tax_household.rb
app/models/unassisted_plan_cost_decorator.rb
spec/models/family_member_spec.rb
spec/models/tax_household_spec.rb
spec/models/unassisted_plan_cost_decorator_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23578](https://devops.dchbx.org/redmine/issues/23578) |

23578: Allocation of APTC based on Bench mark value

---

app/data_migrations/remove_resident_role_for_dual_role_case.rb
app/models/individual_market_transition.rb
lib/tasks/migrations/remove_resident_role_for_dual_role_case.rake
spec/data_migrations/remove_resident_role_for_dual_role_case_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36415](https://devops.dchbx.org/redmine/issues/36415) |

36415: Shop EE receives Coverall DC Marketplace

---

app/data_migrations/make_benefit_group_assignment_active.rb
app/data_migrations/unset_benefit_group_assignment.rb
lib/tasks/verification_reports/unset_benefit_group_assignment.rake
spec/data_migrations/app/unset_benefit_group_assignment_spec.rb
spec/data_migrations/make_benefit_group_assignment_active_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [31003](https://devops.dchbx.org/redmine/issues/31003) |

31003: Employee unable to enroll in coverage

---

app/data_migrations/update_special_enrollment_period.rb
app/models/special_enrollment_period.rb
lib/tasks/update_special_enrollment_period.rake
spec/data_migrations/update_special_enrollment_period_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36517](https://devops.dchbx.org/redmine/issues/36517) |

36517: EE receives error message when trying to enroll

---

app/data_migrations/reset_due_dates_for_outstanding_consumers.rb
app/models/family.rb
app/models/hbx_enrollment.rb
lib/tasks/migrations/reset_due_dates_for_outstanding_consumers.rake
script/ivl_renewal_notices.rb
spec/data_migrations/reset_due_dates_for_outstanding_consumers_spec.rb
spec/factories/hbx_enrollment_member.rb
spec/models/family_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36711](https://devops.dchbx.org/redmine/issues/36711) |

36711: Follow up to ticket 31270 - Create a rake task to reset the due dates of the families who were affected by 25820 

---

app/helpers/insured/plan_shopping/receipt_helper.rb
spec/helpers/insured/plan_shopping/receipt_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [33198](https://devops.dchbx.org/redmine/issues/33198) |

33198: Pay Now Kaiser- Hide Pay Now UI until Kaiser has finished their development

---

app/data_migrations/build_ivl_market_transition_for_missing_consumer.rb
lib/tasks/migrations/build_ivl_market_transition_for_missing_consumer.rake
spec/data_migrations/build_ivl_market_transition_for_missing_consumer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36489](https://devops.dchbx.org/redmine/issues/36489) |
| Ticket Author | Cudjoe . |

36489: Unable to plan shop with SEP: HBX - 19963027

---

app/models/subscribers/legacy_notification_subscriber.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Add census employee routing key to LegacyNotificationSubscriber.

---

features/support/worlds/ivl_assistance_world.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37344](https://devops.dchbx.org/redmine/issues/37344) |
| Ticket Author | @harshared |

37344: Failing Cucumbers in master

---

app/models/services/checkbook_services.rb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37394](https://devops.dchbx.org/redmine/issues/37394) |

37394: Update production path for Plan Match API

---

app/models/employer_profile.rb
spec/models/employer_profile_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29856](https://devops.dchbx.org/redmine/issues/29856) |

29856: Plan Year display issue

---

app/models/subscribers/family_application_completed.rb
spec/models/subscribers/family_application_completed_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21766](https://devops.dchbx.org/redmine/issues/21766) |

21766: IC failure "failed to match to broker with NPN"

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37139](https://devops.dchbx.org/redmine/issues/37139) |

37139: MEDICAL NEED: Employee Cannot Access Account due to Error Msg

---

script/er_poc_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [29207](https://devops.dchbx.org/redmine/issues/29207) |
| Ticket Author | Stephen Haines |

29207: All POC Staff for SHOP Employers

---

db/seedfiles/plans-sbcs.csv
plans-sbcs.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37311](https://devops.dchbx.org/redmine/issues/37311) |

37311: Error loading 2019 dental plan document

---

app/models/services/checkbook_services.rb
spec/models/services/checkbook_services_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37410](https://devops.dchbx.org/redmine/issues/37410) |

37410:  EE Plan Shopping Errors 

---

app/data_migrations/upload_notice_to_employee_account.rb
lib/tasks/upload_notice_to_employee_account.rake
lib/tasks/upload_notice_to_employees.rake
spec/data_migrations/upload_notice_to_employee_account_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37404](https://devops.dchbx.org/redmine/issues/37404) |

37404: DC SHOP Notice: Upload attached notice to EE secure message inbox [DRG010]

---

app/models/family.rb
app/notices/ivl_notices/final_eligibility_notice_aqhp.rb
app/notices/ivl_notices/final_eligibility_notice_renewal_aqhp.rb
app/notices/ivl_notices/final_eligibility_notice_renewal_uqhp.rb
app/notices/ivl_notices/final_eligibility_notice_uqhp.rb
app/notices/ivl_notices/ivl_renewal_notice.rb
app/views/notices/ivl/eligibility_notice.html.erb
app/views/notices/ivl/enrollment_notice.html.erb
app/views/notices/ivl/final_eligibility_notice_aqhp.html.erb
app/views/notices/ivl/final_eligibility_notice_uqhp.html.erb
app/views/notices/ivl/final_eligibility_notice_uqhp_aqhp.html.erb
app/views/notices/ivl/ineligibility_notice.html.erb
app/views/notices/ivl/ivl_backlog_verification_notice_uqhp.html.erb
script/ivl_renewal_notices.rb
script/projected_eligibility_notice_1.rb
spec/models/admin/aptc_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_aqhp_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_renewal_aqhp_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_renewal_uqhp_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_uqhp_spec.rb
spec/notices/ivl_notices/ivl_renewal_notice_spec.rb
spec/notices/ivl_notices/second_ivl_renewal_notice_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21355](https://devops.dchbx.org/redmine/issues/21355) |

21355: No renewal notices generated for responsible party enrollment

---

app/models/insured_eligible_for_benefit_rule.rb
spec/models/insured_eligible_for_benefit_rule_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21418](https://devops.dchbx.org/redmine/issues/21418) |

21418: Eligibility engine accepts 'nil' value for 'Incarcerated' question for accounts impacted by previous UI bug

---

app/models/factories/family_enrollment_renewal_factory.rb
spec/models/factories/family_enrollment_renewal_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36785](https://devops.dchbx.org/redmine/issues/36785) |

36785: Congressional Open Enrollment - Set the Open Enrollment Period Dates

---

app/data_migrations/build_ivl_market_transition_for_missing_consumer.rb
lib/tasks/migrations/build_ivl_market_transition_for_missing_consumer.rake
spec/data_migrations/build_ivl_market_transition_for_missing_consumer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37217](https://devops.dchbx.org/redmine/issues/37217) |
| Ticket Author | Cudjoe . |

37217: Unable to plan shop with SEP: HBX - 19903865

---

app/models/services/checkbook_services.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37524](https://devops.dchbx.org/redmine/issues/37524) |
| Ticket Author | Robert Hooker |

37524: API Plan Match (Age When Coverage Begins)

---

app/data_migrations/change_census_employee_details.rb
app/models/forms/bulk_actions_for_admin.rb
app/models/person.rb
lib/tasks/change_census_employee_details.rake
spec/controllers/insured/families_controller_spec.rb
spec/data_migrations/change_census_employee_details_spec.rb
spec/models/forms/bulk_actions_for_admin_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37095](https://devops.dchbx.org/redmine/issues/37095) |
| Ticket Author | Raymond Lam |

37095: MEDICAL NEED: Employee receiving Error Message: "We're sorry, but something went wrong."

---

app/notices/ivl_notices/final_eligibility_notice_aqhp.rb
app/notices/pdf_templates/individual.rb
app/views/notices/ivl/final_eligibility_notice_aqhp.html.erb
script/ivl_renewal_notices.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37454](https://devops.dchbx.org/redmine/issues/37454) |

37454: 2019 IVL_FEL Final Eligibility Notice- AQHP

---

app/helpers/verification_helper.rb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [36890](https://devops.dchbx.org/redmine/issues/36890) |
| Ticket Author | @krbhavith |

36890: Demographics info not displaying for dependent when Person has Dual Role

---

app/data_migrations/update_family_member_details.rb
lib/tasks/migrations/update_family_member_details.rake
spec/data_migrations/update_family_member_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37860](https://devops.dchbx.org/redmine/issues/37860) |
| Ticket Author | Jason Sparks |

37860: Senate Employee Unable to Add Spouse

---

app/data_migrations/change_gender.rb
lib/tasks/migrations/change_gender.rake
spec/data_migrations/change_gender_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [37550](https://devops.dchbx.org/redmine/issues/37550) |

37550: Error message appears in Employees account - "We're sorry, but something went wrong."

---

app/helpers/employers/employer_helper.rb
app/models/forms/bulk_actions_for_admin.rb
spec/helpers/employers/employer_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30890](https://devops.dchbx.org/redmine/issues/30890) |

30890: Employee erroneously transitioned to "terminated" status when future term date submitted via Admin tool

---

spec/models/factories/plan_year_renewal_factory_spec.rb
spec/models/services/checkbook_services_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

PlanYearRenewalFactory spec fix.

---

app/helpers/insured/families_helper.rb
spec/helpers/insured/families_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24511](https://devops.dchbx.org/redmine/issues/24511) |
| Ticket Author | Raymond Lam |

24511: 500 Error - "We're sorry, but something went wrong."

---

app/data_migrations/extending_open_enrollment_end_date_for_employers.rb
lib/tasks/migrations/extending_open_enrollment_end_date_for_employers.rake
spec/data_migrations/extending_open_enrollment_end_date_for_employers_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38529](https://devops.dchbx.org/redmine/issues/38529) |

38529: Open enrollment extension for 1/1/2019 renewal groups

---

app/models/hbx_profile.rb
config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38554](https://devops.dchbx.org/redmine/issues/38554) |

38554: Extend 1/1 effective date plan shopping for IVL

---

lib/tasks/plans/plan_cross_walk.rake
spec/lib/tasks/plans/plan_cross_walk_spec.rb
spec/test_data/plan_data/cross_walk/2018/bmchp_crosswalk.xml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38458](https://devops.dchbx.org/redmine/issues/38458) |

38458: Master Ticket- Congress/Carrier update

---

app/notices/ivl_notices/final_eligibility_notice_renewal_aqhp.rb
app/notices/ivl_notices/final_eligibility_notice_renewal_uqhp.rb
app/views/notices/ivl/documents_section.html.erb
app/views/notices/ivl/final_eligibility_notice_uqhp_aqhp.html.erb
script/final_eligibility_notice_report_unassisted.rb
script/ivl_renewal_notices.rb
spec/notices/ivl_notices/final_eligibility_notice_renewal_aqhp_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38702](https://devops.dchbx.org/redmine/issues/38702) |

38702: 2019 IVL_FRE UQHP Run

---

app/data_migrations/reinstate_plan_year.rb
app/models/plan_year.rb
spec/data_migrations/reinstate_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38270](https://devops.dchbx.org/redmine/issues/38270) |

38270: Unable to reinstate employers in termination pending state

---

app/data_migrations/update_hbx_enrollment_employee_role_id.rb
lib/tasks/migrations/update_hbx_enrollment_employee_id.rake
spec/data_migrations/update_hbx_enrollment_employee_role_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38523](https://devops.dchbx.org/redmine/issues/38523) |
| Ticket Author | Azizza Brown |

38523: Gaining access to House consumer's account in EA HBX Member ID: 1728381

---

app/models/factories/plan_year_renewal_factory.rb
spec/models/factories/plan_year_renewal_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38905](https://devops.dchbx.org/redmine/issues/38905) |

38905: 3-1-2019 Renewal Draft Plan Years Not in EA

---

app/models/tax_household_member.rb
report_for_sep_updated_family.csv
spec/data_migrations/remove_enrolled_contingent_state_spec.rb
spec/data_migrations/reset_due_dates_for_outstanding_consumers_spec.rb
spec/helpers/insured/families_helper_spec.rb
spec/lib/tasks/cancel_employer_renewal_spec.rb
spec/models/employee_role_spec.rb
spec/models/employer_profile_spec.rb
spec/models/hbx_enrollment_spec.rb
spec/models/plan_year_spec.rb
spec/models/tax_household_member_spec.rb
spec/models/tax_household_spec.rb
spec/notices/ivl_notices/reminder_notice_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Fix master specs 2019

---

app/models/family.rb
app/models/queries/outstanding_verification_datatable_query.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38060](https://devops.dchbx.org/redmine/issues/38060) |

38060: Accounts with outstanding verifications and only future active plan years not showing on verifications tab

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [39214](https://devops.dchbx.org/redmine/issues/39214) |

39214: Change deadline for 2/1 shopping from 1/15 to 1/16

---

components/notifier/app/models/notifier/builders/employer_profile.rb
components/notifier/app/models/notifier/builders/plan_year.rb
components/notifier/app/models/notifier/notice_builder.rb
spec/models/model_events/low_enrollment_notice_for_employer_spec.rb

…lder
* (Required!)
* ()
* ()
```
```
*
---
---

40045:Refactor legacy notices to use NOTICE ENGINE

---

app/views/insured/interactive_identity_verifications/_outstanding_ridp_documents.html.erb

No redmine ticket
* ()
* ()
```
```
*
---
---

Added missing end to block

---

components/benefit_sponsors/app/assets/javascripts/benefit_sponsors/jq_datepicker.js

* (Required!)
* ()
* ()
```
```
*
---
---

datepicker fix

---

app/views/shared/_consumer_fields.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Refs #40781 move run-glossary class name to fix faulty JS

---

features/admin/reset_password.feature
features/employers/step_definitions/employer_attestation_steps.rb
features/permissions/reset_password_permission.feature
features/step_definitions/new_hire_steps.rb
features/step_definitions/renewal_steps.rb
features/step_definitions/reset_password_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

cucumber updates

---

components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/general_agency_profile.rb
components/benefit_sponsors/app/models/benefit_sponsors/queries/general_agency_families_query.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/broker_management_service.rb
components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_general_agency_family_data_table.rb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/general_agency_index.html.erb
components/sponsored_benefits/app/models/sponsored_benefits/services/general_agency_manager.rb
components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/general_agency_profiles_controller_spec.rb
components/sponsored_benefits/spec/dummy/app/models/benefit_sponsors/organizations/broker_agency_profile.rb
components/sponsored_benefits/spec/dummy/app/models/broker_role.rb
components/sponsored_benefits/spec/dummy/config/routes.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Ga sprint 3

---

app/helpers/verification_helper.rb
app/views/insured/families/_navigation.html.erb
app/views/ui-components/v1/navs/_families_navigation.html.slim
spec/helpers/verification_helper_spec.rb
spec/views/insured/families/_navigation.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #42405 show documents tab if family has consumer family members

---

app/javascript/controllers/signup_controller.js
app/javascript/css/forms.scss
app/views/devise/registrations/new.html.slim

https://devops.dchbx.org/redmine/issues/42271
* ()
* ()
```
```
*
---
---

Updates to registration page

---

app/controllers/invitations_controller.rb
app/helpers/portal_header_helper.rb
app/mailers/user_mailer.rb
app/models/invitation.rb
app/views/user_mailer/agent_invitation_email.html.erb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/general_agencies/general_agency_profiles/show.js.erb
features/general_agencies/create_general_agency_staff.feature
features/general_agencies/step_definitions/ga_steps.rb
features/step_definitions/ga_staff_steps.rb
features/support/worlds/general_agency_world.rb
spec/controllers/invitations_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Ga multi staff 41637

---

app/assets/javascripts/ui-components/validators.js
app/javascript/controllers/signup_controller.js
app/views/devise/registrations/new.html.slim

https://devops.dchbx.org/redmine/issues/42479
* ()
* ()
```
```
*
---
---

Optional email field displaying when should be hidden

---

app/views/ui-components/v1/cards/_benefit_groups.html.slim
components/benefit_markets/app/models/benefit_markets/benefit_sponsor_catalog.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/importers/benefit_package_importer.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/fehb_employer_profile.rb
components/benefit_sponsors/app/models/benefit_sponsors/services/sponsored_benefit_cost_estimation_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/sponsored_benefit.rb
components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_sponsored_benefit.html.erb
db/migrate/20181213164010_generate_dc_site.rb
db/migrate/20181213164339_migrate_dc_products.rb
db/migrate/20181213164549_migrate_dc_employer_profiles.rb
db/migrate/20181213164720_migrate_dc_benefit_application.rb
db/migrate/20181213164835_migrate_dc_hbx_enrollments.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc bene application migration

---

app/views/ui-components/v1/modals/_help_with_plan.html.slim

https://devops.dchbx.org/redmine/issues/42286
* ()
* ()
```
```
*
---
---

IVL - Unable to close Help Me Sign Up pop up

---

app/javascript/benefit_sponsors/controllers/office_locations_controller.js

https://devops.dchbx.org/redmine/issues/42423
* ()
* ()
```
```
*
---
---

Update Business Info: Blank Space as a Selection in Drop Down

---

app/views/layouts/_flash.html.erb

https://devops.dchbx.org/redmine/issues/42477
* ()
* ()
```
```
*
---
---

Invalid password error display issue

---

app/views/layouts/_flash.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Removed capitalize

---

components/benefit_sponsors/spec/factories/benefit_sponsors_organizations_issuer_profiles.rb
components/sponsored_benefits/spec/factories/sponsored_benefits_benefit_applications_benefit_groups.rb
components/sponsored_benefits/spec/factories/sponsored_benefits_benefit_sponsorships_benefit_sponsorships.rb
components/sponsored_benefits/spec/factories/sponsored_benefits_locations_addresses.rb
components/sponsored_benefits/spec/factories/sponsored_benefits_organizations_aca_shop_cca_employer_profiles.rb
script/policies_for_employer_ies.rb

* (Required!)
* ()
* ()
```
```
*
---
---

ref: address rubocop offenses while running rspecs

---

app/helpers/insured/families_helper.rb
app/models/hbx_enrollment.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model base congress sep fix

---

components/benefit_sponsors/app/models/benefit_sponsors/importers/benefit_package_importer.rb
components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_organization.rb
db/migrate/20181213164339_migrate_dc_products.rb
db/migrate/20181213164720_migrate_dc_benefit_application.rb
db/migrate/20181213164835_migrate_dc_hbx_enrollments.rb
db/migrate/20181213164955_migrate_dc_broker_quoting_tool.rb
db/seedfiles/dc/dc_benefit_market_catalogs_product_packages.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model base bqt

---

db/migrate/20181213164549_migrate_dc_employer_profiles.rb
db/migrate/20181213164835_migrate_dc_hbx_enrollments.rb
db/migrate/20181213164955_migrate_dc_broker_quoting_tool.rb
db/migrate/20190624201110_create_fehb_qles.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model base congress sep migration

---

app/views/layouts/_flash.html.erb

https://devops.dchbx.org/redmine/issues/42875
* ()
* ()
```
```
*
---
---

UI - success messages are displayed off screen

---

components/benefit_sponsors/Gemfile
components/benefit_sponsors/Gemfile.lock
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_director.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/employer_benefit_renewal_subscriber.rb
components/benefit_sponsors/app/validators/benefit_sponsors/base_param_validator.rb
components/benefit_sponsors/app/validators/benefit_sponsors/benefit_sponsorships/renewal_requests/parameter_validator.rb
components/benefit_sponsors/spec/dummy/config/locales/dry_validation.en.yml
components/benefit_sponsors/spec/models/benefit_sponsors/subscribers/employer_benefit_renewal_subscriber_spec.rb
components/benefit_sponsors/spec/validators/benefit_sponsors/benefit_sponsorships/renewal_requests/parameter_validator_spec.rb
config/application.rb
config/locales/dry_validation.en.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Added asynchronous processing for employer renewals

---

components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_employees.html.erb

https://devops.dchbx.org/redmine/issues/43154
* ()
* ()
```
```
*
---
---

Broker - UI issue - employee details on the Quote are wrongly aligned

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/base.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/benefit_package_employee_renewer_subscriber.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/employer_benefit_renewal_subscriber.rb
components/benefit_sponsors/app/validators/benefit_sponsors/benefit_packages/employee_renewals/domain_validator.rb
components/benefit_sponsors/app/validators/benefit_sponsors/benefit_packages/employee_renewals/parameter_validator.rb
components/benefit_sponsors/spec/dummy/config/locales/dry_validation.en.yml
components/benefit_sponsors/spec/models/benefit_sponsors/subscribers/benefit_package_employee_renewer_subscriber_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/subscribers/employer_benefit_renewal_subscriber_spec.rb
components/benefit_sponsors/spec/validators/benefit_sponsors/benefit_packages/employee_renewals/domain_validator_spec.rb
components/benefit_sponsors/spec/validators/benefit_sponsors/benefit_packages/employee_renewals/parameter_validator_spec.rb
config/application.rb
config/locales/dry_validation.en.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Added per-employee renewal listener.

---

app/views/exchanges/hbx_profiles/configuration_index.html.erb
components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/registrations_controller.rb

https://devops.dchbx.org/redmine/issues/42478
* ()
* ()
```
```
*
---
---

Small UI Updates

---

app/models/census_employee.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/aca_shop_benefit_sponsorship_service.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/base.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/benefit_package_renewal_group_assignment_subscriber.rb
components/benefit_sponsors/app/models/benefit_sponsors/subscribers/employer_benefit_renewal_subscriber.rb
components/benefit_sponsors/app/validators/benefit_sponsors/benefit_packages/renewal_group_assignments/domain_validator.rb
components/benefit_sponsors/app/validators/benefit_sponsors/benefit_packages/renewal_group_assignments/parameter_validator.rb
components/benefit_sponsors/spec/dummy/app/models/census_employee.rb
components/benefit_sponsors/spec/models/benefit_sponsors/subscribers/benefit_package_renewal_group_assignment_subscriber_spec.rb
components/benefit_sponsors/spec/validators/benefit_sponsors/benefit_packages/renewal_group_assignments/domain_validator_spec.rb
components/benefit_sponsors/spec/validators/benefit_sponsors/benefit_packages/renewal_group_assignments/parameter_validator_spec.rb
config/application.rb
spec/data_migrations/notify_renewal_employees_dental_carriers_exiting_shop_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model fix bogus predicate

---

app/models/bill_file.rb
app/models/current_statement_activity.rb
app/models/employer_profile_account.rb
app/models/hbx_enrollment.rb
app/models/organization.rb
app/models/plan_year.rb
app/models/premium_payment.rb
components/benefit_markets/app/models/benefit_markets/configurations/aca_shop_configuration.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/app/models/benefit_sponsors/coverage_age_calculator.rb
components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_organization.rb
db/migrate/20181213164010_generate_dc_site.rb
db/migrate/20181213164549_migrate_dc_employer_profiles.rb
db/migrate/20181213164551_migrate_dc_employer_profile_documents.rb
db/migrate/20181213164720_migrate_dc_benefit_application.rb
db/migrate/20181213164835_migrate_dc_hbx_enrollments.rb
db/migrate/20181213164955_migrate_dc_broker_quoting_tool.rb
db/migrate/20190624201110_create_fehb_qles.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model base auto pay migration

---

app/models/census_employee.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
components/benefit_sponsors/spec/dummy/app/models/census_employee.rb
spec/models/census_employee_query_spec.rb

Fix incorrect query for renewal outliers.

Fix query to catch renewal outliers.

---

components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_staff_roles/_search_broker_agency.html.erb

https://devops.dchbx.org/redmine/issues/43274
* ()
* ()
```
```
*
---
---

Broker Staff - select broker button color

---

components/benefit_sponsors/app/views/benefit_sponsors/profiles/registrations/edit.html.slim

https://devops.dchbx.org/redmine/issues/43273
* ()
* ()
```
```
*
---
---

Calendar format for updating the broker agency profile

---

script/cobra_enrollment_report.rb
script/qle_new_hire_report.rb
spec/reports/hbx_reports/shop_enrollment_report_spec.rb
spec/script/qle_new_hire_report_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model base reports

---

app/models/group_selection_eligibility_checker.rb
components/benefit_markets/app/models/benefit_markets/contribution_models/contribution_model.rb

* (Required!)
* ()
* ()
```
```
*
---
---

check age comparison on member relationship.

---

db/migrate/20181213164549_migrate_dc_employer_profiles.rb
db/migrate/20181213164551_migrate_dc_employer_profile_documents.rb
db/migrate/20181213164553_migrate_dc_general_agency_profiles.rb
db/migrate/20181213164556_migrate_dc_broker_agency_profiles.rb
db/migrate/20181213164720_migrate_dc_benefit_application.rb
db/migrate/20181213164751_migrate_dc_broker_agency_accounts.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Dc new model base migration refactor

---

components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

ba off cycle renewal engine level spec fix

---

config/mongoid.yml
db/seedfiles/dc/benefit_markets_seed.rb
db/seedfiles/dc/fixtures/benefit_markets/benefit_market_5d5df96093c4e7428edb52c7.yaml
db/seedfiles/dc/fixtures/benefit_markets/benefit_market_5d5df96093c4e7428edb52c8.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_27840b8e805a47cb851cb99e1404b36c.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_5f6a8c5f8d144700946da4308b7a9262.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_88d36bc5e5054e849d67c32955ed00fd.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_9cabd456a3d14daa947fc5bc384313e6.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_9d0e0a3b58b6457ea396f687ee638ab5.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_aada0c9736dc4e4986b10b2ffa3ade6e.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_b3888017901c47cabf1d7cfd50b34634.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_bcf6e8bb1ea34353b42516996d9e4e81.yaml
db/seedfiles/dc/fixtures/issuer_profiles/issuer_profile_c4ad141325ca41acbcdb4eeae53dd5fe.yaml
db/seedfiles/dc/fixtures/owner_organization_3191d463c7704714b39043b45e6b46b9.yaml
db/seedfiles/dc/fixtures/site_dc.yaml
db/seedfiles/dc/issuer_profiles_seed.rb
db/seedfiles/dc/site_seed.rb
db/seedfiles/people_seed.rb
db/seeds.rb
lib/object_builders/product_builder.rb
lib/tasks/migrations/plans/load_dc_benefit_market_catalog.rake
lib/tasks/migrations/plans/load_rating_areas.rake
lib/tasks/migrations/plans/load_rating_factors.rake
lib/tasks/migrations/plans/load_service_area_data.rake
lib/tasks/upload_sbcs.rake

* (Required!)
* ()
* ()
```
```
*
---
---

Fix seed file

---

jenkins/cucumber.sh

Minor pipeline fix.

---

jenkins/cucumber.sh

Fix cucumber error check.

---

components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
features/group_selection/ivl_plan_shopping.feature
features/step_definitions/group_selection_steps.rb
features/step_definitions/individual_steps.rb
spec/models/queries/named_enrollment_queries_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

quick cucumber fixes

---

app/helpers/config/aca_helper.rb
app/models/benefit_group.rb
app/models/concerns/config/aca_model_concern.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_organizations_general_organizations.rb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/contributions/_contribution_sliders.html.erb
components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plan_selections/_plan_selection_form.html.erb
components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals/benefit_groups_controller_spec.rb
components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals_controller_spec.rb
components/sponsored_benefits/spec/dummy/app/helpers/config/aca_concern.rb
components/sponsored_benefits/spec/dummy/app/models/concerns/config/aca_model_concern.rb
components/sponsored_benefits/spec/dummy/config/settings.yml
components/sponsored_benefits/spec/factories/sponsored_benefits_benefit_applications_benefit_groups.rb
components/sponsored_benefits/spec/shared_contexts/sponsored_benefits.rb
config/settings.yml
spec/data_migrations/fix_title_for_existing_quotes_spec.rb
spec/models/benefit_group_spec.rb
spec/models/sponsored_benefits/plan_design_proposals_controller_spec.rb

* https://devops.dchbx.org/redmine/issues/84611
* ()
* ()
```
```
*
---
---

Er eligibility bqt

---

components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Fix time zone issue in spec.

---

.github/workflows/ruby.yml
test_utilities/run_engines.sh

Create Workflow for Rspec

---

.github/workflows/ruby.yml

Add Cucumber to Github actions.

GitHub actions

---

.github/workflows/ruby.yml
spec/lib/sbc/sbc_processor2015_spec.rb
spec/models/queries/policy_aggregration_pipeline_spec.rb
spec/spec_helper.rb

This will run rspec in parallel on Github actions.

Parallelize rspec Github workflow

---

.github/workflows/ruby.yml
README.md

This pull request adds Yellr integration for Github actions.

Add Yellr Integration

---

.github/workflows/ruby.yml
test_utilities/report_to_yellr.sh

Move yellr curl command to a bash script
Also fixes improper indentation and a mis-labeled spec step (1/4 vs 1/5)

Use bash script for yellr

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/models/eligibility/employee_benefit_packages.rb
spec/factories/users.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Rspec improvements

---

spec/models/factories/eligibility_factory_spec.rb
spec/models/factories/ivl_plan_shopping_eligibility_factory_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fix & optimize failing aptc specs

---

features/employee/conversion_employee.feature
features/step_definitions/conversion_employee_steps.rb
features/support/worlds/benefit_market_world.rb
spec/factories/qualifying_life_event_kinds.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Added cucumber fix for conversion employee feature

---

spec/models/census_employee_spec.rb
spec/models/enrollment_shopping/enrollment_builder_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

ref: Fixes master spec failures due to date mismatch

---

.github/workflows/ruby.yml
.overcommit.yml
.rubocop.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Rubocop updates

---

components/financial_assistance/app/assets/javascripts/financial_assistance/benefit.js
components/financial_assistance/app/assets/javascripts/financial_assistance/fa_integration.js
components/financial_assistance/app/assets/javascripts/financial_assistance/glossary.js
components/financial_assistance/app/assets/javascripts/financial_assistance/income.js
components/financial_assistance/app/assets/javascripts/financial_assistance/step_conditionals.js
components/financial_assistance/app/models/financial_assistance/applicant.rb
components/financial_assistance/app/views/financial_assistance/applications/edit.html.erb
components/financial_assistance/app/views/financial_assistance/shared/_fa_left_nav.html.erb
config/routes.rb
features/financial_assistance/household_info_continue_button.feature
features/step_definitions/household_info_continue_button_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS - Adding household info continue button feature stuff

---

app/views/ui-components/v1/navs/_families_navigation.html.slim
components/financial_assistance/app/controllers/financial_assistance/application_controller.rb
components/financial_assistance/app/controllers/financial_assistance/applications_controller.rb
config/settings.yml
features/financial_assistance/cost_savings.feature
features/financial_assistance/step_definitions/financial_assistance_steps.rb
features/support/worlds/resource_registry_world.rb
system/config/templates/features/aca_individual_market/financial_assistance.yml

This is @raghuramg's pull request to bring in resource_registery to provide configuration for FAA.

Faa configurations

---

components/financial_assistance/app/assets/stylesheets/financial_assistance.scss.erb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #FAA Fix glossay pop-ups on Help Paying for Coverage page

---

app/controllers/insured/interactive_identity_verifications_controller.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy.rb
features/financial_assistance/help_paying_coverage.feature
features/financial_assistance/step_definitions/financial_assistance_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Faa uqhp configurations

---

components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy.rb
components/financial_assistance/app/controllers/financial_assistance/applicants_controller.rb
components/financial_assistance/app/controllers/financial_assistance/applications_controller.rb
components/financial_assistance/app/controllers/financial_assistance/benefits_controller.rb
components/financial_assistance/app/controllers/financial_assistance/deductions_controller.rb
components/financial_assistance/app/controllers/financial_assistance/incomes_controller.rb
components/financial_assistance/app/views/layouts/financial_assistance.html.erb
components/financial_assistance/app/views/layouts/financial_assistance_nav.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

FAA-ref#174275977: help paying for coverage page UI fix

---

app/assets/stylesheets/main.scss.erb
components/financial_assistance/app/assets/javascripts/financial_assistance/deduction.js
components/financial_assistance/app/views/financial_assistance/shared/_fa_left_nav.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Income adjustments bugs

---

components/financial_assistance/spec/dummy/app/models/eligibility_determination.rb
components/financial_assistance/spec/dummy/app/models/family.rb
components/financial_assistance/spec/dummy/app/models/household.rb
components/financial_assistance/spec/dummy/app/models/user.rb
components/financial_assistance/spec/models/financial_assistance/application_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #FAA Add application_spec.rb

---

app/assets/javascripts/fa_integration.js
app/controllers/insured/families_controller.rb
app/controllers/people_controller.rb
app/views/insured/family_members/_dependent.html.erb
app/views/insured/family_members/_family_members.html.erb
app/views/people/landing_pages/_personal.html.erb
app/views/people/update.js.erb
spec/views/people/landing_pages/_personal.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #FAA Fix edit member functionality for UQHP flow

---

app/controllers/insured/consumer_roles_controller.rb
spec/controllers/insured/consumer_roles_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

FAA-ref: redirect to help paying for coverage page

---

components/financial_assistance/app/assets/javascripts/financial_assistance/income.js
components/financial_assistance/app/controllers/financial_assistance/incomes_controller.rb
components/financial_assistance/app/views/financial_assistance/incomes/other.html.erb
features/support/worlds/permissions_world.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #FAA Fix other income page issues

---

app/assets/stylesheets/main.scss.erb
components/financial_assistance/app/assets/stylesheets/financial_assistance/application.scss

* (Required!)
* ()
* ()
```
```
*
---
---

FAA-ref: enable edit and delete icons

---

app/assets/javascripts/relationship_selector.js
app/views/insured/families/family_relationships_matrix.html.erb
app/views/insured/family_relationships/_form.html.erb
app/views/insured/family_relationships/create.js.erb
features/financial_assistance/family_relationships_page.feature
features/financial_assistance/step_definitions/family_relationships_page_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fix amily relationships feature page

---

features/financial_assistance/job_income.feature
features/financial_assistance/step_definitions/job_income_steps.rb
features/step_definitions/household_info_continue_button_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Faa new model job income popups fix

---

features/financial_assistance/eligbility_response_pages.feature
features/financial_assistance/step_definitions/eligibility_response_pages_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

FAA-ref: enable eligibility_response_pages cucumber

---

app/helpers/application_helper.rb
app/views/insured/consumer_roles/edit.html.erb
app/views/insured/consumer_roles/ridp_agreement.html.erb
app/views/insured/consumer_roles/search.html.haml
app/views/insured/interactive_identity_verifications/new.html.haml
app/views/shared/_individual_progress.html.haml
spec/views/insured/family_members/index.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Remove horizontal flow

---

app/assets/stylesheets/application.scss.erb
app/views/insured/consumer_roles/edit.html.erb
app/views/insured/consumer_roles/match.html.haml
app/views/insured/consumer_roles/search.html.haml
app/views/shared/_consumer_home_address_fields.html.erb

* (Required!)
* ()
* ()
```
```
*
---
---

Ui spacing

---

app/controllers/insured/families_controller.rb
app/models/concerns/scheduled_event_service.rb
app/models/qualifying_life_event_kind.rb
components/benefit_sponsors/spec/dummy/app/models/qualifying_life_event_kind.rb
script/final_eligibility_notice_script.rb
spec/controllers/insured/families_controller_spec.rb
spec/models/hbx_enrollment_spec.rb
spec/script/final_eligibility_notice_script_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #FEL Added script for fel notice

---

package.json

* (Required!)
* ()
* ()
```
```
*
---
---

fix asset precompile issue due to angular cli / typscript versions

---

app/domain/operations/fehb/dependent_age_off.rb
app/models/group_selection_eligibility_checker.rb
app/models/hbx_enrollment.rb
spec/domain/operations/fehb/dependent_age_off_spec.rb
system/config/templates/features/enroll_app/enroll_app.yml

* (Required!)
* ()
* ()
```
```
*
---
---

ref: 88755 Adds dependent age off auto job for fehb market.

---

.gitignore
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollments_monthly_query_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_action_service_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/sponsored_benefits/contribution_level_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/subscribers/employer_benefit_renewal_subscriber_spec.rb
components/financial_assistance/spec/models/financial_assistance/application_spec.rb
features/brokers/broker_quote.feature
features/employers/edit_renewing_plan_year_for_employer.feature
features/step_definitions/broker_employee_quote_steps.rb
features/step_definitions/employers_steps.rb
features/step_definitions/integration_steps.rb
features/step_definitions/renewal_steps.rb
features/support/worlds/benefit_application_world.rb
features/support/worlds/benefit_market_world.rb
spec/domain/operations/individual/cancel_renewal_enrollment_spec.rb
spec/models/employee_role_integration_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Master spec fixes

---

.github/workflows/full-suite.yml

this will run our full check suite workflow every day at 6 AM UTC

add cron schedule to full check suite

---

components/benefit_markets/spec/domain/benefit_markets/operations/benefit_markets/create_benefit_sponsor_catalog_spec.rb
components/benefit_markets/spec/domain/benefit_markets/operations/products/find_spec.rb
components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
components/benefit_sponsors/spec/factories/benefit_sponsors_site.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy_spec.rb
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
components/sponsored_benefits/spec/shared_contexts/sponsored_benefits.rb
features/step_definitions/integration_steps.rb
spec/controllers/insured/group_selection_controller_spec.rb
spec/domain/operations/qualifying_life_event_kind/persist_spec.rb
spec/models/sponsored_benefits/plan_design_proposals_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Spec failures dec 1

---

app/models/coverage_record.rb
app/models/employer_staff_role.rb
app/models/my_portal/employee_coverage.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Employee coverage

---

app/controllers/employers/census_employees_controller.rb
app/models/census_employee.rb
spec/controllers/employers/census_employees_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Brakeman Fixes - Fixes params vulnerability.

---

hugo/content/docs/_index.md
hugo/layouts/docs/list.html

* (Required!)
* ()
* ()
```
```
*
---
---

Hugo documentation - fixes titles.

---

hugo/content/docs/models/employees.md
hugo/content/docs/models/employers.md
hugo/content/docs/models/hbx_enrollment.md
hugo/content/docs/models/special_enrollment_periods.md

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Hugo documentation - Takes draft off.

---

hugo/content/docs/contributing.md
hugo/content/docs/local_hugo_setup.md

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Hugo docs - Setup insturctions.

---

app/controllers/general_agencies/profiles_controller.rb
app/controllers/inboxes_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/families_controller.rb
app/controllers/insured/family_members_controller.rb
hugo/content/docs/brakeman.md
spec/controllers/insured/family_members_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Mas assignment part 2 zane

---

app/controllers/broker_agencies/profiles_controller.rb
app/controllers/documents_controller.rb
app/controllers/employers/employer_profiles_controller.rb
app/controllers/employers/people_controller.rb
app/controllers/exchanges/broker_applicants_controller.rb
app/controllers/exchanges/hbx_profiles_controller.rb
app/controllers/exchanges/products_controller.rb
app/controllers/exchanges/residents_controller.rb
app/controllers/exchanges/scheduled_events_controller.rb
app/controllers/people_controller.rb
spec/controllers/broker_agencies/profiles_controller_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Brakeman medium mass assignment errors

---

hugo/content/docs/brakeman.md

* (Required!)
* ()
* ()
```
```
*
---
---

Continued brakeman docs

---

app/controllers/exchanges/manage_sep_types_controller.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Brakeman - Mangae sep types controller.

---

spec/factories/benefit_sponsorships.rb
spec/models/time_keeper_spec.rb
spec/notices/ivl_notices/final_eligibility_notice_aqhp_spec.rb
spec/test_data/notices/event_report_09_11_2020.csv

* (Required!)
* ()
* ()
```
```
*
---
---

Fix spec failures

---

app/controllers/broker_agencies/broker_roles_controller.rb
app/controllers/documents_controller.rb
app/controllers/employers/employer_profiles_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/employee_roles_controller.rb
app/controllers/insured/group_selection_controller.rb
app/models/factories/enrollment_factory.rb
app/models/group_selection_prevarication_adapter.rb
spec/models/factories/enrollment_factory_spec.rb
spec/models/subscribers/family_application_completed_spec.rb
spec/test_data/verified_family_payloads/core_scenarios/core_scenarios_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Brakeman - Fixes consumer roles controller mass assignment issues.

---

app/models/admin/aptc.rb
app/models/insured/factories/self_service_factory.rb
components/benefit_markets/spec/domain/benefit_markets/operations/contribution_models/assign_spec.rb
components/benefit_markets/spec/dummy/system/config/templates/features/aca_shop_market/contributions.yml
components/benefit_sponsors/spec/dummy/system/config/templates/features/aca_shop_market/contributions.yml
components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/aca_shop_benefit_sponsorship_service_spec.rb
components/sponsored_benefits/spec/dummy/system/config/templates/features/aca_shop_market/contributions.yml
features/hbx_admin/manage_sep_types/individual_sep_type_eligibility.feature
features/hbx_admin/manage_sep_types/sep_type_eligibility.feature
features/hbx_admin/manage_sep_types/shop_sep_type_eligibility.feature
features/hbx_admin/step_definitions/manage_sep_types_steps.rb
lib/tasks/fix_2020_ivl_benefit_packages.rake
spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb
spec/data_migrations/fix_2020_ivl_benefit_packages_spec.rb
spec/data_migrations/remove_enrolled_contingent_state_spec.rb
spec/factories/special_enrollment_periods.rb
spec/models/factories/eligibility_factory_spec.rb
spec/models/factories/ivl_plan_shopping_eligibility_factory_spec.rb
spec/models/family_member_spec.rb
spec/models/insured/factories/self_service_factory_spec.rb
spec/models/insured/forms/self_term_or_cancel_form_spec.rb
spec/models/tax_household_member_spec.rb
spec/models/tax_household_spec.rb
spec/script/shop_sep_query_spec.rb
spec/shared_contexts/ivl_eligibility.rb
system/config/templates/features/aca_shop_market/contributions.yml

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance Team - Fixing spec dummy contributions yml missing.

---

app/controllers/concerns/vlp_doc.rb
app/controllers/exchanges/products_controller.rb
app/controllers/insured/family_members_controller.rb
app/controllers/users_controller.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Brakeman - Fixes VLP doc brakeman warnings.

---

app/domain/operations/individual/cancel_renewal_enrollment.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #91082 Get renewal year from bcp

---

Gemfile
Gemfile.lock
hugo/content/docs/brakeman.md

This is an update to the Brakeman docs.

Brakeman docs update

---

hugo/content/docs/internationalization_and_translations.md

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Adds internationalizacion docs.

---

hugo/content/docs/internationalization_and_translations.md

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Clarifctions for internationalization documenttion.

---

app/views/ui-components/v1/filters/_plan_filters.html.slim

* (Required!)
* ()
* ()
```
```
*
---
---

Update padding/font for modal

---

app/views/insured/families/_enrollment.html.erb
app/views/insured/group_selection/edit_plan.html.erb
spec/views/insured/families/_enrollment.html.erb_spec.rb
spec/views/insured/group_selection/edit_plan.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Fixes missing translations.

---

app/views/insured/families/_enrollment.html.erb
app/views/insured/group_selection/_enrollment.html.erb
spec/views/insured/families/_enrollment.html.erb_spec.rb
spec/views/insured/group_selection/_enrollment.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Adds missing translations to enrollment partials.

---

db/seedfiles/translations/en/dc/insured.rb
features/step_definitions/group_selection_steps.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

ref: 92167 fixes errors message to remove 'yet'

---

script/kaiser_enrollment_list_for_pay_now.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs#paynow_enroll_report Added loggers files & changed file name

---

app/views/notices/ivl/ivl_vta_notice.html.erb
spec/views/notices/ivl/ivl_vta_notice.html.erb_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #92296 2020 Template updates

---

spec/helpers/view_translations_linter_spec.rb
spec/support/fake_view.html.erb
spec/support/fixtures/approved_translation_strings.yml
spec/support/test_initiate_cobra.html.erb
spec/support/view_translations_linter.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Linting branch hotfix

---

spec/helpers/view_translations_linter_spec.rb
spec/support/fake_view_2.html
spec/support/fake_view_2.html.erb
spec/support/fixtures/approved_translation_strings.yml
spec/support/view_translations_linter.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Additional view linter checks

---

app/controllers/translations_controller.rb
app/policies/hbx_profile_policy.rb
app/views/translations/index.html.erb
spec/controllers/translations_controller_spec.rb
spec/policies/hbx_profile_policy_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Fixes translations permisssions.

---

app/controllers/payment_transactions_controller.rb
app/domain/operations/generate_saml_response.rb
spec/domain/operations/generate_saml_response_spec.rb
spec/support/fixtures/approved_translation_strings.yml

* (Required!)
* ()
* ()
```
```
*
---
---

Paynow 2 176573485

---

hugo/content/docs/resource_registry.md

* (Required!)
* ()
* ()
```
```
*
---
---

REFS Maintenance - Adds ressource registry docs.

---

app/helpers/insured/plan_shopping/pay_now_helper.rb
app/views/insured/families/_enrollment.html.erb
spec/helpers/insured/plan_shopping/pay_now_helper_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs#paynow_bug_fixes Added new changes to view file & helper methods
