dchbx/enroll

app/models/enrollee.rb
app/models/family_member.rb
app/models/phone.rb
app/models/policy.rb
spec/models/enrollee_spec.rb
spec/models/family_member_spec.rb
spec/models/phone_spec.rb

Family member spec

---

app/models/concerns/value_parsers/optimistic_ssn_parser.rb
spec/models/concerns/value_parsers/optimistic_ssn_parser_spec.rb

Make it clearer when this parser should not be used.

Better naming and documentation.

---

app/models/access_policies/employee_role.rb
spec/controllers/insured/employee_roles_controller_spec.rb
spec/factories/users.rb
spec/models/access_policies/employee_role_spec.rb

Hotfix 4786

---

app/models/broker_role.rb
lib/tasks/hbx_reports/brokers.rake

* https://devops.dchbx.org/redmine/issues/7494
```
3764 examples, 0 failures, 73 pendings
Took 224 seconds (3:44)
5m40.055s
```
* 1.7.5
---
---
* Rake task lib/tasks/hbx_reports/brokers.rake

Refs #7494 Fixes daily approved broker report issue

---

app/models/benefit_group.rb
app/models/employer_profile.rb
app/models/hbx_enrollment.rb
app/views/insured/families/_employer_panel.html.erb
features/employee/conversion_employee.feature
features/step_definitions/conversion_employee_steps.rb
spec/factories/families.rb
spec/factories/people.rb
spec/models/benefit_group_spec.rb
spec/models/general_agency_profile_spec.rb

* https://devops.dchbx.org/redmine/issues/6544
* https://devops.dchbx.org/redmine/issues/6820
```
3769 examples, 0 failures, 73 pendings
Took 206 seconds (3:26)
39 scenarios (39 passed)
823 steps (823 passed)
6m8.587s
```
* 1.7.3
---
---

Hotfix 6544

---

app/controllers/concerns/vlp_doc.rb
app/models/vlp_document.rb
app/views/insured/consumer_roles/docs_shared/_expiration_date.html.erb

https://devops.dchbx.org/redmine/issues/6900
```
Finished in 2 minutes 5.7 seconds (files took 6.16 seconds to load)
3763 examples, 0 failures, 73 pendings
Took 135 seconds (2:15)
4m40.882s
```
tag: refs/tags/1.7.4
---
---

refs #6900 change expiration date type to datetime in vlp document model

---

app/models/forms/employer_profile.rb
app/models/forms/organization_signup.rb
app/models/person.rb
app/views/employers/employer_profiles/_employer_form.html.erb
features/employers/employer_profile.feature
features/step_definitions/employer_profile_steps.rb

* https://devops.dchbx.org/redmine/issues/7582
```
3771 examples, 0 failures, 73 pendings
Took 197 seconds (3:17)
34 scenarios (34 passed)
785 steps (785 passed)
6m16.328s
```
* 1.7.6

Refs #7582 POC

---

app/views/shared/_sep_progress.html.haml

https://devops.dchbx.org/redmine/issues/5537
```
970 examples, 0 failures, 28 pending
3777 examples, 0 failures, 73 pendings
Took 166 seconds (2:46)39 scenarios (39 passed)
823 steps (823 passed)
5m25.305s
```
*
tag: refs/tags/1.7.6
---
---

refs #5537 fix receipt page percentage_complete value

---

app/views/insured/employee_roles/_no_match.html.haml
spec/views/insured/employee_roles/no_match.html.haml_spec.rb

https://devops.dchbx.org/redmine/issues/7545
```
Finished in 7 minutes 4 seconds (files took 14.18 seconds to load)
2055 examples, 0 failures, 48 pending
3771 examples, 0 failures, 73 pending
7m25.862s
```
*
---
---

Enhancement-7545

---

app/assets/stylesheets/application.scss.erb
app/assets/stylesheets/insured.scss.erb
app/views/insured/families/_apply_for_medicaid_widget.html.erb
app/views/insured/families/_shop_for_plans_widget.html.erb

* https://devops.dchbx.org/redmine/issues/6624
* (if more)
```
4017 examples, 0 failures, 77 pendings
Took 244 seconds (4:04)
56 scenarios (56 passed)
978 steps (978 passed)
7m21.849s
```
*needs rebase
---
---

Ticket 6624

---

app/models/family.rb
features/step_definitions/brokers_steps.rb
features/step_definitions/individual_steps.rb
features/step_definitions/new_hire_steps.rb
spec/models/hbx_enrollment_spec.rb

* https://devops.dchbx.org/redmine/issues/7635
```
3778 examples, 0 failures, 73 pendings
44 scenarios (0 failed, 44 passed)
881 steps (0 failed, 81 skipped, 800 passed)
```
* master
* Only testable for the 8/1 employer data set, see the employees for BLESSED FAMILY ASSOCIATION INTERNATIONAL for example
Don't show me canceled conversion policies.

Hotfix 7635

---

app/controllers/employers/plan_years_controller.rb
spec/controllers/employers/plan_years_controller_spec.rb

https://devops.dchbx.org/redmine/issues/6207
https://devops.dchbx.org/redmine/issues/5582
```
bundle exec rake parallel:spec[2]  
Finished in 7 minutes 8 seconds (files took 11.5 seconds to load)
3760 examples, 0 failures, 73 pending 
7m19.026s
```

Hot fix-6207/5582: Fix for event publish cannot transit state

---

app/controllers/employers/plan_years_controller.rb
app/helpers/application_helper.rb
config/settings.yml
features/step_definitions/new_hire_steps.rb
spec/controllers/employers/plan_years_controller_spec.rb

https://devops.dchbx.org/redmine/issues/7667
Finished in 15 minutes 21 seconds (files took 54.28 seconds to load)
3846 examples, 0 failures, 73 pending
10m4.096s
```

fix for copyright period

---

app/models/consumer_role.rb
app/models/lawful_presence_determination.rb
script/populate_citizenship_result.rb

* https://devops.dchbx.org/redmine/issues/7703
```
3848 examples, 0 failures, 73 pendings
Took 212 seconds (3:32)
6m47.771s
```
* 1.8.0

Separate column for citizenship results.

---

app/controllers/employers/employer_staff_roles_controller.rb
features/employers/employer_profile.feature
features/step_definitions/employer_profile_steps.rb

* https://devops.dchbx.org/redmine/issues/7286
3777 examples, 0 failures, 73 pendings
45 scenarios (45 passed)
891 steps (891 passed)
6m32.867s
* tag: 1.7.7
You may delete a pending applicant
Coding style commit added during peer review

Refs #7286 delete pending applicants

---

app/assets/stylesheets/insured.scss.erb
app/views/insured/families/_qle_detail.html.erb
app/views/insured/plan_shoppings/_plan_details.html.erb
app/views/shared/_sep_progress.html.haml

https://devops.dchbx.org/redmine/issues/7722
just removed css class
```
```
tag: refs/tags/1.8.1
---
---

refs #7722 fix misaligned sign up button

---

app/assets/stylesheets/application.scss.erb
app/assets/stylesheets/globals.scss.erb
app/views/shared/_census_employee_fields.html.erb
vendor/assets/stylesheets/selectric.css

https://devops.dchbx.org/redmine/issues/7360
```
873 examples, 0 failures, 12 pending
3763 examples, 0 failures, 73 pendings
Took 130 seconds (2:10)
29 scenarios (1 failed, 28 passed)
727 steps (1 failed, 8 skipped, 718 passed)
4m37.167s
^^^ random failure, and then...
34 steps (34 passed)
0m20.277s
```
tag: refs/tags/1.7.4
---
---

refs #7360 add global style for creating labeled selectrics

---

app/controllers/employers/employer_profiles_controller.rb
app/models/census_employee.rb
app/views/employers/employer_profiles/my_account/_census_employees.html.erb
config/routes.rb
spec/controllers/employers/employer_profiles_controller_spec.rb

https://devops.dchbx.org/redmine/issues/5297
```
871 examples, 0 failures, 22 pending
3765 examples, 0 failures, 73 pendings
Took 131 seconds (2:11)29 scenarios (29 passed)
4m43.013s
```
*
tag: refs/tags/1.7.5
---
---

refs #5297 add export employee roster functionality and test

---

app/models/access_policies/employee_role.rb
spec/controllers/insured/employee_roles_controller_spec.rb
spec/models/access_policies/employee_role_spec.rb

https://devops.dchbx.org/redmine/issues/7670
```
Finished in 2 minutes 13.5 seconds (files took 6.29 seconds to load)
954 examples, 0 failures, 18 pending
3849 examples, 0 failures, 73 pendings
Took 141 seconds (2:21)
5m33.043s
```
*
---
---

Refs# 7670 allows general agent to access employee bookmark url

---

app/assets/stylesheets/globals.scss.erb

https://devops.dchbx.org/redmine/issues/7806
```
Finished in 2 minutes 0.1 seconds (files took 6.39 seconds to load)
1013 examples, 0 failures, 17 pending
Took 128 seconds (2:08)
5m45.226s
```
tag: refs/tags/1.8.4
*
---
---

refs #7806 fix ui issue with selectric-labeled style

---

app/controllers/insured/families_controller.rb
app/views/insured/families/check_qle_date.js.erb
features/step_definitions/integration_steps.rb
spec/controllers/insured/families_controller_spec.rb
spec/views/insured/families/check_qle_date.js.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7544
Finished in 10 minutes 58 seconds (files took 12.94 seconds to load)
3847 examples, 0 failures, 73 pending
7m16.397s

Enhancement 7544

---

app/controllers/employers/employer_profiles_controller.rb
app/views/employers/employer_profiles/show_pending.html.erb
features/step_definitions/employer_profile_steps.rb

* https://devops.dchbx.org/redmine/issues/7320
```
Finished in 13 minutes 44 seconds (files took 29.54 seconds to load)
3777 examples, 0 failures, 73 pending
44 scenarios (44 passed)
881 steps (881 passed)
9m4.483s
```
tag: 1.7.7
---
---

POCs Need Confirmation Page After Submitting Application Page

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/invoices/employer_invoice.rb
app/invoices/invoice_helper.rb
lib/tasks/employer_invoice.rake

https://devops.dchbx.org/redmine/issues/7793
Finished in 2 minutes 53.5 seconds (files took 7.63 seconds to load)
927 examples, 0 failures, 26 pending
3899 examples, 0 failures, 77 pendings
Took 183 seconds (3:03)
6m15.120s
1.8.4
---
---
@raghuramg 

#7793 Generates invoices

---

app/controllers/broker_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/_employers.html.erb
app/views/broker_agencies/profiles/employers.js.erb
app/views/employers/employer_profiles/_index.html.erb
features/general_agencies/step_definitions/ga_steps.rb
features/step_definitions/general_agency_steps.rb

Per requested by the functional testing team, sorted columns 'legal name', 'enroll status', 'Effective Date', and 'General Agency'

Hotfix 5388

---

app/assets/stylesheets/custom.scss.erb
app/assets/stylesheets/main.scss.erb.erb
app/assets/stylesheets/modules.scss.erb
app/assets/stylesheets/new.scss.erb
app/views/employers/employer_profiles/my_account/_census_employees.html.erb
app/views/employers/employer_profiles/my_account/_home_tab.html.erb
app/views/shared/_add_dependents.html.erb

https://devops.dchbx.org/redmine/issues/5297
```
3906 examples, 0 failures, 77 pendings
Took 200 seconds (3:20)
7m42.007s
```
*
---
---

refs #5297 fixes ui bugs in employer portal production

---

app/assets/stylesheets/globals.scss.erb
app/assets/stylesheets/main.scss.erb.erb
app/views/devise/registrations/new.html.erb
app/views/employers/census_employees/_member_fields.html.erb
app/views/employers/people/_search_fields.html.erb
app/views/layouts/_flash.html.erb
app/views/people/landing_pages/_personal.html.erb
app/views/shared/_add_dependents.html.erb
app/views/shared/_person_name_fields.html.erb
app/views/shared/person/_consumer_information.html.erb
app/views/shared/person/_personal_information.html.erb
features/step_definitions/employers_steps.rb

*  https://devops.dchbx.org/redmine/issues/7475
```
Took 254 seconds (4:14)
6m52.115s
```

Enhancement 7475

---

app/assets/javascripts/set_tab_content.js
app/controllers/broker_agencies/profiles_controller.rb
app/controllers/exchanges/hbx_profiles_controller.rb
app/controllers/general_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/_menu.html.erb
app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
app/views/general_agencies/profiles/_menu.html.erb
app/views/layouts/_flash.html.erb
app/views/layouts/single_column.html.erb
spec/views/broker_agencies/profiles/_menu.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7816
```
Finished in 2 minutes 21.7 seconds (files took 5.99 seconds to load)
1127 examples, 0 failures, 37 pending
Took 149 seconds (2:29)
5m40.432s
```
tag: refs/tags/1.8.6
---
---

refs #7816 add single_column layout, level set flash

---

app/assets/stylesheets/new.scss.erb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
spec/views/employers/employer_profiles/my_account/benefits.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7848
```
Finished in 14 minutes 10 seconds (files took 26.31 seconds to load)
3906 examples, 0 failures, 77 pending
9m40.899s
```
tag: 1.8.8
*
---
---

Enhancement 7848

---

app/models/plan_year.rb
lib/tasks/migrations/cancel_employer_renewal.rake

*https://devops.dchbx.org/redmine/issues/7775
```
Finished in 7 minutes 21 seconds (files took 30.05 seconds to load)
967 examples, 0 failures, 14 pending
Took 477 seconds (7:57)
9m2.532s
```

Terminate ER: Democracy Travel in Enroll App

---

lib/tasks/migrations/terminate_employer_accounts.rake

*https://devops.dchbx.org/redmine/issues/7753
```
Finished in 7 minutes 40 seconds (files took 30.56 seconds to load)
1172 examples, 0 failures, 35 pending
Took 497 seconds (8:17)
```
*
---
---

Refs #7753 ER Termination in EA

---

app/assets/javascripts/demographics_fields.js
app/views/insured/family_members/_dependent_form.html.erb
app/views/people/landing_pages/_personal.html.erb
app/views/shared/_individual_progress.html.haml
features/step_definitions/individual_steps.rb
features/step_definitions/integration_steps.rb
features/step_definitions/verification_process_steps.rb

https://devops.dchbx.org/redmine/issues/2885
```
755 examples, 0 failures, 25 pending
3763 examples, 0 failures, 73 pendings
Took 133 seconds (2:13)
4m54.189s
```
*
tag: refs/tags/1.7.4
---
---

refs #2885 adjust cucumbers for silent errors js fix

---

lib/tasks/hbx_reports/employee_initiated _termination.rake

* https://devops.dchbx.org/redmine/issues/5507
```
Finished in 6 minutes 22 seconds (files took 9.26 seconds to load)
3906 examples, 0 failures, 77 pendings
7m17.120s
```
*
---
---

Support #5507

---

app/controllers/families_controller.rb
spec/controllers/families_controller_spec.rb

* https://devops.dchbx.org/redmine/issues/5377
```
bundle exec rake parallel:spec[2]
Finished in 6 minutes 19 seconds (files took 18.77 seconds to load)
1805 examples, 0 failures, 44 pending
3778 examples, 0 failures, 73 pendings
44 scenarios (44 passed)
881 steps (881 passed)
8m26.072s
```
*
---
---
Looks like nothing to test for testers we'll throw this in preprod and see if it quiets the robot

HotFix-5377

---

app/helpers/verification_helper.rb
lib/tasks/dual_roles.rake

https://devops.dchbx.org/redmine/issues/7834
Finished in 10 minutes 41 seconds (files took 12.45 seconds to load)
3906 examples, 0 failures, 77 pending
7m24.083s
1.8.6

Support 7834

---

app/models/person.rb
spec/models/person_spec.rb

https://devops.dchbx.org/redmine/issues/7681
```
718 examples, 0 failures, 17 pending
3912 examples, 0 failures, 77 pendings
```
*
---
---

Refs #7681 - deactivate all employer staff roles

---

app/controllers/insured/consumer_roles_controller.rb
app/views/insured/consumer_roles/privacy.html.erb
spec/controllers/insured/consumer_roles_controller_spec.rb

https://devops.dchbx.org/redmine/issues/7960
Finished in 12 minutes 9 seconds (files took 15.44 seconds to load)
3914 examples, 0 failures, 77 pending
7m33.759s
1.8.15

enhancement-7960

---

lib/tasks/hbx_reports/ivl_terminations_report.rake

https://devops.dchbx.org/redmine/issues/7758
3921 examples, 0 failures, 77 pendings
```
*
---
---

Support 7758

---

lib/tasks/migrations/cancel_employer_renewal.rake

https://devops.dchbx.org/redmine/issues/7994
https://devops.dchbx.org/redmine/issues/7993
https://devops.dchbx.org/redmine/issues/7992
https://devops.dchbx.org/redmine/issues/7954 (Run this One later.)
Finished in 12 minutes 35 seconds (files took 12.28 seconds to load)
3921 examples, 0 failures, 77 pending
7m23.425s
1.8.15

Refs #7954 de-linked employees from terminated employer

---

app/controllers/broker_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/_families.html.erb
app/views/shared/_alph_paginate_remote.html.erb
app/views/shared/_search.html.erb
spec/views/broker_agencies/profiles/_families.html.erb_spec.rb
spec/views/shared/_alph_paginate_remote.html.erb_spec.rb
spec/views/shared/_search.html.erb_spec.rb

* https://devops.dchbx.org/redmine/issues/4981
```
3852 examples, 0 failures, 73 pendings
```
*
---
---

Hotfix 4981

---

app/views/devise/sessions/session_expiration_warning.js.erb
app/views/layouts/_header.html.erb
config/initializers/devise.rb
lib/custom_failure_app.rb

https://devops.dchbx.org/redmine/issues/7988
```
Finished in 2 minutes 2.1 seconds (files took 6.96 seconds to load)
1127 examples, 0 failures, 12 pending
3925 examples, 0 failures, 77 pendings
Took 130 seconds (2:10)
5m48.248s
```
tag: refs/tags/1.8.17
---
---

Hotfix 7988

---

app/controllers/insured/employee_roles_controller.rb
app/models/factories/enrollment_factory.rb
spec/controllers/insured/employee_roles_controller_spec.rb
spec/models/factories/enrollment_factory_spec.rb

https://devops.dchbx.org/redmine/issues/7990
https://devops.dchbx.org/redmine/issues/7863
```
1113 examples, 0 failures, 21 pending
3926 examples, 0 failures, 77 pendings
```
*
---
---

Refs #7990 - sets matched employee contact info in enrollment factory

---

app/models/factories/family_enrollment_renewal_factory.rb
spec/models/factories/family_enrollment_renewal_factory_spec.rb

https://devops.dchbx.org/redmine/issues/4725
Finished in 2 minutes 17.1 seconds (files took 6.59 seconds to load)
897 examples, 0 failures, 27 pending
6m21.607s
* 1.8.18
Fixed code not to renew employees when renewal plan no longer offered by the employers
Todo: Write a rake task to export & fix the people who already got effected by this issue.
…e renewal plan

Refs #4725 Generate passive renewals only for the plans offered by employer

---

app/controllers/insured/employee_roles_controller.rb
app/views/insured/employee_roles/_welcome_msg.html.haml
app/views/insured/employee_roles/privacy.html.erb
app/views/insured/employee_roles/welcome.html.haml
app/views/user_mailer/invitation_email.html.erb
config/routes.rb
spec/controllers/insured/employee_roles_controller_spec.rb

https://devops.dchbx.org/redmine/issues/8072
```
Finished in 2 minutes 15.1 seconds (files took 5.85 seconds to load)
1014 examples, 0 failures, 21 pending
3963 examples, 0 failures, 79 pendings
Took 144 seconds (2:24)
5m44.461s
```
tag: refs/tags/1.8.21
---
---

refs #8072 restore employee roles welcome route

---

app/helpers/employers/broker_agency_helper.rb
app/models/broker_role.rb
app/models/employer_profile.rb
app/views/employers/broker_agency/_active_broker.html.erb
spec/views/employers/broker_agency/_active_broker.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7474
```
Finished in 2 minutes 7.3 seconds (files took 6.64 seconds to load)
1027 examples, 0 failures, 10 pending
3908 examples, 0 failures, 77 pendings
Took 137 seconds (2:17)
5m47.648s
```
tag: refs/tags/1.8.13
---
---

refs #7474 add assignment date to employers active broker page

---

app/views/employers/employer_profiles/my_account/_billing.html.erb
spec/views/employers/employer_profiles/_billing.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7026
```
1 deprecation warning total
Finished in 8 minutes 44 seconds (files took 9.3 seconds to load)
3910 examples, 0 failures, 77 pending
5m58.059s
```
tag: refs/tags/1.8.14
---
---

refs #7026 add hbx id to employer profiles bill page and add spec

---

app/controllers/broker_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/_staff.html.erb
app/views/broker_agencies/profiles/_staff_table.html.erb
spec/views/broker_agencies/profiles/_staff_table.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/6813
```
Finished in 2 minutes 20.2 seconds (files took 5.83 seconds to load)
1093 examples, 0 failures, 6 pending
3963 examples, 0 failures, 79 pendings
Took 149 seconds (2:29)
5m59.139s
```
*
1.8.21
---
```
Finished in 2 minutes 40.3 seconds (files took 8.97 seconds to load)
1078 examples, 0 failures, 7 pending
3963 examples, 0 failures, 79 pendings
Took 172 seconds (2:52)
6m41.813s
```

Refs #6813 Search box under Broker IVL/ER help

---

app/views/employers/employer_profiles/my_account/_benefits.html.erb
app/views/employers/employer_profiles/my_account/_home_tab.html.erb
spec/views/employers/employer_profiles/my_account/benefits.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/5139
```
Finished in 4 minutes 29.8 seconds (files took 13.27 seconds to load)
1019 examples, 0 failures, 10 pending
3971 examples, 0 failures, 78 pendings
Took 286 seconds (4:46)
48 scenarios (1 failed, 47 passed)
916 steps (1 failed, 12 skipped, 903 passed)
6m3.650s
and then... 
34 steps (34 passed)
0m20.319s
```
tag: refs/tags/1.8.23
---
---

Hotfix 5139

---

lib/tasks/export_employers.rake

https://devops.dchbx.org/redmine/issues/4776
https://devops.dchbx.org/redmine/issues/7870
967 examples, 0 failures, 11 pending
3912 examples, 0 failures, 77 pendings
*
---
---

Refs #7870 added new fields verified brokers match brokers from admin panel

---

app/assets/javascripts/hints.js
app/assets/stylesheets/bootstrap_overrides.scss.erb
app/controllers/welcome_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/shared/_my_portal_links.html.erb
config/routes.rb
spec/controllers/welcome_controller_spec.rb
spec/views/shared/my_portal_links.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7922
```
Finished in 2 minutes 1.7 seconds (files took 5.75 seconds to load)
931 examples, 0 failures, 32 pending
3926 examples, 0 failures, 77 pendings
Took 130 seconds (2:10)
5m44.881s
```
tag: refs/tags/1.8.18
---
---

refs #7922 add popover explaining my portal links dropdown

---

app/controllers/broker_agencies/profiles_controller.rb

https://devops.dchbx.org/redmine/issues/8060
```
972 examples, 0 failures, 26 pending
3967 examples, 0 failures, 78 pendings
```
*
---
---

Refs #8060 - render broker id in broker agency edit

---

app/models/hbx_enrollment.rb
lib/tasks/datafix_hbx_enrollment_created_at.rake
spec/models/hbx_enrollment_spec.rb

https://devops.dchbx.org/redmine/issues/5579
Finished in 2 minutes 24.4 seconds (files took 6.64 seconds to load)
1066 examples, 0 failures, 29 pending
3963 examples, 0 failures, 79 pendings
1.8.21
---
---

Enhancement 5579

---

app/controllers/broker_agencies/broker_roles_controller.rb
app/mailers/user_mailer.rb
app/models/forms/broker_agency_profile.rb
app/views/user_mailer/broker_application_confirmation.html.erb
features/step_definitions/brokers_steps.rb
features/step_definitions/general_agency_steps.rb

https://devops.dchbx.org/redmine/issues/7500
Finished in 2 minutes 18 seconds (files took 7.98 seconds to load)
982 examples, 0 failures, 26 pending
3914 examples, 0 failures, 77 pendings
Took 147 seconds (2:27)
6m1.279s
*1.8.15*
---
---

Refs #7500 Sends confirmation email when broker creates agency

---

lib/tasks/hbx_reports/ivl_termination_submitted_on_report.rake

* https://devops.dchbx.org/redmine/issues/8266
```
Finished in 6 minutes 13 seconds (files took 10.97 seconds to load)
2057 examples, 0 failures, 34 pending
3991 examples, 0 failures, 78 pending
```
*
---
---
…revious day

Enhancement: #8266 List of IVL users submitted termination

---

app/models/employer_profile.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
spec/models/employer_profile_spec.rb
spec/views/employers/employer_profiles/my_account/benefits.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/8058
```
Finished in 6 minutes 30 seconds (files took 11.08 seconds to load)
2080 examples, 0 failures, 28 pending
3969 examples, 0 failures, 78 pendings
Took 403 seconds (6:43)
7m13.737s
```
*
---
---

Bug-8058: Fix for multiple draft plan years

---

app/data_migrations/correct_citizen_with_ssn.rb
app/data_migrations/correct_curam_vlp_status.rb
app/data_migrations/correct_non_citizen_with_ssn.rb
app/models/consumer_role.rb
app/models/employer_profile.rb
app/models/lawful_presence_determination.rb
app/models/person.rb
app/views/employers/employer_profiles/my_account/_benefits.html.erb
lib/tasks/correct_citizen_with_ssn.rake
lib/tasks/correct_non_citizen_with_ssn.rake
lib/tasks/hbx_reports/ivl_termination_submitted_on_report.rake
spec/data_migrations/correct_citizen_with_ssn_spec.rb
spec/data_migrations/correct_non_citizen_with_ssn_spec.rb
spec/factories/people.rb
spec/models/consumer_role_spec.rb
spec/models/employer_profile_spec.rb
spec/models/person_spec.rb
spec/models/subscribers/ssa_verification_spec.rb
spec/views/employers/employer_profiles/my_account/benefits.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/8248
4024 examples, 0 failures, 78 pendings
5m42.280s
*
---
---
based on the most recent hub reping, add validation fixes
and citizenship records based on hub responses

Refs #8248 add datamigration fix for citizen and non citizen with ssn

---

app/controllers/general_agencies/profiles_controller.rb
app/views/general_agencies/profiles/_families.html.erb
spec/views/general_agencies/_families.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/7070
Finished in 2 minutes 24.4 seconds (files took 6.57 seconds to load)
928 examples, 0 failures, 6 pending
3905 examples, 0 failures, 77 pending
Took 154 seconds (2:34)
5m54.530s
1.8.6
---
---

Refs #7070 Search box - GA portal - Families Tab

---

app/views/broker_agencies/profiles/_show.html.erb

https://devops.dchbx.org/redmine/issues/7845
```
1023 examples, 0 failures, 19 pending
3968 examples, 0 failures, 78 pendings
```
*
---
---

Refs #7845 - removes entity kind from broker landing page

---

app/data_migrations/correct_citizen_with_ssn.rb
app/data_migrations/correct_non_citizen_with_ssn.rb

https://devops.dchbx.org/redmine/issues/8248
4278 examples, 0 failures, 78 pendings
67 scenarios (67 passed)
1071 steps (1071 passed)
8m11.807s
---

Refs #8248. update the queries for datafix

---

app/controllers/employers/broker_agency_controller.rb
spec/controllers/employers/broker_agency_controller_spec.rb

https://devops.dchbx.org/redmine/issues/7985
Finished in 2 minutes 28.8 seconds (files took 6.69 seconds to load)
1052 examples, 0 failures, 19 pending
3925 examples, 0 failures, 77 pendings
Took 159 seconds (2:39)
6m9.021s
* 1.8.31
---
---

Hotfix 7985

---

app/invoices/invoice_helper.rb

https://devops.dchbx.org/redmine/issues/8295
```
Finished in 2 minutes 28.3 seconds (files took 7.46 seconds to load)
974 examples, 0 failures, 5 pending
3996 examples, 0 failures, 78 pendings
Took 159 seconds (2:39)
6m11.307s
```
1.8.30
---
---

Refs #8295 Populating the invoice DUE DATE for the initial ERs based on plan year calculations

---

app/controllers/insured/families_controller.rb
app/views/insured/families/_navigation.html.erb
spec/controllers/insured/families_controller_spec.rb

https://devops.dchbx.org/redmine/issues/8215
```
Finished in 2 minutes 27.5 seconds (files took 7.22 seconds to load)
1203 examples, 0 failures, 9 pending
3998 examples, 0 failures, 78 pendings
Took 158 seconds (2:38)
6m12.220s
*
---
---

Bug 8215 household members on My DC Health Link page

---

app/views/broker_agencies/profiles/_show.html.erb

* https://devops.dchbx.org/redmine/issues/7597
```
Finished in 2 minutes 34.4 seconds (files took 6.6 seconds to load)
873 examples, 0 failures, 35 pending
3998 examples, 0 failures, 78 pendings
Took 163 seconds (2:43)
6m8.912s
```
*
1.8.31
---
---

Refs 7597 Admin able to edit broker agency profiles

---

app/controllers/people_controller.rb
app/views/people/landing_pages/_personal.html.erb
app/views/shared/_contact_preferences.html.erb
spec/views/insured/families/personal.html.erb_spec.rb

* https://devops.dchbx.org/redmine/issues/7593
3771 examples, 0 failures, 73 pending
6m9.174s
*
---
---

update notice information in manage family

---

app/data_migrations/correct_enrollment_status.rb
app/models/rule_set/hbx_enrollment/individual_market_verification.rb
lib/tasks/correct_enrollments_status.rake
spec/data_migrations/correct_enrollment_status_spec.rb
spec/models/rule_set/hbx_enrollment/individual_market_verificiation_spec.rb

https://devops.dchbx.org/redmine/issues/8422
4134 examples, 0 failures, 78 pending
6m6.638s
tag: refs/tags/1.8.34
---
datafix script for enrollments

Refs #8422. fix ruleset for individual market

---

Gemfile
Gemfile.lock
app/interactors/find_or_create_insured_person.rb
app/models/factories/enrollment_factory.rb
app/models/mongoid_support/association_proxies.rb
spec/interactors/find_or_create_insured_person_spec.rb

* https://devops.dchbx.org/redmine/issues/8571
```
```
* master
---
* https://devops.dchbx.org/redmine/issues/8572
---
Remove failure caused by stale proxies or a race to save records in the
right order.
Use this opportunity to also provide some direction and and example to
begin making enrollment factory a much better place for everybody to
live and work.

Refs #8571. Fix race condition with families.

---

app/helpers/insured/group_selection_helper.rb
app/models/person.rb
spec/helpers/insured/group_selection_helper_spec.rb
spec/models/person_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/8439
Finished in 6 minutes 59 seconds (files took 14.13 seconds to load)
1228 examples, 0 failures, 8 pending
1001 steps ( 1001 passed)
19m0.536s
* 1.8.34

Hotfix 8439

---

app/views/insured/family_members/_dependent_form.html.erb
features/step_definitions/individual_steps.rb
features/step_definitions/integration_steps.rb
spec/views/insured/family_members/_dependent_form.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/4397
Finished in 11 minutes 5 seconds (files took 11.72 seconds to load)
3848 examples, 0 failures, 73 pending
7m25.499s

changed relation dropdown

---

app/data_migrations/deactivate_consumer_role.rb
lib/tasks/deactivate_consumer_role.rake
spec/data_migrations/deactivate_consumer_role_spec.rb

https://devops.dchbx.org/redmine/issues/8444
Finished in 6 minutes 30 seconds (files took 19.58 seconds to load)
1155 examples, 0 failures, 15 pending
9m54.269s
* 1.8.35

hotfix 8444

---

app/models/family.rb
spec/models/hbx_enrollment_spec.rb

https://devops.dchbx.org/redmine/issues/8149
Finished in 10 minutes 28 seconds (files took 11.03 seconds to load)
3997 examples, 0 failures, 78 pending
918 steps (918 passed)
6m54.530s
* 1.8.30

bug-8149 Hiding external enrollments from EE Dashboard

---

app/mailers/user_mailer.rb
app/models/invitation.rb
app/models/plan_year.rb
app/views/user_mailer/renewal_invitation_email.html.erb
spec/models/plan_year_spec.rb
spec/support/mail_spec_helper.rb

* https://devops.dchbx.org/redmine/issues/8490
```
Finished in 6 minutes 38 seconds (files took 8.14 seconds to load)
2124 examples, 0 failures, 44 pending
4124 examples, 0 failures, 78 pendings
7m34.451s
```
*
---
---

Updating renewal invitation email content-8490

---

app/helpers/employers/employer_helper.rb
app/models/user.rb
app/views/employers/employer_profiles/_primary_nav.html.erb
spec/views/employers/employer_profiles/_primary_nav.html.erb_spec.rb

* https://devops.dchbx.org/redmine/issues/4479
* (if more)
```
3991 examples, 0 failures, 78 pendings
5m58.875s
```
*
---
---

4479 broker families tab

---

app/controllers/users/registrations_controller.rb
app/models/user.rb
spec/models/user_spec.rb

* https://devops.dchbx.org/redmine/issues/8815
```
Finished in 6 minutes 44 seconds (files took 11.15 seconds to load)
2271 examples, 0 failures, 49 pending
4172 examples, 0 failures, 78 pendings
Took 417 seconds (6:57)
7m33.880s
```
*
---
---

Validation for Oim_id:8815

---

app/controllers/concerns/vlp_doc.rb
spec/concerns/vlp_doc.rb

* https://devops.dchbx.org/redmine/issues/7592
```
Finished in 6 minutes 46 seconds (files took 8.4 seconds to load)
2249 examples, 0 failures, 43 pending
4122 examples, 0 failures, 78 pendings
Took 422 seconds (7:02)
```
*
---
---

Hotfix-7592

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/helpers/application_helper.rb
app/models/employer_profile.rb
app/models/organization.rb
app/models/plan_year.rb
app/views/exchanges/hbx_profiles/_invoice.html.erb
spec/controllers/exchanges/hbx_profiles_controller_spec.rb

https://devops.dchbx.org/redmine/issues/7800
* (if more)
```
Finished in 4 minutes 46.3 seconds (files took 14.24 seconds to load)
1028 examples, 0 failures, 16 pending
4080 examples, 0 failure, 78 pendings
```
*
---
---

Employer invoice enhancements

---

app/models/employee_role.rb
app/views/insured/group_selection/new.html.erb
spec/models/employee_role_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/8586
Finished in 2 minutes 34.1 seconds (files took 7.49 seconds to load)
1091 examples, 0 failures, 6 pending
4188 examples, 0 failures, 78 pending
7m9.095s
*1.8.40
1) Added helper method under employee_role to identify employer dental offerings

Bug 8586 EEs of conversion ER unable to shop for dental coverage

---

lib/tasks/update_employer_status.rake

* https://devops.dchbx.org/redmine/issues/8354
```
4181 examples, 0 failures, 78 pendings
Took 173 seconds (2:53)
6m18.363s
```
*
---
---

Refs #8354: Update anytime canine employers  aasm state to enrolled

---

lib/tasks/hbx_reports/employee_terminations.rake

https://devops.dchbx.org/redmine/issues/6558
```
913 examples, 0 failures, 18 pending
3967 examples, 0 failures, 78 pendings
```
*
---
---

Refs #6558 - show terminated employees with future DOT

---

app/interactors/handle_coverage_selected.rb
app/models/consumer_role.rb
app/models/family_member.rb
app/models/hbx_enrollment.rb
app/models/hbx_enrollment_member.rb
app/models/person.rb
spec/interactors/handle_coverage_selected_spec.rb
spec/models/consumer_role_spec.rb
spec/models/family_member_spec.rb
spec/models/hbx_enrollment_member_spec.rb
spec/models/person_spec.rb

* https://devops.dchbx.org/redmine/issues/8860
* master
* There's no real way to test this functionality other than purchasing a bunch of plans in the IVL market and ensuring no crashes/errors
Call the correct set of events based on where we are in eligibility.
Also factor out some of the events to make things cleaner.

Refs #8860.  Implement correct event.

---

app/models/factories/family_enrollment_renewal_factory.rb
spec/models/factories/family_enrollment_renewal_factory_spec.rb

https://devops.dchbx.org/redmine/issues/8243
Finished in 3 minutes 0.8 seconds (files took 8.61 seconds to load)
928 examples, 0 failures, 23 pending
4232 examples, 0 failures, 78 pendings
7m50.382s
* 1.9.1
Fixed factory and added specs

Hotfix 8243  passive renewals

---

app/assets/stylesheets/globals.scss.erb
app/assets/stylesheets/modules.scss.erb
app/helpers/devise_helper.rb
app/views/devise/registrations/_registration_rules.html.erb
app/views/devise/registrations/new.html.erb
spec/views/devise/registrations/new.html.erb_spec.rb

https://devops.dchbx.org/redmine/issues/8473
```
Finished in 14 minutes 55 seconds (files took 27.8 seconds to load)
4124 examples, 16 failures, 78 pending
passed here :
Finished in 9.44 seconds (files took 7.96 seconds to load)
20 examples, 0 failures
```
*
---
---

Hotfix 8473

---

app/controllers/insured/group_selection_controller.rb
app/models/hbx_enrollment.rb
spec/controllers/insured/group_selection_controller_spec.rb

Finished in 7 minutes 35 seconds (files took 19.92 seconds to load)
1243 examples, 0 failures, 25 pending
10m7.032s
* 1.9.7

Refs #8828 Added field in hbx_enrollment

---

app/data_migrations/update_full_phone_number.rb
app/models/phone.rb
lib/tasks/migrations/update_full_phone_number.rake
spec/data_migrations/update_full_phone_number_spec.rb
spec/models/broker_role_spec.rb
spec/models/phone_spec.rb

* https://devops.dchbx.org/redmine/issues/7967
```
Finished in 6 minutes 14 seconds (files took 10.78 seconds to load)
1972 examples, 0 failures, 36 pending
3965 examples, 0 failures, 79 pendings
7m31.381s
```
* refs/tags/1.9.6)
---
---
* Reviewed and tested by Jim and Sai.  This PR can go to testing

HotFix-7967 Fix for saving full phone number

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/models/enrollment_period/special_enrollment.rb
app/models/setting.rb
app/models/special_enrollment_period.rb
app/views/exchanges/hbx_profiles/_configuration_index.html.erb
config/routes.rb
spec/controllers/exchanges/hbx_profiles_controller_spec.rb
spec/models/setting_spec.rb
spec/models/special_enrollment_period_spec.rb

* (https://devops.dchbx.org/redmine/issues/8484)
* (if more)
```
```
*
---
---

Refs #8484 - Extend IVL 15th of month deadline in August

---

app/models/plan_year.rb
spec/models/plan_year_spec.rb

https://devops.dchbx.org/redmine/issues/8311
Finished in 12 minutes 25 seconds (files took 12.2 seconds to load)
4278 examples, 0 failures, 78 pending
10m57.917s
* 1.9.8

enhancement-8311 Added MIGRATION EXPIRED state for plan year

---

app/controllers/insured/plan_shoppings_controller.rb
spec/controllers/insured/plan_shoppings_controller_spec.rb

* https://devops.dchbx.org/redmine/issues/8319
```
8m8.311s
```
*
---
---

Record termination submitted on for EE- 8319

---

app/controllers/insured/consumer_roles_controller.rb

* https://devops.dchbx.org/redmine/issues/5482
```
Finished in 7 minutes 14 seconds (files took 9.87 seconds to load)
2237 examples, 0 failures, 30 pending
4267 examples, 0 failures, 78 pendings
Took 451 seconds (7:31
```
*
---
---

Hotfix-5482

---

spec/models/enrollment_period/special_enrollment_spec.rb

* (redmine links here)
* (if more)
```
```
*
---
---

fix rspec for sep

---

app/models/broker_agency_staff_role.rb

* https://devops.dchbx.org/redmine/issues/8028
```
Finished in 2 minutes 27.2 seconds (files took 6.31 seconds to load)
1056 examples, 0 failures, 18 pending
3996 examples, 0 failures, 78 pendings
Took 155 seconds (2:35)
6m36.838s
```
*
1.8.31
---
---

Refs #8028 Approved Broker received two invitations to create account in Enroll App

---

app/models/user.rb
spec/models/user_spec.rb

https://devops.dchbx.org/redmine/issues/7569
```
Finished in 16 minutes 59 seconds (files took 28.56 seconds to load)
4134 examples, 0 failures, 78 pending
```
*
---
---

Refs #7569 Querying  select first to increase performance

---

app/assets/stylesheets/application.scss.erb
app/views/broker_agencies/profiles/_person_info_fields.html.erb
app/views/broker_agencies/profiles/edit.html.erb
app/views/shared/_broker_agency_profile_fields.html.erb
app/views/shared/_person_staff_search.html.erb
app/views/shared/organizations/_entity_name_and_type_fields.html.erb
spec/views/broker_agencies/profiles/edit.html.erb_spec.rb

* https://devops.dchbx.org/redmine/issues/9818
```
4276 examples, 0 failures, 78 pendings
Took 225 seconds (3:45)
Working on Tuesday, intermittent failures on Monday!!
Failing Scenarios:
cucumber features/brokers/create_broker_agency_profiles.feature:13 # Scenario: Primary Broker has not signed up on the HBX
58 scenarios (1 failed, 57 passed)
1001 steps (1 failed, 39 skipped, 961 passed)
on retry
80 steps (80 passed)
*
---
---

Refs #9818 broker profile edit read only dob, fein,market kind and email

---

app/controllers/employers/census_employees_controller.rb
app/models/census_employee.rb
config/routes.rb
spec/controllers/employers/census_employees_controller_spec.rb
spec/models/census_employee_spec.rb
spec/models/census_member_spec.rb
spec/models/employer_profile_spec.rb
spec/models/factories/employer_enroll_factory_spec.rb
spec/models/plan_year_spec.rb

https://devops.dchbx.org/redmine/issues/10438
4280 examples, 0 failures, 78 pendings
Took 184 seconds (3:04)
6m58.628s
*1.9.9
Added callback to set default benefit group assignment

Hot fix 10438 Assign employees to default benefit group assignment

---

lib/tasks/hbx_reports/users_account_with_no_email.rake

* https://devops.dchbx.org/redmine/issues/9688
```
```
*
---
---

report user account with no email address-9688

---

app/assets/javascripts/qle.js.erb
app/assets/stylesheets/globals.scss.erb
app/controllers/insured/families_controller.rb
app/controllers/insured/family_members_controller.rb
app/models/special_enrollment_period.rb
app/views/insured/families/_insurance_fields.html.erb
app/views/insured/families/_moving_fields.html.erb
app/views/insured/families/_qle_detail.html.erb
app/views/insured/families/_qle_moving_detail.html.erb
app/views/insured/families/_special_reasons.html.erb
app/views/insured/families/check_insurance_reason.js.erb
app/views/insured/families/check_move_reason.js.erb
app/views/insured/families/check_qle_date.js.erb
config/routes.rb
features/step_definitions/conversion_employee_steps.rb
features/step_definitions/integration_steps.rb
spec/controllers/insured/families_controller_spec.rb

https://devops.dchbx.org/redmine/issues/7966
https://devops.dchbx.org/redmine/issues/7932
Finished in 11 minutes 23 seconds (files took 9.29 seconds to load)
4174 examples, 0 failures, 78 pending
7m17.926s
tag: 1.8.37
---
---
1. No questions are displayed when a non-allowable date is entered. 
2. rspec and cucumber tests are passing.
3. The branch name is feature-7966

Feature 7966

---

app/data_migrations/set_active_benefit_group_assignment.rb
app/models/factories/census_employee_factory.rb
lib/tasks/migrations/set_active_benefit_group_assignment.rake
spec/models/factories/census_employee_factory_spec.rb

https://devops.dchbx.org/redmine/issues/8339
4296 examples, 0 failures, 78 pendings
Took 187 seconds (3:07)
7m41.850s
*1.9.13
Added rake task with some code updates for factory.
>> rake migrations:set_active_benefit_group_assignment

Bug 8339 create benefit group assignment if missing

---

app/views/shared/_my_portal_links.html.erb
spec/views/shared/my_portal_links.html.erb_spec.rb

* https://devops.dchbx.org/redmine/issues/9817
```
4285 examples, 0 failures, 78 pendings
Took 194 seconds (3:14)
6m39.693s
*
---
---

Refs #9817 multiple employee staff roles

---

app/views/insured/family_members/_dependent_form.html.erb
app/views/shared/person/_consumer_information.html.erb

https://devops.dchbx.org/redmine/issues/8420#change-87739
Finished in 11 minutes 39 seconds (files took 9.79 seconds to load)
4292 examples, 0 failures, 78 pending
tag: 1.9.12
---
---

resolved gender_error radio button

---

app/controllers/employers/plan_years_controller.rb
app/data_migrations/fix_plan_years_to_obey_minimum_open_enrollment_period.rb
app/models/plan_year.rb
config/settings.yml
spec/controllers/employers/plan_years_controller_spec.rb
spec/models/employer_profile_spec.rb
spec/models/plan_year_spec.rb

https://devops.dchbx.org/redmine/issues/10530
4296 examples, 0 failures, 78 pendings
Took 194 seconds (3:14)
7m23.802s
*1.9.14

Refs #10530 Add minimum open enrollment period validation for renewing employers

---

app/models/benefit_group.rb
app/models/plan_year.rb

https://devops.dchbx.org/redmine/issues/9846
4296 examples, 0 failures, 78 pendings
Took 195 seconds (3:15)
7m41.850s
*1.9.13
Added MongoID dynamic attributes to benefit_group model.

Refs #9846 Added MongoID Dynamic attribute to benefit group

---

app/controllers/inboxes_controller.rb
spec/controllers/broker_agencies/inboxes_controller_spec.rb
spec/controllers/employers/inboxes_controller_spec.rb
spec/controllers/exchanges/inboxes_controller_spec.rb
spec/controllers/insured/inboxes_controller_spec.rb

*https://devops.dchbx.org/redmine/issues/7520
* (if more)
```
```
*
---
---

Enhancement 7520

---

app/assets/javascripts/registration.js
app/controllers/users/registrations_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
config/initializers/devise.rb
features/general_agencies/step_definitions/ga_steps.rb
features/step_definitions/brokers_steps.rb
features/step_definitions/employer_profile_steps.rb
features/step_definitions/general_agency_steps.rb
features/step_definitions/individual_steps.rb
features/step_definitions/integration_steps.rb
spec/controllers/users/registrations_controller_spec.rb
spec/models/user_spec.rb

https://devops.dchbx.org/redmine/issues/8885
https://devops.dchbx.org/redmine/issues/10048
```
Finished in 15 minutes 5 seconds (files took 27.12 seconds to load)
4230 examples, 0 failures, 78 pending
58 scenarios (4 failed, 54 passed)
1001 steps (4 failed, 74 skipped, 923 passed)
11m44.354s
30 steps (30 passed)
0m36.262s
30 steps (30 passed)
0m28.286s
3 scenarios (3 passed)
25 steps (25 passed)
0m22.521s
80 steps (80 passed)
1m7.517s
```
*
---
---

Enhancement 8885

---

app/models/census_employee.rb
lib/tasks/check_ce_hired_date.rake
spec/models/census_employee_spec.rb

* (https://devops.dchbx.org/redmine/issues/10330)
* (if more)
```
```
*
---
---

Enhancement 10330

---

app/controllers/employers/employer_profiles_controller.rb
app/models/benefit_group.rb
app/models/benefit_group_assignment.rb
app/models/caches/request_scoped_cache.rb
app/models/hbx_enrollment.rb
app/models/plan_cost_decorator.rb
app/models/plan_year.rb
config/environments/development.rb
spec/models/employer_profile_account_spec.rb
spec/models/plan_year_spec.rb

* https://devops.dchbx.org/redmine/issues/10642
```
Finished in 4 minutes 19.8 seconds (files took 9.31 seconds to load)
1269 examples, 0 failures, 32 pending
4304 examples, 0 failures, 81 pendings
```
* master

Employer show request cache

---

app/data_migrations/create_new_initial_plan_year.rb
lib/tasks/migrations/create_new_initial_plan_year.rake

* https://devops.dchbx.org/redmine/issues/10508
Finished in 5 minutes 46 seconds (files took 11.67 seconds to load)
1339 examples, 0 failures, 31 pending
8m40.016s
* 1.9.17

data #10508 rake task to create an initial plan year

---

app/helpers/employers/employer_helper.rb
spec/models/hbx_enrollment_spec.rb

This PR involves a fix to correctness of # employees waived calculation, plus additional spec tests
* https://devops.dchbx.org/redmine/issues/8029
```
```
Since this is an API with no user-facing UI, we are not using cucumber tests, only rspec.
*
---
* https://github.com/dchbx/enroll/pull/322
---

Mobile APIs Broker App testing continued 

---

app/models/broker_agency_profile.rb
app/models/person.rb
app/views/broker_agencies/profiles/_families_table_for_broker.html.erb
app/views/employers/employer_profiles/my_account/_families.html.erb
spec/models/broker_agency_profile_spec.rb
spec/views/employers/employer_profiles/my_account/_families.html.erb_spec.rb

* https://devops.dchbx.org/redmine/issues/9831
* (if more)
```
4286 examples, 0 failures, 78 pendings
Took 184 seconds (3:04)
6m24.604s
```
* 1.9.9
---
---

Refs #9831 : Hide roster if they are terminated in broker portal

---

app/helpers/employers/employer_helper.rb
app/models/hbx_enrollment.rb
spec/helpers/employers/employer_helper_spec.rb
spec/models/hbx_enrollment_spec.rb

Additional rspec tests.
* https://devops.dchbx.org/redmine/issues/8029
```
```
Since this is an API with no user-facing UI, we are not using cucumber tests, only rspec.
*
---
* https://github.com/dchbx/enroll/pull/326
---

Mobile apis new enrolled count - specs

---

app/assets/javascripts/datatables/quotes_datatables.js.erb
app/assets/javascripts/datatables_scope_map.js.erb
app/assets/javascripts/enroll_datatables_initializer.js.erb

* https://devops.dchbx.org/redmine/issues/6197
```
4574 examples, 0 failures, 81 pendings
```
* stage
---
* https://github.com/dchbx/enroll/pull/255
---
* Jim reviewed 6197 with Phil.   Phil recommended that the best way to upgrade datatables for the Broker Quote Tool was to do commit that upgrades datatables based off of stage.   This commit upgrades datatables infrastructure.

refs #5391 fix for quote filters on stage

---

app/views/insured/consumer_roles/immigration_document_options.js.erb

https://devops.dchbx.org/redmine/issues/6629
```
Finished in 7 minutes 33 seconds (files took 29.53 seconds to load)
1080 examples, 0 failures, 13 pending
4305 examples, 0 failures, 81 pendings
58 scenarios (2 failed, 56 passed)
1001 steps (2 failed, 83 skipped, 916 passed)
12m53.447s
78 steps (78 passed)
0m43.567s
80 steps (80 passed)
0m55.002s
```
tag: 1.9.18
---

Refs #6629  vlp_questions partial_target defaults to nill

---

app/controllers/employers/employer_profiles_controller.rb
app/models/plan_year.rb
app/models/queries/employer_show_page_bill.rb
app/views/employers/employer_profiles/show.html.erb
spec/controllers/employers/employer_profiles_controller_spec.rb

* https://devops.dchbx.org/redmine/issues/10661
```
4305 examples, 0 failures, 81 pendings
Took 379 seconds (6:19)
```
* master

Employer show cost total optimization

---

app/models/plan_year.rb

* https://devops.dchbx.org/redmine/issues/10859
```
Finished in 4 minutes 23 seconds (files took 10.42 seconds to load)
1298 examples, 0 failures, 31 pending
```
* master
---
* Test with previous performance urls, as well as checking congress for a large employer example to make sure there is no time out.
* Double check in different environments to make sure premium total calculations remain correct on the home tab with the addition of the optimization/large employer filter.

Refs #10859.  Limit results for congress.

---

app/assets/javascripts/hints.js

* (https://devops.dchbx.org/redmine/issues/8334)
* (if more)
```
```
*
---
---

Refs #8334 - fixed the popover issue for document verification

---

app/views/employers/census_employees/show.html.erb
spec/views/employers/census_employees/show.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10616](https://devops.dchbx.org/redmine/issues/10616) |
| Start Date | 08/31/2016 |

10616: Hide 2015 "External" Enrollment for Conversion Employees on Census Employee Details

---

app/views/insured/family_members/_dependent_form.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10930](https://devops.dchbx.org/redmine/issues/10930) |
| Start Date | 09/20/2016 |

10930: "Manage Family" page UI update

---

lib/tasks/hbx_reports/users_account_with_no_email.rake
spec/lib/tasks/hbx_reports/users_account_with_no_email_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10869](https://devops.dchbx.org/redmine/issues/10869) |
| Start Date | 09/15/2016 |

10869: Updates: Report of IVL/EE users with email address

---

lib/tasks/fix_immigration_status.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10883](https://devops.dchbx.org/redmine/issues/10883) |
| Start Date | 09/16/2016 |

10883: Data fix to correct data impacted by 7703

---

app/controllers/insured/group_selection_controller.rb
spec/controllers/insured/group_selection_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10972](https://devops.dchbx.org/redmine/issues/10972) |
| Start Date | 09/21/2016 |

10972: IVL EnrollApp "Terminate Plan" Button Not Saving Terms

---

app/assets/javascripts/employer_profile.js
app/assets/javascripts/freebies.js.erb
app/assets/stylesheets/bootstrap_overrides.scss.erb
app/assets/stylesheets/custom.scss.erb
app/assets/stylesheets/employer.scss.erb
app/assets/stylesheets/globals.scss.erb
app/assets/stylesheets/insured.scss.erb
app/assets/stylesheets/new.scss.erb
app/helpers/application_helper.rb
app/models/plan_year.rb
app/views/employers/employer_profiles/my_account/_home_tab.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8213](https://devops.dchbx.org/redmine/issues/8213) |
| Start Date | 07/08/2016 |

8213: Fix ER eligibility target graphic

---

app/controllers/broker_agencies/profiles_controller.rb
app/policies/broker_agency_profile_policy.rb
spec/controllers/broker_agencies/profiles_controller_spec.rb
spec/policies/broker_agency_profile_policy_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10836](https://devops.dchbx.org/redmine/issues/10836) |
| Start Date | 09/14/2016 |
| Ticket Author | @jfinucane |

10836: Pundit control for broker agency profile access in the profiles_controller

---

app/controllers/insured/families_controller.rb
app/models/family.rb
spec/controllers/insured/families_controller_spec.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10873](https://devops.dchbx.org/redmine/issues/10873) |
| Start Date | 09/15/2016 |

10873: "We're sorry..." error when trying to view account

---

app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/views/insured/families/verification/_unverified_person.html.erb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [6785](https://devops.dchbx.org/redmine/issues/6785) |
| Start Date | 04/18/2016 |

6785: Wait 24 hours to display outstanding verification message

---

features/step_definitions/brokers_steps.rb
features/step_definitions/employer_profile_steps.rb
features/step_definitions/general_agency_steps.rb
features/step_definitions/individual_steps.rb
features/step_definitions/integration_steps.rb

This branch is just a placeholder. It does not correspond to a Redmine ticket yet. The goal is to make it correspond to a ticket, but ...

Jenkins Test Fixes

---

app/helpers/insured/families_helper.rb
spec/views/insured/families/_enrollment.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11106](https://devops.dchbx.org/redmine/issues/11106) |
| Start Date | 09/28/2016 |

11106: SEP ID code is "nil" 

---

app/models/employer_profile.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11133](https://devops.dchbx.org/redmine/issues/11133) |

11133: 1/1/2017 ER Renewals should not be ran on 9/30

---

app/views/insured/families/_enrollment.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11153](https://devops.dchbx.org/redmine/issues/11153) |
| Start Date | 10/02/2016 |

11153: CE’s with waived coverage are broken on the roster

---

app/views/employers/employer_profiles/my_account/_census_employees.html.erb
features/employers/roster.feature
features/step_definitions/employers_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11049](https://devops.dchbx.org/redmine/issues/11049) |
| Start Date | 09/27/2016 |

11049: Termination Date does not display properly on ER Roster

---

lib/tasks/export_employers.rake
lib/tasks/hbx_reports/employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11186](https://devops.dchbx.org/redmine/issues/11186) |
| Ticket Author | Kevin Lerer |

11186: Daily Employer Report Time-Out Issue

---

app/models/plan.rb
app/models/plan_cost_decorator.rb
spec/models/plan_cost_decorator_spec.rb
spec/models/plan_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [9768](https://devops.dchbx.org/redmine/issues/9768) |
| Start Date | 08/10/2016 |
| Ticket Author | Alix Pereira |

9768: Correct 2015 Q4 SHOP Rate for an aged 33 subscriber in the 86052DC0450002 plan

---

lib/tasks/hbx_reports/waiver_not_cancelling_passive_renewal_enrollment.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10243](https://devops.dchbx.org/redmine/issues/10243) |
| Start Date | 08/17/2016 |

10243: Waiver Report for 9/1 Employees who had Passive Renewal Enrollments

---

app/controllers/insured/families_controller.rb
app/mailers/user_mailer.rb
app/views/insured/families/inbox.html.erb
app/views/insured/families/upload_notice_form.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/views/insured/families/inbox.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [7761](https://devops.dchbx.org/redmine/issues/7761) |
| Start Date | 06/09/2016 |

7761: Upload notice for Admin

---

lib/tasks/export_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11262](https://devops.dchbx.org/redmine/issues/11262) |
| Ticket Author | Kevin Lerer |

11262: Daily Employer Report Issue

---

lib/tasks/hbx_reports/duplicate_users.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8851](https://devops.dchbx.org/redmine/issues/8851) |
| Start Date | 08/02/2016 |
| Due Date | 08/02/2016  |

8851: Duplicate username clean up

---

app/controllers/application_controller.rb
app/models/session_id_history.rb
config/application.rb
config/initializers/sesson_tagged_logger.rb
features/insured/csr.feature
features/step_definitions/integration_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11177](https://devops.dchbx.org/redmine/issues/11177) |
| Ticket Author |  Anonymous |

11177: User accountability by Session HIstory

---

app/models/employer_profile.rb
app/models/hbx_profile.rb
app/models/plan_year.rb
config/settings.yml
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11021](https://devops.dchbx.org/redmine/issues/11021) |
| Start Date | 09/26/2016 |
| Ticket Author | Carlo Kellem |

11021: Plan Year Test Scenario

---

script/write_group_xml_files.v2.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8237](https://devops.dchbx.org/redmine/issues/8237) |
| Start Date | 07/11/2016 |
| Ticket Author | @sagarlekar |

8237: v2 Group Xmls - add event types

---

app/controllers/exchanges/agents_controller.rb
app/data_migrations/change_incorrect_bookmark_url_in_consumer_role.rb
app/models/person.rb
lib/tasks/change_incorrect_bookmark_url_in_consumer_role.rake
spec/controllers/exchanges/agents_controller_spec.rb
spec/data_migrations/change_incorrect_bookmark_url_in_consumer_role_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10982](https://devops.dchbx.org/redmine/issues/10982) |
| Start Date | 09/22/2016 |

10982: Admin users landed in Household info page instead of account page

---

app/assets/stylesheets/globals.scss.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10717](https://devops.dchbx.org/redmine/issues/10717) |
| Start Date | 09/08/2016 |
| Ticket Author | Adara Beamesderfer |

10717: Pending Broker profiles incorrectly have duplicate check boxes

---

lib/tasks/hbx_reports/employee_terminations.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10761](https://devops.dchbx.org/redmine/issues/10761) |
| Start Date | 09/10/2016 |

10761: Terminations Missing from ER Roster Terminations Report

---

app/models/user.rb
spec/models/user_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10602](https://devops.dchbx.org/redmine/issues/10602) |
| Start Date | 08/30/2016 |
| Ticket Author |  Anonymous |

10602: refactor blinking spec 

---

lib/tasks/import_2017_ivl_benefit_package.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11217](https://devops.dchbx.org/redmine/issues/11217) |
| Start Date | 10/05/2016 |

11217: Benefit Package period for 2017 is missing

---

app/views/people/landing_pages/_personal.html.erb
spec/views/people/landing_pages/_peronal.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10679](https://devops.dchbx.org/redmine/issues/10679) |
| Start Date | 09/06/2016 |

10679: User account creation email associated properly to the person record. 

---

app/views/insured/group_selection/new.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10906](https://devops.dchbx.org/redmine/issues/10906) |
| Start Date | 09/19/2016 |

10906: SHOP charging premium for dependents who did not request coverage

---

lib/tasks/export_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11505](https://devops.dchbx.org/redmine/issues/11505) |
| Ticket Author | @matt--williams |

11505: Daily Employer Report Issue

---

app/views/employers/census_employees/show.html.erb
spec/views/employers/census_employees/show.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11134](https://devops.dchbx.org/redmine/issues/11134) |

11134: 12/1 Conversion Employers Missing Email Field on Employee Roster

---

app/data_migrations/triggering_auto_renewals.rb
lib/tasks/migrations/triggering_auto_renewals.rake
spec/data_migrations/triggering_auto_renewals_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11183](https://devops.dchbx.org/redmine/issues/11183) |

11183: Data FIX: 12/1 Auto renewal Issue

---

app/mailers/devise_custom_mailer.rb
config/initializers/devise.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11465](https://devops.dchbx.org/redmine/issues/11465) |

11465: "Forgot Your Password" Button Functionality

---

app/data_migrations/remove_invalid_benefit_group_assignments.rb
lib/tasks/migrations/remove_invalid_benefit_group_assignments.rake
spec/data_migrations/remove_invalid_benefit_group_assignments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11191](https://devops.dchbx.org/redmine/issues/11191) |

11191: Unable to Update Benefit Package - Benefit group assignments is invalid - Council For Christian Colleges & Universities

---

lib/tasks/enrollments_with_missing_sep_id.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11107](https://devops.dchbx.org/redmine/issues/11107) |

11107: QLE Workflow is not storing SEP ID Codes for enrollments 

---

app/views/employers/census_employees/show.html.erb
spec/views/employers/census_employees/show.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11529](https://devops.dchbx.org/redmine/issues/11529) |

11529: Address field & Dependent field is not populating if no data exists. 

---

app/data_migrations/remove_invalid_benefit_group_assignment_for_census_employee.rb
lib/tasks/migrations/remove_invalid_benefit_group_assignment_for_census_employee.rake
spec/data_migrations/remove_invalid_benefit_group_assignment_for_census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11483](https://devops.dchbx.org/redmine/issues/11483) |
| Ticket Author | Adara Beamesderfer |

11483: EE unable to proceed to plan shopping

---

lib/tasks/hbx_reports/employers_list.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8056](https://devops.dchbx.org/redmine/issues/8056) |
| Start Date | 09/20/2016 |

8056: Provide a list of employers with more than one HBX ID

---

app/data_migrations/terminate_census_employee.rb
lib/tasks/migrations/terminate_census_employee.rake
spec/data_migrations/terminate_census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11423](https://devops.dchbx.org/redmine/issues/11423) |
| Start Date | 10/05/2016 |

11423: EEs in Termination Pending State after DOT.

---

lib/tasks/plans/plan_cross_walk.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11556](https://devops.dchbx.org/redmine/issues/11556) |
| Ticket Author | @vineelsonnathi |

11556: Fix plan cross walk rake task print statement

---

app/data_migrations/group_conversion_employers_migration.rb
lib/tasks/migrations/group_conversion_employers_migration.rake
spec/data_migrations/group_conversion_employers_migration_spec.rb
spec/factories/organizations.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10924](https://devops.dchbx.org/redmine/issues/10924) |
| Start Date | 09/20/2016 |

10924: 10/1 Conversion ERs that did not migrate. 

---

app/views/events/phones/_phone.xml.haml
app/views/events/v2/employers/_owner_contact.xml.haml
app/views/events/v2/organizations/_office_location.xml.haml
app/views/events/v2/phones/_phone.xml.haml
spec/views/events/v2/organizations/_office_locations.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10778](https://devops.dchbx.org/redmine/issues/10778) |
| Start Date | 09/12/2016 |

10778: V2 XML Issues-POC and office locations

---

app/views/events/employers/updated.xml.haml
app/views/events/v2/employers/updated.xml.haml
spec/views/events/employers/updated.xml.haml_spec.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [7023](https://devops.dchbx.org/redmine/issues/7023) |
| Ticket Author | @sagarlekar |

7023: Remove Contact Duplication From Employer CV

---

app/models/census_employee.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11163](https://devops.dchbx.org/redmine/issues/11163) |

11163: "Termination Pending" status does not change to "Terminated"

---

app/controllers/application_controller.rb
features/insured/individual_sep_signup.feature
features/step_definitions/individual_steps.rb
spec/controllers/insured/families_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11166](https://devops.dchbx.org/redmine/issues/11166) |
| Start Date | 10/03/2016 |
| Ticket Author | @nisanthyaganti9 |

11166: Bookmark URL is not populating correctly for Consumer role.

---

app/controllers/employers/census_employees_controller.rb
app/models/hbx_enrollment.rb
spec/controllers/employers/census_employees_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10691](https://devops.dchbx.org/redmine/issues/10691) |
| Start Date | 09/07/2016 |

10691: Census EE Show Page issue

---

app/models/census_member.rb
app/views/employers/census_employees/_email_fields.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11695](https://devops.dchbx.org/redmine/issues/11695) |

11695: Update email validation method

---

features/general_agencies/step_definitions/ga_steps.rb
features/hbx/step_definitions/announcement_step.rb
features/step_definitions/brokers_steps.rb
features/step_definitions/individual_steps.rb
features/step_definitions/integration_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

CUCUMBERRRRRRRRR

---

lib/tasks/hbx_reports/employee_terminations.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11676](https://devops.dchbx.org/redmine/issues/11676) |
| Ticket Author | @vineelsonnathi |

11676: Revert 10761

---

db/seedfiles/plans-sbcs.csv
plans-sbcs.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11646](https://devops.dchbx.org/redmine/issues/11646) |
| Ticket Author | @vineelsonnathi |

11646: Fix Kaiser sbc mapping

---

Gemfile.lock

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11714](https://devops.dchbx.org/redmine/issues/11714) |

11714: update poltergiest

---

app/views/devise/registrations/new.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11487](https://devops.dchbx.org/redmine/issues/11487) |

11487: Account Setup Page - Typo in Password Rules

---

app/data_migrations/change_state_for_passive_enrollment.rb
app/models/factories/census_employee_factory.rb
lib/tasks/migrations/change_state_for_passive_enrollment.rake
spec/data_migrations/change_state_for_passive_enrollment_spec.rb
spec/models/factories/census_employee_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8887](https://devops.dchbx.org/redmine/issues/8887) |
| Start Date | 08/03/2016 |

8887: At Effective Date Employee's Enrollments are Being Transition Incorrectly when there are 2 valid policies

---

app/models/address.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8214](https://devops.dchbx.org/redmine/issues/8214) |
| Start Date | 07/08/2016 |

8214: EEs Blocked on Contact Information Page

---

app/data_migrations/change_employer_contributions.rb
app/data_migrations/remove_benefit_package.rb
lib/tasks/migrations/change_employer_contributions.rake
lib/tasks/migrations/remove_benefit_package.rake
spec/data_migrations/change_employer_contributions_spec.rb
spec/data_migrations/remove_benefit_package_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11108](https://devops.dchbx.org/redmine/issues/11108) |
| Start Date | 09/28/2016 |
| Ticket Author | Adara Beamesderfer |

11108: ER Plan Offering Change & Group XML Transmission - Update Benefit Packages for 9/1 Conversion ER- International Committee Of The Red Cross

---

app/models/census_employee.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11733](https://devops.dchbx.org/redmine/issues/11733) |

11733: I can't remove the ssns of census employee dependents even if the employee isn't linked

---

app/views/shared/_census_employee_fields.html.erb
spec/views/employers/census_employees/show.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11187](https://devops.dchbx.org/redmine/issues/11187) |
| Ticket Author | J'Aimee Louis |

11187: ER Roster - Missing Benefit Package drop-down menu on employee census detail page

---

lib/tasks/aptc_csr_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11690](https://devops.dchbx.org/redmine/issues/11690) |
| Start Date | 10/25/2016 |
| Due Date | 10/26/2016  |

11690: APTC/CSR Report from EA

---

app/models/employee_role.rb
app/views/insured/employee_roles/_employers.html.erb
app/views/shared/_employer.html.erb
spec/models/employee_role_spec.rb

| Field | Value |
| --- | --- |
| Redmine Ticket Number | [10582](https://devops.dchbx.org/redmine/issues/10582) |
| Start Date | 08/29/2016 |
| Due Date | n/a |

10582: Existing ERs without active plan years block existing EEs from My Account Access.

---

app/models/person.rb
spec/factories/employer_staff_role.rb
spec/models/person_spec.rb
spec/views/shared/portal_title_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11786](https://devops.dchbx.org/redmine/issues/11786) |

11786: Record lookup in Enroll triggers update in Glue

---

app/controllers/insured/plan_shoppings_controller.rb
app/models/hbx_enrollment.rb
spec/controllers/insured/plan_shoppings_controller_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11459](https://devops.dchbx.org/redmine/issues/11459) |

11459: Dental coverage is being automatically waived when Health coverage is waived

---

app/data_migrations/change_enrollment_effective_on_date.rb
lib/tasks/migrations/change_enrollment_effective_on_date.rake
spec/data_migrations/change_enrollment_effective_on_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11288](https://devops.dchbx.org/redmine/issues/11288) |
| Ticket Author | Baldeep Dhaliwal |

11288: EE of 12/1 Initial Group Received a 11/1 Start Date 

---

app/helpers/insured/families_helper.rb
spec/helpers/insured/families_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11864](https://devops.dchbx.org/redmine/issues/11864) |

11864: 2017 IVL Auto-Renewal state not displayed

---

app/models/user.rb
spec/models/user_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10871](https://devops.dchbx.org/redmine/issues/10871) |
| Start Date | 09/15/2016 |
| Ticket Author |  Anonymous |

10871: pass generation edge case

---

app/controllers/employers/census_employees_controller.rb
app/models/census_employee.rb
app/models/hbx_enrollment.rb
spec/controllers/employers/census_employees_controller_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10965](https://devops.dchbx.org/redmine/issues/10965) |

10965: Employees with waived coverage are not properly terminated

---

app/models/census_employee.rb
spec/models/census_employee_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

Refs #8333 #11733 using unset for setting field value as nil

---

app/invoices/employer_invoice.rb
app/models/organization.rb
app/views/exchanges/hbx_profiles/_invoice.html.erb
spec/models/organization_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11647](https://devops.dchbx.org/redmine/issues/11647) |

11647: Automate invoice to print house

---

app/models/hbx_enrollment.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [7411](https://devops.dchbx.org/redmine/issues/7411) |
| Start Date | 05/13/2016 |

7411: Employee Enrollment Tile – Termination Date Incorrectly Reflects 14-day IVL Marketplace Rule

---

app/controllers/employers/census_employees_controller.rb
spec/controllers/employers/census_employees_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11448](https://devops.dchbx.org/redmine/issues/11448) |

11448: Hide Canceled enrollments from Census  detail "Past Enrollments"

---

app/views/employers/employer_profiles/my_account/_families.html.erb
app/views/employers/employer_profiles/show_profile.html.erb
features/step_definitions/brokers_steps.rb
spec/views/employers/employer_profiles/_show_profile.html.erb_spec.rb
spec/views/employers/employer_profiles/my_account/_families.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [6941](https://devops.dchbx.org/redmine/issues/6941) |
| Start Date | 04/26/2016 |

6941: Broker ER Families Tab - Missing Left Nav Menu, Reformat EE list to look/function more like regular Families tab

---

app/controllers/broker_agencies/profiles_controller.rb
app/views/broker_agencies/profiles/_person_info_fields.html.erb
spec/controllers/broker_agencies/profiles_controller_spec.rb
spec/views/broker_agencies/profiles/edit.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11130](https://devops.dchbx.org/redmine/issues/11130) |
| Ticket Author | Adara Beamesderfer |

11130: Unable to edit broker information when clicking "edit broker agency profile"

---

app/models/employer_profile.rb
script/trigger_renewal_plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12027](https://devops.dchbx.org/redmine/issues/12027) |

12027: Enable Plan Year Renewal Trigger

---

app/data_migrations/extending_open_enrollment_end_date_for_employers.rb
config/settings.yml
lib/tasks/migrations/extending_open_enrollment_end_date_for_employers.rake
spec/data_migrations/extending_open_enrollment_end_date_for_employers_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11906](https://devops.dchbx.org/redmine/issues/11906) |

11906: Extend Open Enrollment End Date for 12/1 conversion and renewal ERs

---

app/data_migrations/update_csr_plan_names.rb
db/seedfiles/plans-sbcs.csv
lib/object_builders/qhp_builder.rb
lib/tasks/update_csr_plan_names.rake
plans-sbcs.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12002](https://devops.dchbx.org/redmine/issues/12002) |

12002: 2017 SBC file name updates for IVL CSR variations

---

app/controllers/insured/plan_shoppings_controller.rb
app/views/insured/plan_shoppings/_plan_details.html.erb
app/views/insured/plan_shoppings/_plan_filters.html.erb
spec/controllers/insured/plan_shoppings_controller_spec.rb
spec/views/insured/plan_shoppings/_plan_details.html.erb_spec.rb
spec/views/insured/plan_shoppings/plan_filters.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11912](https://devops.dchbx.org/redmine/issues/11912) |

11912: EE with IVL Role Receives Cost Sharing Reductions

---

app/models/hbx_enrollment.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12058](https://devops.dchbx.org/redmine/issues/12058) |

12058: Enrollments in the Auto-renewal state are not canceled by waiver submission

---

app/controllers/employers/plan_years_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12034](https://devops.dchbx.org/redmine/issues/12034) |

12034: remove deprecated instance variables with hard coded dates

---

config/settings.yml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12056](https://devops.dchbx.org/redmine/issues/12056) |
| Start Date | 11/16/2016 |

12056: Revert OE extension settings

---

script/actively_renewed_ee_renewal_cancellation.rb
script/actively_waived_ee_enrollment_cancellation.rb
script/ee_with_no_coverage_renewal_cancellation.rb
script/terminated_employee_renewals_cancellation.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12166](https://devops.dchbx.org/redmine/issues/12166) |

12166: 12/1 scripts to be ran 

---

app/controllers/api/v1/mobile_api_controller.rb
lib/api/v1/mobile/employer.rb
lib/api/v1/mobile/plan_year.rb
spec/lib/api/v1/mobile_api_employer_spec.rb

- Fixed bug https://dchealthlink.kanbanize.com/ctrl_board/15/cards/4185.
* 8029
Since this is an API with no user-facing UI, we are not using cucumber tests, only RSpec.
```
bundle exec rake spec
```
Finished in 9 minutes 57 seconds (files took 7.16 seconds to load)
4639 examples, 0 failures, 83 pending
* https://github.com/dchbx/enroll/pull/587
---

"Mobile APIs: 'Fix "undefined method `benefit_groups'  error (8029)"

---

app/controllers/employers/census_employees_controller.rb
app/models/census_member.rb
spec/controllers/employers/census_employees_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11704](https://devops.dchbx.org/redmine/issues/11704) |

11704: Unable to delete email address in census roster

---

app/views/insured/group_selection/new.html.erb
app/views/insured/plan_shoppings/show.html.erb
app/views/shared/_qle_progress.html.haml
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11806](https://devops.dchbx.org/redmine/issues/11806) |

11806: Dual role - Waive Coverage Failed Issue for EE

---

app/helpers/employers/premium_statement_helper.rb
spec/factories/organizations.rb
spec/factories/plan_years.rb
spec/helpers/employers/premium_statement_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10710](https://devops.dchbx.org/redmine/issues/10710) |
| Start Date | 09/07/2016 |

10710: Enrollment Report for Initial Groups Looks One Month Out Rather than the Effective Date

---

app/controllers/insured/group_selection_controller.rb
app/models/hbx_enrollment.rb
features/step_definitions/individual_steps.rb
spec/controllers/insured/group_selection_controller_spec.rb
spec/factories/benefit_coverage_periods.rb
spec/factories/benefit_packages.rb
spec/factories/benefit_sponsorships.rb
spec/factories/hbx_profiles.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12263](https://devops.dchbx.org/redmine/issues/12263) |

12263: fix group selection insured rule benefit package selection for IVL 

---

app/data_migrations/change_plan_year_effective_date.rb
lib/tasks/migrations/change_plan_year_effective_date.rake
spec/data_migrations/change_plan_year_effective_date_spec.rb
spec/factories/plan_years.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12206](https://devops.dchbx.org/redmine/issues/12206) |

12206: Force Publish Plan Year 12/1 - Vocational Assessment Services, Inc

---

script/list_of_all_assisters_and_cac.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11927](https://devops.dchbx.org/redmine/issues/11927) |
| Ticket Author | Shayla Hamlin |

11927: Need A Comprehensive List of All Assisters and CACs

---

app/data_migrations/remove_invalid_benefit_group_assignments_for_employer.rb
lib/tasks/migrations/remove_invalid_benefit_group_assignments_for_employer.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12127](https://devops.dchbx.org/redmine/issues/12127) |

12127: Invalid Benefit Group Assignment Conversion issue-

---

app/views/employers/census_employees/_address_fields.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12177](https://devops.dchbx.org/redmine/issues/12177) |

12177: EE census record Address field

---

app/controllers/insured/group_selection_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12401](https://devops.dchbx.org/redmine/issues/12401) |

12401: Users with Consumer and Employee role receive error after clicking shop for plans. 

---

app/views/insured/group_selection/new.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12304](https://devops.dchbx.org/redmine/issues/12304) |
| Ticket Author | Amy Calderon |

12304: "We're Sorry" error upon attempting to Shop for plans

---

app/data_migrations/change_plan_year_effective_date.rb
lib/tasks/migrations/change_plan_year_effective_date.rake
spec/data_migrations/change_plan_year_effective_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12298](https://devops.dchbx.org/redmine/issues/12298) |

12298: Force Publish Plan Year 12/1 - Icon, Inc

---

app/helpers/portal_header_helper.rb
spec/helpers/portal_header_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12070](https://devops.dchbx.org/redmine/issues/12070) |

12070: ER/EE Header Text Issue

---

lib/tasks/nfp.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12555](https://devops.dchbx.org/redmine/issues/12555) |

12555: Load November NFP statements/Invoice

---

app/models/broker_role.rb
spec/models/broker_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12398](https://devops.dchbx.org/redmine/issues/12398) |

12398: Recertify Broker

---

app/views/exchanges/hbx_profiles/assister_index.js.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11660](https://devops.dchbx.org/redmine/issues/11660) |

11660: Assister Listing does not populate.

---

app/views/events/v2/employers/_elected_plan.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12657](https://devops.dchbx.org/redmine/issues/12657) |

12657: Aetna Group XML issue

---

app/models/factories/enrollment_factory.rb
spec/models/factories/enrollment_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12487](https://devops.dchbx.org/redmine/issues/12487) |
| Peer Review Story Points | 1.5 |

12487: EE Receives "Were Sorry Error" upon login and Unable to update roster entry - 182965

---

app/models/person.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11636](https://devops.dchbx.org/redmine/issues/11636) |

11636: Cannot remove POC if they have already been removed

---

app/data_migrations/adding_employee_role.rb
lib/tasks/migrations/adding_employee_role.rake
spec/data_migrations/adding_employee_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12630](https://devops.dchbx.org/redmine/issues/12630) |

12630: Unable to Link to employer-  163882

---

app/models/hbx_enrollment.rb
app/views/insured/plan_shoppings/_plan_filters.html.erb
spec/models/hbx_enrollment_spec.rb
spec/views/insured/plan_shoppings/plan_filters.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12686](https://devops.dchbx.org/redmine/issues/12686) |

12686: Plan Match links in 2017 plan shopping need to be updated

---

app/notices/ivl_notices/consumer_notice.rb
app/views/notices/shared/footer.html.erb
script/backlog_verifications_generator.rb
script/verifications_csv_export.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12490](https://devops.dchbx.org/redmine/issues/12490) |

12490: Backlog verification notice

---

app/models/hbx_enrollment.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12573](https://devops.dchbx.org/redmine/issues/12573) |

12573: IVL Plan Confirmation - "We're Sorry But Something Went Wrong" Error Message

---

app/views/employers/employer_profiles/my_account/_benefits.html.erb
features/employers/employer_claim_code.feature

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12826](https://devops.dchbx.org/redmine/issues/12826) |

12826: ER Portal - Claim Quote button is live (but broker quoting tool is not supposed to be live)

---

app/invoices/invoice_helper.rb
app/models/address.rb
spec/invoices/invoice_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12537](https://devops.dchbx.org/redmine/issues/12537) |

12537: EA-generated invoices are not addressed to the employer's mailing address

---

script/update_eligibility.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11879](https://devops.dchbx.org/redmine/issues/11879) |
| Peer Review Story Points | 1.5 |

11879: FA Renewals

---

lib/tasks/hbx_reports/census_ee_with_no_address.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12176](https://devops.dchbx.org/redmine/issues/12176) |

12176: EE census record without address

---

script/users_unable_be_updated_by_email_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11554](https://devops.dchbx.org/redmine/issues/11554) |

11554: Users unable be updated with email

---

app/data_migrations/unset_employee_role_id.rb
lib/tasks/migrations/unset_employee_role_id.rake
spec/data_migrations/unset_employee_role_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11549](https://devops.dchbx.org/redmine/issues/11549) |

11549: Unable to Access user account- "We're sorry, but something went wrong"

---

app/models/census_employee.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12756](https://devops.dchbx.org/redmine/issues/12756) |

12756: "Terminated Pending" Status not changing to "terminated" for ER - Technology Transition Corp

---

app/models/effective/datatables/family_data_table.rb
features/admin/paper_phone.feature
features/step_definitions/admin_paper_phone.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12845](https://devops.dchbx.org/redmine/issues/12845) |

12845: Continue application functionality in data tables

---

spec/models/hbx_enrollment_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refactor spec

---

app/models/factories/family_enrollment_renewal_factory.rb
spec/models/factories/family_enrollment_renewal_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [9872](https://devops.dchbx.org/redmine/issues/9872) |
| Start Date | 08/15/2016 |

9872: Employees able to enroll family members when Employer does not offer family coverage

---

app/models/person.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12928](https://devops.dchbx.org/redmine/issues/12928) |

12928: Correct Index reference in Person model 

---

app/views/employers/census_employees/show.html.erb
features/employers/roster.feature
features/step_definitions/employers_steps.rb
spec/views/employers/census_employees/show.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12579](https://devops.dchbx.org/redmine/issues/12579) |

12579: Hide Address field in EE census detail page

---

app/notices/ivl_notices/no_appeal_variable_ivl_renewal_notice.rb
app/views/layouts/pdf_notice.html.erb
app/views/notices/ivl/IVLR10_AQHP_final_renewal.html.erb
app/views/notices/ivl/IVLR9_UQHP_final_renewal_december.html.erb
app/views/notices/shared/_table.html.erb
db/seedfiles/notice_triggers_seed.rb
script/ivlr9_10_reports_enroll_version.rb
script/ivlr_9_10_notice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12912](https://devops.dchbx.org/redmine/issues/12912) |

12912: Generate IVL_9_10 notices

---

app/models/subscribers/family_application_completed.rb
spec/models/subscribers/family_application_completed_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [4245](https://devops.dchbx.org/redmine/issues/4245) |

4245: Assisted - Relationships are not populating correctly in EA from Curam 

---

app/data_migrations/add_coverage_household_member.rb
lib/tasks/migrations/add_coverage_household_member.rake
spec/data_migrations/add_coverage_household_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12474](https://devops.dchbx.org/redmine/issues/12474) |

12474: Plan Shopping Includes 0 Members for Linked EE - The William Calomiris Company LLC

---

app/controllers/exchanges/broker_applicants_controller.rb
app/views/shared/brokers/_applicant.html.erb
spec/controllers/exchanges/broker_applicants_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12634](https://devops.dchbx.org/redmine/issues/12634) |

12634: Broker-UI Decertify/Recertify

---

app/models/hbx_enrollment.rb
app/views/events/employers/updated.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13040](https://devops.dchbx.org/redmine/issues/13040) |

13040: BrokerAgencyAccount has a default scope which hides data

---

app/views/events/hbx_enrollment/_policy.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13006](https://devops.dchbx.org/redmine/issues/13006) |

13006: Update Enroll Enrollment Events to Use Hbx Assigned Employer ID

---

app/views/employers/employer_profiles/_enrollment_report_widget.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11998](https://devops.dchbx.org/redmine/issues/11998) |
| Start Date | 11/16/2016 |

11998: ER portal - display issue on home page (broker tile)

---

app/data_migrations/remove_duplicate_census_dependents.rb
lib/tasks/remove_duplicate_census_dependents.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12659](https://devops.dchbx.org/redmine/issues/12659) |
| Ticket Author | J'Aimee Louis |

12659: Unable to Link to employer - 1054627

---

app/views/events/v2/organizations/_office_location.xml.haml
app/views/events/v2/phones/_phone.xml.haml
spec/views/events/v2/organizations/_office_locations.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13050](https://devops.dchbx.org/redmine/issues/13050) |

13050: Aetna group XMLs without contact numbers

---

app/controllers/saml_controller.rb
spec/controllers/saml_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13149](https://devops.dchbx.org/redmine/issues/13149) |

13149: saml new user with no email attribute save problem

---

script/action_on_headless_users.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11321](https://devops.dchbx.org/redmine/issues/11321) |

11321: Delete duplicate headless users

---

app/models/family.rb
app/models/hbx_enrollment.rb
spec/models/census_employee_spec.rb
spec/models/employer_profile_account_spec.rb
spec/models/family_spec.rb
spec/models/plan_year_spec.rb
spec/models/time_keeper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12898](https://devops.dchbx.org/redmine/issues/12898) |

12898: 2015 Enrollments neet to transition to coverage_expired

---

app/controllers/employers/employer_profiles_controller.rb
app/models/census_employee.rb
app/views/employers/employer_profiles/my_account/_census_employees.html.erb
spec/controllers/employers/employer_profiles_controller_spec.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [3443](https://devops.dchbx.org/redmine/issues/3443) |
| Start Date | 10/26/2015 |

3443: ER Roster Search - Add Search by SSN

---

app/models/consumer_role.rb
app/models/employee_role.rb
app/views/shared/_contact_preferences.html.erb
spec/views/insured/families/personal.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [3764](https://devops.dchbx.org/redmine/issues/3764) |
| Start Date | 11/04/2015 |

3764: EE Portal - Update Default communications preference

---

app/data_migrations/update_carrier_appointments.rb
lib/tasks/update_carrier_appointments.rake
spec/data_migrations/update_carrier_appointments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12635](https://devops.dchbx.org/redmine/issues/12635) |

12635: Pending Broker Applications-check boxes are doubling when updated

---

app/assets/javascripts/application.js.erb
app/views/employers/employer_profiles/_upload_employees.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8906](https://devops.dchbx.org/redmine/issues/8906) |
| Start Date | 08/04/2016 |

8906: ER Portal - Typo and "Fake Path" on Roster Upload Page

---

app/models/plan_year.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13193](https://devops.dchbx.org/redmine/issues/13193) |

13193: Enrollment report shows only one plan selection for EEs

---

script/extract_users_with_internal_roles.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13022](https://devops.dchbx.org/redmine/issues/13022) |

13022: Create a report of all users in EA with internal roles

---

app/helpers/insured/families_helper.rb
spec/helpers/insured/families_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12705](https://devops.dchbx.org/redmine/issues/12705) |

12705: IVL enrollments in 2016 dentegra plan terminated- status in enrollment tile missing

---

db/seedfiles/plans-sbcs.csv
plans-sbcs.csv

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13296](https://devops.dchbx.org/redmine/issues/13296) |
| Ticket Author | Kenneth Taylor |

13296: SBC Update Needed for Carefirst Dental (SHOP & IVL)

---

app/notices/ivl_notices/final_catastrophic_plan_notice.rb
app/views/notices/ivl/final_catastrophic_plan_letter.html.erb
db/seedfiles/notice_triggers_seed.rb
script/final_catastrophic_notice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13148](https://devops.dchbx.org/redmine/issues/13148) |

13148: Notice to '16 catastrophic plan enrollees

---

app/controllers/insured/families_controller.rb
app/helpers/insured/families_helper.rb
app/models/benefit_coverage_period.rb
app/models/family.rb
app/models/hbx_enrollment.rb
app/views/insured/families/_enrollment.html.erb
app/views/insured/families/_enrollment_progress.html.erb
app/views/insured/families/home.html.erb
features/step_definitions/renewal_steps.rb
spec/controllers/insured/families_controller_spec.rb
spec/views/insured/families/_enrollment.html.erb_spec.rb
spec/views/insured/families/_enrollment_progress.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13269](https://devops.dchbx.org/redmine/issues/13269) |

13269: Enroll App hbx_enrollments in enrollment_expired state should be visible in customer 'My Account' UI

---

app/models/family.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13270](https://devops.dchbx.org/redmine/issues/13270) |

13270: IVL enrollment_expired should include all enrollments within the calendar year

---

app/models/family.rb
app/models/hbx_enrollment.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13528](https://devops.dchbx.org/redmine/issues/13528) |

13528: Automate 2017 IVL Enrollment Transition from Auto-renewing state 

---

app/assets/javascripts/application.js.erb
app/assets/javascripts/dob_validation.js
vendor/assets/javascripts/jq_datepicker.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8414](https://devops.dchbx.org/redmine/issues/8414) |

8414: DOB Calendar on IVL intake initializes with 'future' months disabled

---

app/views/employers/premium_statements/_benefit_line_item_detail.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13568](https://devops.dchbx.org/redmine/issues/13568) |

13568: Update Text On Enrollment Report

---

app/controllers/saml_controller.rb
spec/controllers/saml_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13222](https://devops.dchbx.org/redmine/issues/13222) |

13222: saml new user headless collision problem

---

app/reports/hbx_reports/destroy_duplicates_without_enr.rb
lib/tasks/hbx_reports/destroy_duplicates_without_enr.rake
spec/reports/hbx_reports/destroy_duplicates_without_enr_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13009](https://devops.dchbx.org/redmine/issues/13009) |

13009: Clean up for duplicate family members in EA

---

app/views/insured/families/_shop_for_plans_widget.html.erb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13747](https://devops.dchbx.org/redmine/issues/13747) |

13747: Modification needed to IVL plan shopping message

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13720](https://devops.dchbx.org/redmine/issues/13720) |

13720: Consumer unable log in to her consumer account--please fix

---

spec/data_migrations/group_conversion_employers_migration_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fixing failing specs

---

app/views/insured/families/_shop_for_plans_widget.html.erb
spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13184](https://devops.dchbx.org/redmine/issues/13184) |

13184: Admin Consumer Role Creation for User with EE role only

---

app/models/census_employee_import.rb
spec/models/census_employee_import_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11626](https://devops.dchbx.org/redmine/issues/11626) |

11626: Roster Upload- Addresses are not being uploaded 

---

app/views/notices/ivl/IVLR10_AQHP_final_renewal.html.erb
app/views/notices/ivl/IVLR9_UQHP_final_renewal_december.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13258](https://devops.dchbx.org/redmine/issues/13258) |

13258: Generate remaining IVL 9/10 notice's

---

app/controllers/insured/families_controller.rb
features/hbx/step_definitions/announcement_step.rb
features/step_definitions/employers_steps.rb
spec/controllers/insured/families_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12877](https://devops.dchbx.org/redmine/issues/12877) |

12877: Users able to bypass RIDP by changing URL

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/views/exchanges/hbx_profiles/_edit_enrollment.html.erb
spec/controllers/exchanges/hbx_profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13305](https://devops.dchbx.org/redmine/issues/13305) |

13305: Cannot update DOB if no SSN present

---

app/views/insured/employee_roles/_employment_relationships.html.haml
app/views/shared/_employer.html.erb
features/employee/conversion_employee.feature
features/step_definitions/conversion_employee_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13543](https://devops.dchbx.org/redmine/issues/13543) |

13543: Remove Effective Date Text When EE Person Matches

---

app/policies/census_employee_policy.rb
spec/policies/census_employee_policy_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13141](https://devops.dchbx.org/redmine/issues/13141) |

13141: Brokers/GAs Unable to Update Roster Information 

---

app/data_migrations/change_applied_aptc_amount.rb
app/data_migrations/reset_e_case_id.rb
app/views/insured/group_selection/new.html.erb
lib/tasks/migrations/change_applied_aptc_amount.rake
lib/tasks/migrations/reset_e_case_id.rake
spec/data_migrations/change_applied_aptc_amount_spec.rb
spec/data_migrations/reset_e_case_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12486](https://devops.dchbx.org/redmine/issues/12486) |

12486: >100% APTC applied

---

app/data_migrations/fix_hub_verified_consumer.rb
app/models/hbx_enrollment.rb
lib/tasks/migrations/fix_hub_verified_consumer.rake
spec/data_migrations/fix_hub_verified_consumer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12646](https://devops.dchbx.org/redmine/issues/12646) |

12646: Data fix for outstanding verification case

---

app/helpers/application_helper.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13431](https://devops.dchbx.org/redmine/issues/13431) |

13431: Spelling Correction Needed on ER Dashboard Progress Bar

---

app/data_migrations/correct_invalid_benefit_group_assignments_for_employer.rb
lib/tasks/migrations/correct_invalid_benefit_group_assignments_for_employer.rake
spec/data_migrations/correct_invalid_benefit_group_assignments_for_employer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13836](https://devops.dchbx.org/redmine/issues/13836) |

13836: Master Ticket for Remaining 'Invalid Benefit Group' clean up 

---

app/models/subscribers/iam_account_creation.rb
app/models/user.rb
config/application.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13581](https://devops.dchbx.org/redmine/issues/13581) |

13581: Change to EA for account creation/updates in ForgeRock

---

app/models/family.rb
spec/models/queries/family_datatable_query_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11856](https://devops.dchbx.org/redmine/issues/11856) |

11856: Dual user not displaying for IVL

---

app/views/insured/families/_shop_for_plans_widget.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13724](https://devops.dchbx.org/redmine/issues/13724) |

13724: Shop with existing SEP Flow

---

app/controllers/exchanges/agents_controller.rb
app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/families_controller.rb
app/models/person.rb
spec/controllers/exchanges/agents_controller_spec.rb
spec/controllers/insured/consumer_roles_controller_spec.rb
spec/controllers/insured/families_controller_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13931](https://devops.dchbx.org/redmine/issues/13931) |

13931: Paper application flow blocked

---

app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [4958](https://devops.dchbx.org/redmine/issues/4958) |
| App-Dev Road Map # | 1.3.6.4 |

4958: HBX-Admin tool to enter APTC/CSR 

---

app/data_migrations/correct_invalid_benefit_group_assignments_for_employer.rb
lib/tasks/migrations/correct_invalid_benefit_group_assignments_for_employer.rake
spec/data_migrations/correct_invalid_benefit_group_assignments_for_employer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13719](https://devops.dchbx.org/redmine/issues/13719) |

13719: Effective Date Update for Conversion Group -  NORTHWEST SETTLEMENT HOUSE

---

script/change_enrollment_statuses.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12907](https://devops.dchbx.org/redmine/issues/12907) |

12907: Employer Unable to View Employee Census Details from Roster (Reverse Data Migration from Glue Needed)- Capitol Immigration Law Group PLLC

---

app/models/forms/consumer_candidate.rb
spec/factories/people.rb
spec/models/forms/consumer_candidate_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14130](https://devops.dchbx.org/redmine/issues/14130) |

14130:  Consumers is blocked when they try to register without SSN

---

app/views/broker_agencies/profiles/_menu.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11234](https://devops.dchbx.org/redmine/issues/11234) |
| Start Date | 10/05/2016 |

11234: Broker Dashboard needs Alignment

---

app/models/benefit_group.rb
app/models/census_employee.rb
spec/controllers/employers/employer_profiles_controller_spec.rb
spec/models/benefit_group_spec.rb
spec/models/census_employee_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13818](https://devops.dchbx.org/redmine/issues/13818) |

13818: Issues in Census Employee Setting Default Benefit Group Assignment

---

app/helpers/employers/employer_helper.rb
app/views/employers/census_employees/show.html.erb
spec/helpers/employers/employer_helper_spec.rb
spec/views/employers/census_employees/show.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12460](https://devops.dchbx.org/redmine/issues/12460) |

12460: Census detail page of Rehired EE

---

app/views/insured/plan_shoppings/_plan_filters.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14177](https://devops.dchbx.org/redmine/issues/14177) |

14177: Update the order of metal level display in plan shopping

---

script/assign_missing_benefit_groups.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14044](https://devops.dchbx.org/redmine/issues/14044) |

14044: Data Fix-CV2 Errors 

---

app/helpers/insured/employee_roles_helper.rb
app/models/benefit_coverage_period.rb
app/models/insured_eligible_for_benefit_rule.rb
app/views/insured/group_selection/_coverage_household.html.erb
app/views/insured/group_selection/_ivl_coverage_household.html.erb
app/views/shared/_relationship_benefit_fields.html.erb
spec/factories/families.rb
spec/helpers/insured/employee_roles_helper_spec.rb
spec/models/benefit_coverage_period_spec.rb
spec/models/insured_eligible_for_benefit_rule_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12463](https://devops.dchbx.org/redmine/issues/12463) |

12463: New Business logic for Age 26 eligibility

---

script/actions_on_plan_year_groups.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12834](https://devops.dchbx.org/redmine/issues/12834) |

12834: 1-1-2017 Groups that did not re-new or migrate

---

app/data_migrations/fix_incorrect_effective_dates.rb
lib/tasks/migrations/fix_conversion_effective_dates.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14313](https://devops.dchbx.org/redmine/issues/14313) |

14313: Autowaivers are generated instead of auto renewal for 5/1 conversion groups

---

app/invoices/invoice_helper.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13791](https://devops.dchbx.org/redmine/issues/13791) |

13791: Remove last 4 of SSN from invoice

---

app/data_migrations/fix_invalid_relationship_benefit_in_plan_year.rb
lib/tasks/migrations/fix_child_over_26_relationship_benefit_in_plan_year.rake
spec/data_migrations/fix_invalid_relationship_benefit_in_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13151](https://devops.dchbx.org/redmine/issues/13151) |

13151: Child Over 26 eligbility for SHOP

---

app/views/insured/plan_shoppings/_plan_details.html.erb
spec/views/insured/plan_shoppings/_plan_details.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [3333](https://devops.dchbx.org/redmine/issues/3333) |
| Start Date | 10/21/2015 |
| Ticket Author | Simon Henry |

3333: Deductible not showing Family deductible

---

app/models/hbx_enrollment.rb
app/models/household.rb
app/models/importers/conversion_employee_policy.rb
app/models/importers/conversion_employee_policy_delete.rb
app/models/importers/conversion_employer_plan_year.rb
app/models/importers/conversion_employer_update.rb
app/models/plan_year.rb
script/import_conversion_employee_policies.rb
script/import_conversion_employees.rb
script/import_conversion_employer_plan_years.rb
script/import_conversion_employers.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14189](https://devops.dchbx.org/redmine/issues/14189) |
| Ticket Author | Emma Chafetz |

14189: 6/1 Conversion Data

---

app/data_migrations/change_plan_year_effective_date.rb
app/data_migrations/correct_invalid_benefit_group_assignments_for_employer.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14419](https://devops.dchbx.org/redmine/issues/14419) |

14419: Updated Effective Date - El Don, LLC

---

app/helpers/events_helper.rb
spec/helpers/events_helper_spec.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14446](https://devops.dchbx.org/redmine/issues/14446) |

14446: Conversion employers are being included in XML sent to carriers

---

app/views/events/shared/_affected_member.xml.haml
app/views/events/shared/_enrollee.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13417](https://devops.dchbx.org/redmine/issues/13417) |

13417: Enrollment Events from Enroll are missing end dates

---

app/assets/stylesheets/modules.scss.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12300](https://devops.dchbx.org/redmine/issues/12300) |

12300: Unread Messages are not BOLDED

---

app/models/hbx_enrollment.rb
app/models/rule_set/hbx_enrollment/individual_market_verification.rb
spec/models/hbx_enrollment_spec.rb
spec/models/rule_set/hbx_enrollment/individual_market_verificiation_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13857](https://devops.dchbx.org/redmine/issues/13857) |

13857: Plan Purchase Triggers Erroneous HbxEnrollment State transitions in other enrollments

---

app/models/plan_year.rb
app/notices/pdf_templates/plan_year.rb
app/notices/shop_notices/initial_employer_eligibility_notice.rb
app/views/notices/shared/_date.html.erb
app/views/notices/shared/_paragraph_no_top_margin.html.erb
app/views/notices/shop_notices/2_initial_employer_approval_notice.html.erb
app/views/notices/shop_notices/initial_employer_approval_notice.html.erb
db/seedfiles/notice_triggers_seed.rb
spec/notices/initial_employer_eligibility_notice_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14191](https://devops.dchbx.org/redmine/issues/14191) |

14191: Approval of ER Application - Number of FTEs and DC Business Address criteria met (approval notice) 

---

script/renewal_conversion_notices.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14564](https://devops.dchbx.org/redmine/issues/14564) |

14564: Load conversion notices for 6/1 groups 

---

app/views/insured/plan_shoppings/receipt.html.erb
app/views/insured/plan_shoppings/thankyou.html.erb
spec/views/insured/plan_shoppings/receipt.html.erb_spec.rb
spec/views/insured/plan_shoppings/thankyou.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14389](https://devops.dchbx.org/redmine/issues/14389) |

14389: Remove Benefit Packages text when EE submits an enrollment

---

app/controllers/documents_controller.rb
app/data_migrations/update_verification_types.rb
app/models/consumer_role.rb
lib/tasks/update_verification_types_for_fully_verified.rake
spec/controllers/documents_controller_spec.rb
spec/data_migrations/update_verification_types_spec.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14142](https://devops.dchbx.org/redmine/issues/14142) |

14142: All verification types have to be verified if consumer verified by curam 

---

app/controllers/exchanges/agents_controller.rb
app/models/person.rb
app/models/user.rb
lib/tasks/non_ridp_users_with_enrollments.rake
script/set_ridp_true_for_users.rb
spec/models/person_spec.rb
spec/models/user_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14400](https://devops.dchbx.org/redmine/issues/14400) |

14400: Unable to bypass RIDP using paper application

---

app/data_migrations/update_invalid_benefit_group_assignments_for_employer.rb
lib/tasks/update_invalid_benefit_group_assignments_for_employer.rake
spec/data_migrations/update_invalid_benefit_group_assignments_for_employer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14401](https://devops.dchbx.org/redmine/issues/14401) |

14401: Unable to Assign Benefit Package - Senate EE A. Kamp

---

lib/tasks/hbx_reports/non_enrolled_ivl_users_2017_report.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13683](https://devops.dchbx.org/redmine/issues/13683) |

13683: Report of non-enrolled IVL users

---

lib/tasks/plans/plan_network_import.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14535](https://devops.dchbx.org/redmine/issues/14535) |
| Ticket Author | Kenneth Taylor |

14535: Network Information not displaying correctly in EE plan shopping (and possibly IVL) 

---

script/backlog_verifications_generator.rb
script/verifications_csv_export.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14604](https://devops.dchbx.org/redmine/issues/14604) |

14604: Reminder Notice-

---

lib/tasks/hbx_reports/brokers_with_URL_from_admin_approval.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13451](https://devops.dchbx.org/redmine/issues/13451) |

13451: Daily list of Magic URLs

---

app/helpers/events_helper.rb
app/views/events/v2/organizations/_office_location.xml.haml
spec/helpers/events_helper_spec.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb
spec/views/events/v2/organizations/_office_locations.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14640](https://devops.dchbx.org/redmine/issues/14640) |

14640: XML is not correctly handling branch addresses

---

app/data_migrations/change_plan_year_effective_date.rb
lib/tasks/migrations/change_plan_year_effective_date.rake
spec/data_migrations/change_plan_year_effective_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14283](https://devops.dchbx.org/redmine/issues/14283) |

14283: Effective Date Update for Conversion Group - Embassy of Haiti

---

app/models/organization.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14704](https://devops.dchbx.org/redmine/issues/14704) |

14704: FEIN events need to be transmitted as fein_corrected

---

app/models/plan.rb
app/models/plan_cost_decorator.rb
app/models/plan_cost_decorator_congress.rb
app/models/shop_policy_calculations.rb
spec/models/plan_cost_decorator_congress_spec.rb
spec/models/plan_cost_decorator_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13310](https://devops.dchbx.org/redmine/issues/13310) |
| Ticket Author | Kenneth Taylor |

13310: System Is capping dental dependents in SHOP incorrectly

---

app/controllers/exchanges/broker_applicants_controller.rb
spec/controllers/exchanges/broker_applicants_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14138](https://devops.dchbx.org/redmine/issues/14138) |

14138: Check boxes in broker portal not working after clicking red Approve button

---

spec/models/person_spec.rb

Improvements for speed of specs and developer productivity.  This update drops off 2 minutes.
Main change here is we only drop or rebuild the person index we care about for the test, not ALL of them.

Reduce time taken for person spec.

---

app/helpers/events_helper.rb
app/views/events/v2/organizations/_office_location.xml.haml
spec/helpers/events_helper_spec.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14771](https://devops.dchbx.org/redmine/issues/14771) |

14771: XML should display addresses that do not have phone numbers

---

app/notices/ivl_notices/consumer_notice.rb
script/backlog_verifications_generator.rb
script/verifications_csv_export.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14726](https://devops.dchbx.org/redmine/issues/14726) |

14726: First Reminder Notification (10 days)

---

app/assets/javascripts/demographics_fields.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14536](https://devops.dchbx.org/redmine/issues/14536) |

14536: Date of expiration mandatory but should not be for I-94

---

app/data_migrations/fix_citizen_for_hub_responses.rb
app/models/consumer_role.rb
app/models/lawful_presence_determination.rb
app/models/subscribers/lawful_presence.rb
app/models/subscribers/ssa_verification.rb
lib/tasks/fix_citizen_for_hub_responses.rake
spec/data_migrations/fix_citizen_for_hub_responses_spec.rb
spec/models/consumer_role_spec.rb
spec/models/lawful_presence_determination_spec.rb
spec/models/subscribers/ssa_verification_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11219](https://devops.dchbx.org/redmine/issues/11219) |
| Start Date | 10/05/2016 |

11219: Analysis and data correction needed on remaining not lawfully present cases

---

app/controllers/broker_agencies/profiles_controller.rb
spec/controllers/broker_agencies/profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14061](https://devops.dchbx.org/redmine/issues/14061) |

14061: Data-Table error message 

---

app/data_migrations/update_conversion_flag.rb
lib/tasks/migrations/update_conversion_flag.rake
spec/data_migrations/update_conversion_flag_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14560](https://devops.dchbx.org/redmine/issues/14560) |

14560: Remove Conversion Flag -

---

features/step_definitions/integration_steps.rb

* (Required!)
* ()
* ()
```
```
*
---
---

handling plan shop cucumber if a month has 31 days

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/views/datatables/_terminate_enrollment.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14399](https://devops.dchbx.org/redmine/issues/14399) |

14399: Admin Functionality to Terminate Enrollment is broken

---

app/views/shared/_census_employee_fields.html.erb
features/employers/roster.feature
features/employers/step_definitions/cobra_steps.rb
vendor/assets/javascripts/jq_datepicker.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14636](https://devops.dchbx.org/redmine/issues/14636) |

14636: Allow future DOH when adding employees to the roster

---

app/views/events/v2/employers/updated.xml.haml
lib/v2_group_xml_generator.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14101](https://devops.dchbx.org/redmine/issues/14101) |

14101: V2 XML Broker Agency Profile

---

app/models/plan_year.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13612](https://devops.dchbx.org/redmine/issues/13612) |

13612: Terminated Employees Show in View Enrollment Report-THE ARC OF THE UNITED STATES

---

app/controllers/users/registrations_controller.rb
app/models/user.rb
spec/models/user_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14271](https://devops.dchbx.org/redmine/issues/14271) |

14271: User blocked from accessing account

---

app/notices/shop_notice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14330](https://devops.dchbx.org/redmine/issues/14330) |

14330: Testing email sent to employer Group

---

app/data_migrations/change_fein.rb
lib/tasks/change_fein.rake
spec/data_migrations/change_fein_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14924](https://devops.dchbx.org/redmine/issues/14924) |

14924: FEIN Change - ABUNAIPOKE LLC

---

app/controllers/broker_agencies/profiles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14736](https://devops.dchbx.org/redmine/issues/14736) |

14736: "Update Broker Agency" button not working

---

app/controllers/events/individuals_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13357](https://devops.dchbx.org/redmine/issues/13357) |

13357: Individual Event Resource fails to respond on a crash

---

script/update_attributes_on_census_employee.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15126](https://devops.dchbx.org/redmine/issues/15126) |

15126: Invalid Benefit Group - JSP Companies, Inc

---

app/data_migrations/update_ee_dot.rb
lib/tasks/migrations/update_ee_dot.rake
spec/data_migrations/update_ee_dot_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14551](https://devops.dchbx.org/redmine/issues/14551) |
| Ticket Author | Brooklynn Berry |

14551: Employer Roster DOT Change- KASS, MITEK & KASS, PLLC- B.Lee

---

app/views/people/landing_pages/_personal.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14402](https://devops.dchbx.org/redmine/issues/14402) |

14402: Gender button is not clickable - HBX ID "19751723"

---

script/backlog_verifications_generator.rb
script/verifications_csv_export.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13576](https://devops.dchbx.org/redmine/issues/13576) |
| Ticket Author | Camille Gray |

13576: Notice 20B - Second Verification Request Notice

---

app/data_migrations/change_plan_year_effective_date.rb
spec/data_migrations/change_plan_year_effective_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15174](https://devops.dchbx.org/redmine/issues/15174) |
| Ticket Author | @nisanthyaganti9 |

15174: use change plan year effective date rake task only for conversions.

---

app/assets/javascripts/demographics_fields.js
app/models/forms/consumer_fields.rb
app/models/forms/family_member.rb
app/models/person.rb
spec/models/forms/family_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14721](https://devops.dchbx.org/redmine/issues/14721) |

14721: Non-primary subscribers (dependents) may not enroll without answering mandatory quesitons

---

app/data_migrations/update_employer_status.rb
lib/tasks/update_employer_status.rake
spec/data_migrations/update_employer_status_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15229](https://devops.dchbx.org/redmine/issues/15229) |

15229: Transition 5/1 Group  to "Enrolled Status" - Let America Vote

---

app/data_migrations/change_plan_year_effective_date.rb
spec/data_migrations/change_plan_year_effective_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14994](https://devops.dchbx.org/redmine/issues/14994) |

14994: Effective Date Update for Conversion Groups - 6/1 ERs sent by Kaiser in Error

---

app/data_migrations/change_renewing_plan_year_aasm_state.rb
lib/tasks/migrations/change_renewing_plan_year_aasm_state.rake
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15152](https://devops.dchbx.org/redmine/issues/15152) |

15152: Transition Group to " Renewing Enrolling" Status - Dambly Design

---

script/cancel_plan_year.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15306](https://devops.dchbx.org/redmine/issues/15306) |

15306: Remove Benefit Package - Family Practices Medical Services, PC

---

app/data_migrations/expire_conversion_employers.rb
app/models/plan_year.rb
lib/tasks/migrations/expire_conversion_employers.rake
spec/data_migrations/expire_conversion_employers_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12534](https://devops.dchbx.org/redmine/issues/12534) |

12534: 12/1 groups that didn't renew or didn't convert - update12/1/2016 plan year status to renewing_cancelled

---

app/data_migrations/change_gender.rb
lib/tasks/migrations/change_gender.rake
spec/data_migrations/change_gender_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14554](https://devops.dchbx.org/redmine/issues/14554) |
| Ticket Author | Imani Williams |

14554: Gender Correction -- Jessica Andrews

---

app/views/insured/families/_consumer_broker.html.erb
spec/views/insured/families/_consumer_broker.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15031](https://devops.dchbx.org/redmine/issues/15031) |

15031: Please show IVL Broker Assignment date in EnrollApp

---

app/data_migrations/merge_ee_and_er_accounts.rb
lib/tasks/migrations/merge_ee_and_er_accounts.rake
spec/data_migrations/merge_ee_and_er_accounts_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14997](https://devops.dchbx.org/redmine/issues/14997) |

14997: merge ER and EE accounts - 19915507

---

app/assets/stylesheets/new.scss.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15276](https://devops.dchbx.org/redmine/issues/15276) |

15276: Employer Enrollment Report UI changes

---

app/models/family_member.rb
app/models/forms/family_member.rb
app/models/person.rb
spec/controllers/broker_agencies/profiles_controller_spec.rb
spec/models/forms/family_member_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15158](https://devops.dchbx.org/redmine/issues/15158) |

15158: IVL demographics page - required field guards and validations

---

app/models/effective/datatables/premium_billing_report_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15337](https://devops.dchbx.org/redmine/issues/15337) |

15337: Update Text On Enrollment Billing  Report

---

app/notices/shop_employer_notices/employer_renewal_notice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15421](https://devops.dchbx.org/redmine/issues/15421) |

15421: Load SHOP 5 Notice - Employer Renewal notice

---

app/data_migrations/populate_conversion_flag.rb
app/models/factories/plan_year_renewal_factory.rb
app/models/importers/conversion_employer_plan_year.rb
app/models/importers/conversion_employer_plan_year_update.rb
app/models/plan_year.rb
lib/congressional_renewal_cleanup.rb
lib/tasks/migrations/benefit_group_assignment_cleanup.rake
lib/tasks/migrations/initial_congress_roster_to_2015_plan_year.rake
lib/tasks/migrations/populate_conversion_flag.rake
lib/tasks/update_shop_plan_year_renewal.rake
spec/data_migrations/expire_conversion_employers_spec.rb
spec/data_migrations/group_conversion_employers_migration_spec.rb
spec/data_migrations/migrate_plan_year_spec.rb
spec/data_migrations/populate_conversion_flag_spec.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15469](https://devops.dchbx.org/redmine/issues/15469) |

15469: Populate conversion flag on external plan years

---

lib/tasks/hbx_reports/ivl_non_dc_address.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14397](https://devops.dchbx.org/redmine/issues/14397) |

14397: Monthly report of IVL cases with non-DC addresses

---

app/views/events/emails/_email.xml.haml
app/views/events/hbx_enrollment/_policy.xml.haml
app/views/events/individuals/_responsible_party.xml.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14658](https://devops.dchbx.org/redmine/issues/14658) |

14658: Crash on enrollment event resource for responsible parties

---

app/models/hbx_enrollment.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15330](https://devops.dchbx.org/redmine/issues/15330) |

15330: Determine why shop open enrollments are so 'SEP happy'

---

app/data_migrations/change_email_address.rb
app/data_migrations/change_email_of_user.rb
app/data_migrations/change_username.rb
lib/tasks/change_email_address.rake
lib/tasks/change_email_of_user.rake
lib/tasks/change_username.rake
spec/data_migrations/change_email_address_spec.rb
spec/data_migrations/change_email_of_user_spec.rb
spec/data_migrations/change_username_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15193](https://devops.dchbx.org/redmine/issues/15193) |
| Ticket Author | Joshua Karper |

15193: User record update

---

app/helpers/insured/families_helper.rb
spec/views/insured/families/_enrollment.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14300](https://devops.dchbx.org/redmine/issues/14300) |

14300: Error message - "We're sorry, but something went wrong"

---

app/models/hbx_enrollment.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15556](https://devops.dchbx.org/redmine/issues/15556) |

15556: Superseded enrollments will get termination transition recorded without state update

---

app/data_migrations/remove_member_from_hbx_enrollment.rb
lib/tasks/remove_member_from_hbx_enrollment.rake
spec/data_migrations/remove_member_from_hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15265](https://devops.dchbx.org/redmine/issues/15265) |

15265: Smashed data cleanup

---

app/notices/shop_employer_notices/employer_renewal_notice.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15574](https://devops.dchbx.org/redmine/issues/15574) |

15574: Correct renewal notice 

---

app/data_migrations/change_fein.rb
spec/data_migrations/change_fein_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15353](https://devops.dchbx.org/redmine/issues/15353) |

15353: FEIN Update: American Association of People with Disabilities

---

lib/v2_group_xml_generator.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13475](https://devops.dchbx.org/redmine/issues/13475) |

13475: Validation check for duplicate groups on an XML

---

app/data_migrations/update_benefit_group_assignment_start_date.rb
lib/tasks/update_benefit_group_assignment_start_date.rake
spec/data_migrations/update_benefit_group_assignment_start_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15477](https://devops.dchbx.org/redmine/issues/15477) |

15477: Benefit group assignments is invalid - Transemantics, Inc.

---

app/assets/javascripts/plan_shopping.js.erb
app/views/insured/plan_shoppings/_plan_filters.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13465](https://devops.dchbx.org/redmine/issues/13465) |

13465: APTC Widget Applied APTC can exceed Max APTC

---

app/data_migrations/change_fein.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15594](https://devops.dchbx.org/redmine/issues/15594) |

15594: FEIN Update: Carl Consulting

---

app/controllers/insured/families_controller.rb
app/models/family.rb
app/models/person.rb
app/policies/family_policy.rb
spec/controllers/insured/families_controller_spec.rb
spec/policies/family_policy_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15696](https://devops.dchbx.org/redmine/issues/15696) |

15696: Use pundit on family page instead of controller logic

---

app/controllers/exchanges/hbx_profiles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15691](https://devops.dchbx.org/redmine/issues/15691) |

15691: Simplify broker invitation inbox message

---

app/controllers/broker_agencies/profiles_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15254](https://devops.dchbx.org/redmine/issues/15254) |

15254: Broker language spoken not updating when clicking Update Broker Agency

---

app/data_migrations/update_employee_plan_selection.rb
lib/tasks/migrations/update_employee_plan_selection.rake
spec/data_migrations/update_employee_plan_selection_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14872](https://devops.dchbx.org/redmine/issues/14872) |

14872: Update employee plan selections in account - Fort Lincoln Realty Inc

---

app/helpers/time_helper.rb
app/views/sep/approval/_admin_detail.html.erb
spec/helpers/time_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15445](https://devops.dchbx.org/redmine/issues/15445) |

15445: Previous Plan Year Election - Choice Dates

---

lib/tasks/migrations/terminate_employer_accounts.rake
spec/lib/tasks/terminate_employer_accounts_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15706](https://devops.dchbx.org/redmine/issues/15706) |

15706: Please open a 6/1/2017 initial application in EA-  KEIL CONSTRUCTION

---

app/controllers/insured/consumer_roles_controller.rb
app/controllers/insured/group_selection_controller.rb
app/views/insured/group_selection/_coverall_coverage_household.html.erb
app/views/insured/group_selection/new.html.erb
spec/controllers/insured/consumer_roles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14307](https://devops.dchbx.org/redmine/issues/14307) |
| Ticket Author | Camille Gray |

14307: EA circling back to IVL application after completing DC Resident application/plan shopping

---

app/data_migrations/change_person_dob.rb
lib/tasks/change_person_dob.rake
spec/data_migrations/change_person_dob_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15356](https://devops.dchbx.org/redmine/issues/15356) |

15356: Email and username and DOB update - 19931208

---

app/views/shared/inboxes/_message.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13707](https://devops.dchbx.org/redmine/issues/13707) |

13707: Inbox TimeStamp for Shop a/b notice

---

app/views/notices/shop_notices/3a_employer_plan_year_renewal.html.erb
app/views/notices/shop_notices/3b_employer_plan_year_renewal.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14379](https://devops.dchbx.org/redmine/issues/14379) |

14379: Correct Verbiage for Renewal notice template 

---

app/models/plan_year.rb
features/step_definitions/employers_steps.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14663](https://devops.dchbx.org/redmine/issues/14663) |

14663: PPY-Change Pop up Language 

---

app/controllers/insured/families_controller.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15724](https://devops.dchbx.org/redmine/issues/15724) |

15724: Set bookmark URL after access check on familiies home page

---

app/models/person.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14193](https://devops.dchbx.org/redmine/issues/14193) |

14193: POCs are not displaying in the UI

---

lib/object_builders/qhp_builder.rb
lib/tasks/load_broker.rake

Remove 'incidental' log file creation.

Don't create log files just because rake ran.

---

app/data_migrations/merge_ee_and_er_accounts.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15442](https://devops.dchbx.org/redmine/issues/15442) |

15442: merge ER and EE accounts - 19933837

---

app/models/effective/datatables/employer_datatable.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15334](https://devops.dchbx.org/redmine/issues/15334) |
| Ticket Author | @Battula |

15334: Minimum Participation is incorrect.

---

script/destroy_census_employee.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15561](https://devops.dchbx.org/redmine/issues/15561) |
| Ticket Author | J'Aimee Louis |

15561: Remove Employee From Roster

---

app/data_migrations/change_broker_npn.rb
lib/tasks/migrations/change_broker_npn.rake
spec/data_migrations/change_broker_npn_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15683](https://devops.dchbx.org/redmine/issues/15683) |

15683: Please change broker's NPN in EA

---

app/controllers/exchanges/agents_controller.rb
app/models/person.rb
spec/controllers/exchanges/agents_controller_spec.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15680](https://devops.dchbx.org/redmine/issues/15680) |

15680: Admin Bypass of RIDP via "Paper" Action

---

app/data_migrations/remove_dependent_from_ee_enrollment.rb
lib/tasks/migrations/remove_dependent_from_ee_enrollment.rake
spec/data_migrations/remove_dependent_from_ee_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13919](https://devops.dchbx.org/redmine/issues/13919) |

13919: Display clean-up for smashed case

---

app/helpers/application_helper.rb
app/views/insured/plan_shoppings/_plan_details.html.erb
app/views/shared/_summary.html.erb
spec/factories/plans.rb
spec/helpers/application_helper_spec.rb
spec/views/insured/plan_shoppings/_plan_details.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15534](https://devops.dchbx.org/redmine/issues/15534) |

15534: Plan Shopping deductible display based on family composition 

---

app/data_migrations/update_carefirst_shop_health_plan_deductible.rb
lib/tasks/migrations/update_carefirst_shop_health_plan_deductible.rake
spec/data_migrations/update_carefirst_shop_health_plan_deductible_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15605](https://devops.dchbx.org/redmine/issues/15605) |

15605: Update individual and deductible for Carefirst SHOP plan- BluePreferred PPO CDH Slv 2000

---

app/controllers/employers/census_employees_controller.rb
app/controllers/insured/group_selection_controller.rb
app/models/benefit_group_assignment.rb
app/models/census_employee.rb
app/models/factories/family_enrollment_clone_factory.rb
app/models/hbx_enrollment.rb
features/employers/step_definitions/cobra_steps.rb
spec/controllers/insured/group_selection_controller_spec.rb
spec/models/census_employee_spec.rb
spec/models/factories/family_enrollment_clone_factory_spec.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15266](https://devops.dchbx.org/redmine/issues/15266) |

15266: Investigate COBRA Enrollment

---

app/models/family_member.rb
spec/factories/families.rb
spec/models/family_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13190](https://devops.dchbx.org/redmine/issues/13190) |

13190: Duplicate person validation needs to occur on FamilyMember in addition to Family

---

Gemfile.lock
app/models/plan_year.rb
app/models/queries/named_policy_queries.rb
app/models/queries/shop_monthly_enrollments.rb
app/models/subscribers/default_ga_changed.rb
app/models/subscribers/shop_binder_enrollments_transmission_authorized.rb
app/models/subscribers/shop_renewal_transmission_authorized.rb
config/application.rb
spec/models/queries/named_policy_queries_spec.rb
spec/models/queries/shop_monthly/monthly_enrollment_query_spec.rb
spec/models/queries/shop_monthly/monthly_renewal_termination_query_spec.rb
spec/models/subscribers/shop_binder_enrollments_transmission_authorized_spec.rb
spec/models/subscribers/shop_renewal_transmission_authorized_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15223](https://devops.dchbx.org/redmine/issues/15223) |

15223: Shop Monthly Transmission Event

---

app/assets/javascripts/application.js.erb
app/assets/javascripts/dob_validation.js

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11815](https://devops.dchbx.org/redmine/issues/11815) |

11815: Put Checks In Place When POC Enters Current Year as DOB

---

app/data_migrations/revert_termination_for_employee.rb
lib/tasks/migrations/revert_termination_for_employee.rake
spec/data_migrations/revert_termination_for_employee_spec.rb
spec/factories/census_employees.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14915](https://devops.dchbx.org/redmine/issues/14915) |

14915: Undo Termination Pending Status- America's Promise Alliance

---

app/assets/javascripts/employer_profile.js
app/views/employers/employer_profiles/my_account/_census_employees.html.erb
app/views/employers/employer_profiles/my_account/_employees_by_status.html.erb
app/views/employers/employer_profiles/show_profile.js
app/views/shared/_alph_paginate.html.erb
features/employers/roster.feature
features/step_definitions/employers_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13433](https://devops.dchbx.org/redmine/issues/13433) |

13433: Cannot search employer roster for terminated employees

---

app/data_migrations/update_aptc_dental_enr.rb
lib/tasks/migrations/update_aptc_dental_enr.rake
spec/data_migrations/update_aptc_dental_enr_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15296](https://devops.dchbx.org/redmine/issues/15296) |

15296: Applied APTC Greater than Premium for DENTAL

---

app/data_migrations/merge_ee_and_er_accounts.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15734](https://devops.dchbx.org/redmine/issues/15734) |

15734: merge ER and EE accounts - 19923792

---

app/data_migrations/add_existing_family_member_as_dependent_to_enrollment.rb
lib/tasks/add_existing_family_member_as_dependent_to_enrollment.rake
spec/data_migrations/add_existing_family_member_as_dependent_to_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13918](https://devops.dchbx.org/redmine/issues/13918) |

13918: Display clean-up for smashed case

---

app/mailers/user_mailer.rb
app/models/invitation.rb
app/views/user_mailer/invite_initial_employee_for_open_enrollment.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14745](https://devops.dchbx.org/redmine/issues/14745) |

14745: Shop 24-OE Begins for new hires

---

app/controllers/concerns/sep_all.rb
app/helpers/time_helper.rb
app/models/special_enrollment_period.rb
app/views/sep/approval/_admin_detail.html.erb
spec/helpers/time_helper_spec.rb
spec/models/special_enrollment_period_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15719](https://devops.dchbx.org/redmine/issues/15719) |

15719: Previous Plan Year Election - Editing Dates

---

app/models/queries/shop_monthly_enrollments.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15956](https://devops.dchbx.org/redmine/issues/15956) |

15956: Monthly shop transmission queries should exclude COBRAs

---

app/views/insured/group_selection/_enrollment.html.erb
app/views/insured/group_selection/terminate_confirm.html.erb
spec/views/insured/group_selection/_enrollment.html.erb_spec.rb
spec/views/insured/group_selection/terminate_confirmation.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [5080](https://devops.dchbx.org/redmine/issues/5080) |
| Start Date | 02/01/2016 |

5080: IVL/Employee - Premium Amount and DCHL ID showing different values in My Account and Termination pages

---

app/views/shared/_office_location_fields.html.erb
features/step_definitions/employers_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14384](https://devops.dchbx.org/redmine/issues/14384) |

14384: Remove the word "Primary" from Update Business Section

---

app/data_migrations/change_renewing_plan_year_aasm_state.rb
lib/tasks/migrations/change_renewing_plan_year_aasm_state.rake
spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15910](https://devops.dchbx.org/redmine/issues/15910) |

15910: Transition Group to " Renewing Enrolled" Status - 6/1 conversion/renewal

---

app/data_migrations/remove_invalid_broker_agency_accounts_for_employer.rb
lib/tasks/migrations/remove_invalid_broker_agency_accounts_for_employer.rake
spec/data_migrations/remove_invalid_broker_agency_accounts_for_employer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15936](https://devops.dchbx.org/redmine/issues/15936) |

15936: Broker Issues with 6/1 ER Kalorama Partners, Llc

---

lib/tasks/migrations/terminate_employer_accounts.rake
spec/lib/tasks/terminate_employer_accounts_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15190](https://devops.dchbx.org/redmine/issues/15190) |

15190: April 2017 Terminations for non-payment

---

app/controllers/insured/consumer_roles_controller.rb
app/models/family.rb
spec/controllers/insured/consumer_roles_controller_spec.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15483](https://devops.dchbx.org/redmine/issues/15483) |

15483: IVL role creation- unable to edit dependents during role creation.

---

app/data_migrations/remove_user_record.rb
lib/tasks/remove_user_record.rake
spec/data_migrations/remove_user_record_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15774](https://devops.dchbx.org/redmine/issues/15774) |

15774: User record update

---

app/controllers/insured/family_members_controller.rb
app/models/forms/consumer_fields.rb
app/models/person.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15659](https://devops.dchbx.org/redmine/issues/15659) |
| Ticket Author | @lisyk |

15659: consumer fields for dependents doesn't reflect what consumer selected

---

app/models/invitation.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14743](https://devops.dchbx.org/redmine/issues/14743) |

14743: New hire notice, date of hire in the future

---

app/models/effective/datatables/employer_datatable.rb
app/models/organization.rb
features/admin/employer_search.feature
features/step_definitions/employer_search_steps.rb
features/step_definitions/integration_steps.rb
spec/factories/permission.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13682](https://devops.dchbx.org/redmine/issues/13682) |

13682: allow searching on employer tab by HBX ID

---

app/controllers/insured/consumer_roles_controller.rb
app/policies/consumer_role_policy.rb
spec/controllers/insured/consumer_roles_controller_spec.rb
spec/policies/consumer_role_policy_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16030](https://devops.dchbx.org/redmine/issues/16030) |

16030: Implement Pundit Policy for Insured::ConsumerRolesController#edit

---

app/data_migrations/change_census_employee_dot.rb
lib/tasks/migrations/change_census_employee_dot.rake
spec/data_migrations/change_census_employee_dot_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12425](https://devops.dchbx.org/redmine/issues/12425) |

12425: Employer Unable to Terminate EE from Roster - receives 60 day error, even though term date is w/in 60 days

---

app/data_migrations/change_plan_year_effective_terminated_on.rb
lib/tasks/migrations/change_plan_year_effective_terminated_on.rake
spec/data_migrations/change_plan_year_effective_terminated_on_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [4663](https://devops.dchbx.org/redmine/issues/4663) |

4663: Termination Date on ER Roster Does Not Match Termination Date on EE's Enrollment Tile

---

lib/tasks/migrations/cancel_employer_renewal.rake
spec/lib/tasks/cancel_employer_renewal_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15311](https://devops.dchbx.org/redmine/issues/15311) |

15311: 5-1-2017 Groups that did not re-new or migrate

---

app/models/plan_year.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15555](https://devops.dchbx.org/redmine/issues/15555) |

15555: Benefit group assignments is invalid - Churches For Middle East Peace (CMEP)

---

app/models/effective/datatables/premium_billing_report_data_table.rb
app/models/queries/premium_billing_report_query.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15468](https://devops.dchbx.org/redmine/issues/15468) |

15468: Enrollment Report- When EE is enrolled in both health and dental, only one enrollment shows on report

---

app/assets/stylesheets/jquery-steps.css
app/views/broker_agencies/quotes/_quote_calculate.html.erb
app/views/broker_agencies/quotes/show.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15896](https://devops.dchbx.org/redmine/issues/15896) |

15896: BQT fast follow-Align Benefit Group Buttons

---

app/controllers/insured/families_controller.rb
app/controllers/insured/group_selection_controller.rb
app/views/insured/group_selection/new.html.erb
app/views/shared/plan_shoppings/_more_plan_details.html.erb
spec/controllers/insured/families_controller_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb
spec/views/shared/_comparison.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15613](https://devops.dchbx.org/redmine/issues/15613) |

15613: Make Effective Date more Apparent in Plan Shopping

---

app/data_migrations/create_new_initial_plan_year_using_another.rb
lib/tasks/migrations/create_new_initial_plan_year_using_another.rake
spec/data_migrations/create_new_initial_plan_year_using_another_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15851](https://devops.dchbx.org/redmine/issues/15851) |

15851: Change Effective Date and Force Publish - Transcend4Good, LLC

---

app/helpers/time_helper.rb
app/views/datatables/_terminate_enrollment.html.erb
spec/helpers/time_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15269](https://devops.dchbx.org/redmine/issues/15269) |

15269:  Action dropdown -  Default Termination date issue in the Employee Enrollment

---

app/models/phone.rb
spec/data_migrations/update_full_phone_number_spec.rb
spec/models/phone_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15984](https://devops.dchbx.org/redmine/issues/15984) |

15984: Phone numbers are not always parsed correctly when an extension is provided

---

lib/tasks/hbx_reports/family_list_with_antiquated_relationship_types.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14596](https://devops.dchbx.org/redmine/issues/14596) |

14596: Data query for antiquated relationship types

---

spec/lib/tasks/cancel_employer_renewal_spec.rb
spec/lib/tasks/hbx_reports/users_account_with_no_email_spec.rb
spec/lib/tasks/terminate_employer_accounts_spec.rb

Missing database cleaning - causing erronous spec failures.

Make sure db is cleaned.

---

app/controllers/broker_agencies/profiles_controller.rb
app/models/forms/broker_agency_profile.rb
app/models/phone.rb
app/views/broker_agencies/quotes/quotes.html.erb
spec/controllers/broker_agencies/profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15400](https://devops.dchbx.org/redmine/issues/15400) |

15400: Broker Agency changes not flowing to Choose Broker functionality

---

app/assets/stylesheets/effective_datatable.scss.erb
app/controllers/broker_agencies/profiles_controller.rb
app/models/effective/datatables/employer_datatable.rb
app/models/effective/datatables/general_agency_data_table.rb
app/views/broker_agencies/profiles/_employers.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13753](https://devops.dchbx.org/redmine/issues/13753) |

13753: Add sorting feature back to employers tab for Broker/GA. 

---

app/data_migrations/general_agency_assignment.rb
lib/tasks/migrations/general_agency_assignment.rake
spec/data_migrations/general_agency_assignment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15092](https://devops.dchbx.org/redmine/issues/15092) |

15092: General Agency assignments not processing in EnrollApp

---

app/models/effective/datatables/quote_datatable.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15898](https://devops.dchbx.org/redmine/issues/15898) |

15898: BQT fast follow-Add effecitive date column on data table page- 

---

app/data_migrations/add_family_member_to_coverage_household.rb
lib/tasks/migrations/add_family_member_to_coverage_household.rake
spec/data_migrations/add_family_member_to_coverage_household.rb
spec/data_migrations/add_family_member_to_coverage_household_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10572](https://devops.dchbx.org/redmine/issues/10572) |
| Start Date | 08/26/2016 |

10572: Consumer blocked by "Eligibility failed on relationships" error. 

---

app/views/employers/employer_profiles/my_account/_benefits.html.erb
spec/views/employers/employer_profiles/my_account/benefits.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15899](https://devops.dchbx.org/redmine/issues/15899) |

15899: BQT fast follow- Turn off Claim quote when PY already active

---

app/models/plan_cost_decorator_quote.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16097](https://devops.dchbx.org/redmine/issues/16097) |

16097: BQT error message 

---

app/data_migrations/change_enrollment_termination_date.rb
lib/tasks/change_enrollment_termination_date.rake
spec/data_migrations/change_enrollment_termination_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14629](https://devops.dchbx.org/redmine/issues/14629) |
| Ticket Author | J'Aimee Louis |

14629: Correct Enrollment Tile to Reflect Dependent Drop

---

app/data_migrations/delink_broker_general_agency.rb
lib/tasks/delink_broker_general_agency.rake
spec/data_migrations/delink_broker_general_agency_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16128](https://devops.dchbx.org/redmine/issues/16128) |

16128: General Agency name and access changed!  Needs immediate fix

---

app/models/employer_profile_account.rb
spec/models/employer_profile_account_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16300](https://devops.dchbx.org/redmine/issues/16300) |

16300: 6/1 ERs incorrectly canceled due to binder payment pending

---

app/views/insured/group_selection/_enrollment.html.erb
spec/views/insured/group_selection/_enrollment.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16266](https://devops.dchbx.org/redmine/issues/16266) |

16266: Don't require termination reason for IVL plan

---

app/models/forms/family_member.rb
spec/models/forms/family_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15573](https://devops.dchbx.org/redmine/issues/15573) |

15573: Dependent Not Included in Plan Shopping

---

app/data_migrations/remove_hbx_id.rb
lib/tasks/migrations/remove_hbx_id.rake
spec/data_migrations/remove_hbx_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15960](https://devops.dchbx.org/redmine/issues/15960) |

15960: SHOP employee account correction

---

app/controllers/events/employers_controller.rb
app/views/events/v2/employers/updated.xml.haml
lib/v2_group_xml_generator.rb
script/write_employer_files.rb
spec/controllers/events/employers_controller_spec.rb
spec/views/events/v2/employers/updated.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16060](https://devops.dchbx.org/redmine/issues/16060) |

16060: Manual generation of CVs should include all plan years

---

app/controllers/financial_assistance/deductions_controller.rb
app/controllers/financial_assistance/incomes_controller.rb
app/models/financial_assistance/deduction.rb
app/models/financial_assistance/income.rb
app/views/financial_assistance/applicants/edit.html.erb
app/views/financial_assistance/deductions/steps.yml
components/ui_helpers/app/views/workflow/_input_date.html.erb
config/routes.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16293](https://devops.dchbx.org/redmine/issues/16293) |

16293: DEDUCTION.YML - Integrate FORM and Save

---

app/models/hbx_enrollment.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15391](https://devops.dchbx.org/redmine/issues/15391) |
| Ticket Author | Brooklynn Berry |

15391: Employee cannot be terminated-- HBX ID 19787998

---

app/data_migrations/update_person_relationship_kind.rb
lib/tasks/migrations/update_person_relationship_kind.rake
spec/data_migrations/update_person_relationship_kind_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16224](https://devops.dchbx.org/redmine/issues/16224) |

16224: Unable to plan shop due to "Family Relationships" error message

---

app/data_migrations/change_initial_plan_year_aasm_state.rb
lib/tasks/migrations/change_initial_plan_year_aasm_state.rake
spec/data_migrations/change_initial_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16344](https://devops.dchbx.org/redmine/issues/16344) |

16344: Please set plan year to "Enrolling" state - Training Grounds Inc

---

app/data_migrations/deactivate_employer_staff_role.rb
lib/tasks/migrations/deactivate_employer_staff_role.rake
spec/data_migrations/deactivate_employer_staff_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16113](https://devops.dchbx.org/redmine/issues/16113) |

16113: FEIN Correction in EA and Transmittal to the Carrier- DUBLINER, INC

---

app/controllers/insured/group_selection_controller.rb
app/models/hbx_enrollment.rb
app/models/household.rb
spec/models/hbx_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14686](https://devops.dchbx.org/redmine/issues/14686) |

14686: Admin granted SEPs member start date

---

lib/tasks/migrations/create_published_plan_years_for_certain_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11140](https://devops.dchbx.org/redmine/issues/11140) |

11140: Please add the 7/1/2016 active plan year in ENROLL for Beulah Baptist Church

---

app/models/effective/datatables/family_data_table.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13464](https://devops.dchbx.org/redmine/issues/13464) |

13464: Turn ON SEP ADMIN Functionality in PrePROD

---

app/data_migrations/map_dental_plans.rb
lib/tasks/map_dental_plans.rake
spec/data_migrations/map_dental_plans_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16264](https://devops.dchbx.org/redmine/issues/16264) |

16264: Dental renewal plan mapping missing.

---

app/data_migrations/cancel_plan_year.rb
lib/tasks/migrations/cancel_plan_year.rake
spec/data_migrations/cancel_plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12182](https://devops.dchbx.org/redmine/issues/12182) |

12182: Please remove Do Not Use plan year (2017) from National Religious Broadcasters

---

app/models/factories/plan_year_renewal_factory.rb
spec/factories/benefit_groups.rb
spec/factories/employer_profiles.rb
spec/factories/plan_years.rb
spec/models/factories/family_enrollment_clone_factory_spec.rb
spec/models/factories/plan_year_renewal_factory_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16265](https://devops.dchbx.org/redmine/issues/16265) |

16265: Update Plan year renewal factory to handle dental offerings

---

app/interactors/find_or_create_insured_person.rb
spec/interactors/find_or_create_insured_person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [4723](https://devops.dchbx.org/redmine/issues/4723) |
| Start Date | 01/12/2016 |

4723: Implement additional matching criteria using SSN and DOB to prevent overwriting of person or family member records

---

app/data_migrations/terminate_enr_with_date.rb
lib/tasks/hbx_reports/terminate_enr_with_date.rake
spec/data_migrations/terminate_enr_with_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [13951](https://devops.dchbx.org/redmine/issues/13951) |

13951: SHOP Enrollment should be terminated. 

---

app/data_migrations/import_missing_person_contact_info.rb
lib/tasks/import_missing_person_address_info.rake
spec/data_migrations/import_missing_person_contact_info_spec.rb
spec/factories/people.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [8410](https://devops.dchbx.org/redmine/issues/8410) |
| Start Date | 07/25/2016 |
| Ticket Author |  Anonymous |

8410: Multiple people are still missing data from employee roster

---

app/controllers/insured/consumer_roles_controller.rb
app/models/consumer_role.rb
app/models/factories/enrollment_factory.rb
app/models/person.rb
spec/models/person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16229](https://devops.dchbx.org/redmine/issues/16229) |

16229: Applying for Coverage - False before Auth & Consent

---

app/data_migrations/change_initial_plan_year_aasm_state.rb
spec/data_migrations/change_initial_plan_year_aasm_state_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16441](https://devops.dchbx.org/redmine/issues/16441) |

16441: Please set plan year to "Enrolling" state - MOVEIUS Contemporary Ballet

---

app/controllers/financial_assistance/applications_controller.rb
app/models/financial_assistance/application.rb
app/views/financial_assistance/applications/edit.html.erb
app/views/financial_assistance/applications/steps.yml
app/views/financial_assistance/applications/steps_backup.yml
config/routes.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16447](https://devops.dchbx.org/redmine/issues/16447) |

16447: Create Your Preference & Submit Page

---

app/models/family.rb
app/models/family_member.rb
spec/models/family_member_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16471](https://devops.dchbx.org/redmine/issues/16471) |

16471: Create an Applicant instance when a FamilyMember is added to a Household

---

lib/object_builders/qhp_builder.rb

Fix an issue where loading would crash.

Fixing path in the loader.

---

lib/tasks/hbx_reports/generate_report_of_bad_phone_number.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16038](https://devops.dchbx.org/redmine/issues/16038) |

16038: Generate report of bad phone numbers

---

app/data_migrations/update_user_or_person_records.rb
lib/tasks/update_user_or_person_records.rake
spec/data_migrations/update_user_or_person_records_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16185](https://devops.dchbx.org/redmine/issues/16185) |

16185: User Record Rake Task Update

---

app/data_migrations/remove_one_ce_from_er.rb
lib/tasks/remove_one_ce_from_er.rake
spec/data_migrations/remove_one_ce_from_er_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15428](https://devops.dchbx.org/redmine/issues/15428) |

15428: Undo Employee Roster Entry- Enterprise Integration Corpora

---

components/ui_helpers/app/views/workflow/step.html.erb
components/ui_helpers/app/views/workflow/step_partials/_right_nav.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16448](https://devops.dchbx.org/redmine/issues/16448) |

16448: In-STEP Navigation

---

app/models/plan_year.rb
app/notices/shop_employer_notices/initial_employer_ineligibility_notice.rb
app/views/notices/shop_employer_notices/initial_employer_ineligibility_notice.html.erb
db/seedfiles/notice_triggers_seed.rb
spec/notices/shop_employer_notices/initial_employer_ineligibility_notice_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15812](https://devops.dchbx.org/redmine/issues/15812) |

15812: Shop 32-Initial Employee Open Enrollment Completed (Did Not Meet Minimum Participation Requirement or non-owner enrollee requirement)

---

app/data_migrations/change_suffix_person.rb
lib/tasks/migrations/change_suffix_person.rake
spec/data_migrations/change_suffix_person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15809](https://devops.dchbx.org/redmine/issues/15809) |

15809: SHOP employee prefixes appearing in suffix field in EnrollApp & on 834s

---

app/data_migrations/update_plan_years_with_dental_offerings.rb
app/models/benefit_group.rb
app/models/factories/enrollment_renewal_builder.rb
app/models/factories/family_enrollment_renewal_factory.rb
app/models/factories/plan_year_renewal_factory.rb
app/models/factories/shop_enrollment_renewal_factory.rb
lib/tasks/migrations/update_plan_years_with_dental_offerings.rake
spec/data_migrations/update_plan_years_with_dental_offerings_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16474](https://devops.dchbx.org/redmine/issues/16474) |

16474: Add Renewal Dental Plan Year to groups and retransmit XMLs

---

app/data_migrations/disable_person_account.rb
lib/tasks/migrations/disable_person_account.rake
spec/data_migrations/disable_person_account_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12337](https://devops.dchbx.org/redmine/issues/12337) |
| Ticket Author | Amy Calderon |

12337: Correct SSN on Senate Roster

---

lib/tasks/migrations/terminate_employer_accounts.rake
script/fix_benefit_group_assignments_for_employees.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16512](https://devops.dchbx.org/redmine/issues/16512) |

16512: Invalid Benefit Group - ELEVATE, LLC

---

lib/tasks/hbx_reports/brokers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16622](https://devops.dchbx.org/redmine/issues/16622) |

16622: Fix daily broker report

---

app/controllers/exchanges/hbx_profiles_controller.rb
app/helpers/exchanges/hbx_profiles_helper.rb
app/models/effective/datatables/employer_datatable.rb
app/models/effective/datatables/family_data_table.rb
app/views/exchanges/hbx_profiles/_get_employer_info.html.erb
app/views/exchanges/hbx_profiles/_get_user_info.html.erb
app/views/exchanges/hbx_profiles/get_user_info.js.erb
config/routes.rb
spec/controllers/exchanges/hbx_profiles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16110](https://devops.dchbx.org/redmine/issues/16110) |

16110: Ability for hbx Admin to view username and email associated to an Account on EA's Employers data table

---

app/data_migrations/correct_plan_in_enrollment.rb
lib/tasks/migrations/correct_plan_in_enrollments.rake
spec/data_migrations/correct_plan_in_enrollments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [4922](https://devops.dchbx.org/redmine/issues/4922) |
| Start Date | 01/21/2016 |
| Ticket Author | Alix Pereira |

4922: wrong premium; plan tiles not displayed

---

app/data_migrations/remove_termination_date_from_enrollment.rb
lib/tasks/migrations/remove_termination_date_from_enrollment.rake
spec/data_migrations/remove_termination_date_from_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15806](https://devops.dchbx.org/redmine/issues/15806) |
| Ticket Author | Azizza Brown |

15806: Removing Term date from Enroll App 

---

app/models/factories/family_enrollment_renewal_factory.rb
app/views/insured/families/_enrollment.html.erb
spec/views/employers/census_employees/show.html.erb_spec.rb
spec/views/insured/families/_enrollment.html.erb_spec.rb
spec/views/insured/families/_waived_coverage_widget.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16161](https://devops.dchbx.org/redmine/issues/16161) |

16161: New Hire Renewal Issue - Unable to Shop for Renewal Coverage unless you Enroll in New Hire Coverage

---

app/data_migrations/create_renewal_plan_year_and_enrollment.rb
lib/tasks/migrations/create_renewal_plan_year_and_enrollment.rake
spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16223](https://devops.dchbx.org/redmine/issues/16223) |

16223: Please set group to active state and generate renewal plan year - Beulah Baptist Church

---

spec/data_migrations/general_agency_assignment_spec.rb

* (Required!)
* ()
* ()
```
```
*
---
---

fix failing spec

---

app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16507](https://devops.dchbx.org/redmine/issues/16507) |
| Ticket Author | Cherie Smith |

16507: End Date Corrections 

---

app/controllers/financial_assistance/applications_controller.rb
app/helpers/insured/family_members_helper.rb
app/models/family_member.rb
app/models/financial_assistance/applicant.rb
app/models/financial_assistance/application.rb
app/views/financial_assistance/applications/eligibility_results.html.erb
app/views/financial_assistance/applications/review_and_submit.html.erb
app/views/financial_assistance/applications/steps.yml
app/views/financial_assistance/shared/_right_nav.html.erb
app/views/insured/family_members/_dependent.html.erb
app/views/insured/family_members/_financial_assistance_row.html.erb
app/views/insured/family_members/index.html.erb
app/views/shared/_individual_progress.html.haml
components/ui_helpers/app/views/workflow/_section.html.erb
components/ui_helpers/app/views/workflow/step.html.erb
components/ui_helpers/lib/ui_helpers/workflow_helper.rb
config/routes.rb

* (Required!)
* ()
* ()
```
```
*
---
---

refs #13067 Remove STEP: Eligibility Determination

---

lib/tasks/migrations/create_published_plan_years_for_certain_employers.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16506](https://devops.dchbx.org/redmine/issues/16506) |

16506: Add 2016 and 2017 Plan Years - National Association Of Women Judges

---

app/assets/javascripts/consumer_verification.js
app/assets/javascripts/insured.js.erb
app/assets/stylesheets/_variables.scss.erb
app/assets/stylesheets/insured.scss.erb
app/assets/stylesheets/modules.scss.erb
app/controllers/documents_controller.rb
app/helpers/verification_helper.rb
app/models/consumer_role.rb
app/models/person.rb
app/models/vlp_document.rb
app/views/insured/families/verification/_verification.html.erb
spec/controllers/documents_controller_spec.rb
spec/helpers/verification_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15590](https://devops.dchbx.org/redmine/issues/15590) |

15590: Enable AN/AI IVL applicant to upload documents for tribe status

---

app/assets/javascripts/qle.js.erb
app/controllers/insured/families_controller.rb
app/views/exchanges/residents/find_sep.html.erb
app/views/insured/families/_insurance_fields.html.erb
app/views/insured/families/_marriage_fields.html.erb
app/views/insured/families/check_marriage_reason.js.erb
config/routes.rb
spec/controllers/insured/families_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15496](https://devops.dchbx.org/redmine/issues/15496) |

15496: Add question to IVL marriage SEP

---

app/views/user_mailer/invite_future_employee_for_open_enrollment.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16137](https://devops.dchbx.org/redmine/issues/16137) |

16137: Update Notice - New hire notice, date of hire in the future (14743)

---

app/views/user_mailer/invite_initial_employee_for_open_enrollment.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16138](https://devops.dchbx.org/redmine/issues/16138) |

16138: SHOP Notice Update - Shop 24-OE Begins for new hires (14745)

---

app/assets/javascripts/group_selection.js
app/helpers/insured/group_selection_helper.rb
app/views/insured/group_selection/_select_employer.html.erb
app/views/insured/group_selection/new.html.erb
spec/helpers/insured/group_selection_helper_spec.rb
spec/views/insured/group_selection/new.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16625](https://devops.dchbx.org/redmine/issues/16625) |

16625: Employees of Renewing Employer unable to shop Dental

---

app/data_migrations/change_person_name_suffix.rb
lib/tasks/migrations/change_person_name_suffix.rake
script/bad_suffix_data.rb
spec/data_migrations/change_person_name_suffix_spec.rb
spec/factories/people.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16313](https://devops.dchbx.org/redmine/issues/16313) |

16313: Prefix in the suffix field on 834 files

---

app/views/insured/families/verification/_documents_verification_list.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16805](https://devops.dchbx.org/redmine/issues/16805) |

16805: Update the Documents FAQ to include the AN/AI status and an update to the Immigrations status

---

app/controllers/concerns/data_tables_search.rb
app/controllers/exchanges/hbx_profiles_controller.rb
app/helpers/verification_helper.rb
app/models/family.rb
app/views/exchanges/hbx_profiles/_index_verification.html.erb
app/views/exchanges/hbx_profiles/_outstanding_verification_family.json.erb
app/views/insured/families/verification/_verification.html.erb
spec/controllers/concerns/data_tables_search_spec.rb
spec/helpers/verification_helper_spec.rb
spec/models/family_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [5498](https://devops.dchbx.org/redmine/issues/5498) |
| App-Dev Road Map # | 1.1.4.2 |
| Ticket Author | Holly Coffey |

5498: HBX-Admin Outstanding Verifications Reports

---

app/models/effective/datatables/employer_datatable.rb
app/models/employer_profile.rb
app/models/hbx_enrollment.rb
spec/factories/organizations.rb
spec/models/employer_profile_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15341](https://devops.dchbx.org/redmine/issues/15341) |
| Ticket Author | @nisanthyaganti9 |

15341: Employer plan year state displaying Issue under "Employers" tab for admins.

---

lib/tasks/import_2018_ivl_benefit_package.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16548](https://devops.dchbx.org/redmine/issues/16548) |

16548: Create 2018 IVL benefit packages (IVL)

---

app/data_migrations/build_ivl_enrollment.rb
app/data_migrations/change_enrollment_details.rb
lib/tasks/migrations/build_ivl_enrollment.rake
lib/tasks/migrations/change_enrollment_details.rake
spec/data_migrations/change_enrollment_details_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16592](https://devops.dchbx.org/redmine/issues/16592) |
| Ticket Author | Camille Gray |

16592: Update CSR to 73% in EA 

---

app/controllers/financial_assistance/applicants_controller.rb
app/controllers/financial_assistance/applications_controller.rb
app/helpers/navigation_helper.rb
app/views/financial_assistance/applicants/edit.html.erb
app/views/financial_assistance/applications/edit.html.erb
app/views/financial_assistance/shared/_left_nav.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15888](https://devops.dchbx.org/redmine/issues/15888) |

15888: Household Member UI: Application Navigation

---

app/models/census_employee_import.rb
spec/models/census_employee_import_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14414](https://devops.dchbx.org/redmine/issues/14414) |

14414: Roster Upload Owner Issue - 

---

app/models/plan_cost_decorator.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16879](https://devops.dchbx.org/redmine/issues/16879) |

16879: Domestic Partner Relationship results in incorrect premium calculation for SHOP market  

---

app/models/effective/datatables/quote_datatable.rb
app/views/broker_agencies/quotes/quotes.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16230](https://devops.dchbx.org/redmine/issues/16230) |

16230: BQT(2) fast follow-Timeout issue when using pagnation/Action button.

---

app/models/financial_assistance/applicant.rb
app/models/financial_assistance/application.rb
app/models/tax_household.rb
app/views/financial_assistance/applicants/edit.html.erb
app/views/financial_assistance/applicants/steps.yml
components/ui_helpers/app/views/workflow/_claimed_as_dependent_by_dropdown.html.erb
components/ui_helpers/app/views/workflow/_dropdown.html.erb
components/ui_helpers/app/views/workflow/_section.html.erb
spec/models/financial_assistance/application_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14249](https://devops.dchbx.org/redmine/issues/14249) |

14249: Tax Household Creation

---

app/assets/stylesheets/financial_assistance.scss.erb
app/views/financial_assistance/applications/review_and_submit.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16926](https://devops.dchbx.org/redmine/issues/16926) |
| Ticket Author | @shaibazalisyed |

16926: Styling and adding new questions on Review and Submit Page

---

app/data_migrations/update_broker_agency_profile_legal_name.rb
lib/tasks/migrations/update_broker_agency_profile_legal_name.rake
spec/data_migrations/update_broker_agency_profile_legal_name_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16666](https://devops.dchbx.org/redmine/issues/16666) |

16666: Please update Barbara Russell's legal name in her Broker Agency account to Barbara Russell

---

app/views/insured/families/_apply_for_medicaid_widget.html.erb
features/step_definitions/employee_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16804](https://devops.dchbx.org/redmine/issues/16804) |

16804: Text change to individual market option for EEs

---

app/assets/javascripts/employer_profile.js
features/employers/census_details_page.feature
features/step_definitions/employers_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12215](https://devops.dchbx.org/redmine/issues/12215) |

12215: EE termination error

---

app/views/shared/plan_shoppings/_more_plan_details.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16700](https://devops.dchbx.org/redmine/issues/16700) |

16700: Plan Shopping- when filters are used, effective date changes to number of plans showing

---

app/data_migrations/change_enrollment_details.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16680](https://devops.dchbx.org/redmine/issues/16680) |

16680: EA end date correction 

---

app/views/insured/families/_enrollment.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16862](https://devops.dchbx.org/redmine/issues/16862) |

16862: We're Sorry Error Rec'd when admin clicks on Census EE record 

---

app/data_migrations/correct_employees_with_incorrect_waivers.rb
lib/tasks/migrations/correct_employees_with_incorrect_waivers.rake
spec/data_migrations/correct_employees_with_incorrect_waivers_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16248](https://devops.dchbx.org/redmine/issues/16248) |

16248: Incorrect Automatic Waiving of Coverage

---

app/controllers/insured/family_members_controller.rb
app/controllers/people_controller.rb
app/models/consumer_role.rb
app/models/workflow_state_transition.rb
spec/controllers/people_controller_spec.rb
spec/models/consumer_role_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [7405](https://devops.dchbx.org/redmine/issues/7405) |
| Start Date | 05/12/2016 |
| Ticket Author | Holly Coffey |

7405: Member's outstanding verification is verified - but citizenship and lawful presence answers can be changed

---

app/views/financial_assistance/benefits/index.html.erb
app/views/financial_assistance/deductions/index.html.erb
app/views/financial_assistance/incomes/index.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17142](https://devops.dchbx.org/redmine/issues/17142) |

17142: New Income, Deduction & Benefit pages

---

app/reports/hbx_reports/generate_2017_ehb_report.rb
lib/tasks/hbx_reports/generate_2017_ehb_report.rake
spec/reports/hbx_reports/generate_2017_ehb_report_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12876](https://devops.dchbx.org/redmine/issues/12876) |

12876: Applied APTC Greater than Premium

---

lib/tasks/enrollment_data_clean_up.rake

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14691](https://devops.dchbx.org/redmine/issues/14691) |

14691: Enrollment Data Clean Up

---

app/views/broker_agencies/profiles/_menu.html.erb
spec/views/broker_agencies/profiles/_menu.html.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14903](https://devops.dchbx.org/redmine/issues/14903) |

14903: "Brokers" button should not appear when broker is logged-in

---

app/controllers/insured/employee_roles_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/employee_ineligibility_notice.html.erb
spec/controllers/insured/employee_roles_controller_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15200](https://devops.dchbx.org/redmine/issues/15200) |

15200: Employee ineligibility Notice (NOTICE ID 10003)

---

spec/views/insured/families/_waived_coverage_widget.erb_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17053](https://devops.dchbx.org/redmine/issues/17053) |

17053: Add a spec for census employee show page with waiver scenario

---

app/views/insured/families/verification/_verification.html.erb
spec/data_migrations/update_broker_agency_profile_legal_name_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15160](https://devops.dchbx.org/redmine/issues/15160) |

15160: User ability to upload Documentation

---

app/models/plan_year.rb
spec/models/plan_year_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15789](https://devops.dchbx.org/redmine/issues/15789) |

15789: Update Renewal Employer Transition Validations

---

app/controllers/financial_assistance/applicants_controller.rb
app/controllers/financial_assistance/applications_controller.rb
app/helpers/financial_assistance_helper.rb
app/models/financial_assistance/applicant.rb
app/models/financial_assistance/benefit.rb
app/models/financial_assistance/deduction.rb
app/models/financial_assistance/income.rb
app/views/financial_assistance/applicants/edit.html.erb
app/views/financial_assistance/applications/index.html.erb
app/views/financial_assistance/benefits/_health_coverage_questions.html.erb
app/views/financial_assistance/benefits/index.html.erb
app/views/financial_assistance/deductions/_income_adjustments_question.html.erb
app/views/financial_assistance/deductions/index.html.erb
app/views/financial_assistance/incomes/_income_questions.html.erb
app/views/financial_assistance/incomes/index.html.erb
app/views/financial_assistance/shared/_left_nav.html.erb
app/views/insured/family_members/_dependent.html.erb
app/views/insured/family_members/_financial_assistance_row.html.erb
app/views/insured/family_members/index.html.erb
app/views/shared/_individual_progress.html.haml

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17136](https://devops.dchbx.org/redmine/issues/17136) |

17136: Functionality Driver Questions

---

app/data_migrations/update_dental_relationship_benefits.rb
lib/tasks/migrations/update_dental_relationship_benefits.rake
spec/data_migrations/update_dental_relationship_benefits_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16156](https://devops.dchbx.org/redmine/issues/16156) |

16156: EE Was Able to Enroll Spouse in Dental Coverage Even Though It's Not Offered By ESC

---

app/data_migrations/delink_user_and_person.rb
lib/tasks/delink_user_and_person.rake
spec/data_migrations/delink_user_and_person_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16917](https://devops.dchbx.org/redmine/issues/16917) |

16917: Username and Email Updates 

---

app/data_migrations/populate_employee_role_on_enrollments.rb
lib/tasks/migrations/populate_employee_role_on_enrollments.rake
spec/data_migrations/populate_employee_role_on_enrollments_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17201](https://devops.dchbx.org/redmine/issues/17201) |

17201: Data migration: populate employee role id on renewal waiver enrollments

---

app/models/factories/temp_plan_year_renewal_factory.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16457](https://devops.dchbx.org/redmine/issues/16457) |
| Ticket Author | Alex Romero |

16457: Conversion Data - New 6.1 Add 

---

app/models/consumer_role.rb
app/models/insured_eligible_for_benefit_rule.rb
spec/models/insured_eligible_for_benefit_rule_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15019](https://devops.dchbx.org/redmine/issues/15019) |

15019: Rules Engine should treat a wider range of states as ineligible

---

app/data_migrations/create_broker_agency_account_for_employer.rb
lib/tasks/migrations/create_broker_agency_account_for_employer.rake
spec/data_migrations/create_broker_agency_account_for_employer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17168](https://devops.dchbx.org/redmine/issues/17168) |

17168: Please reinstate broker Brandon Downs with assignment date 4/1/2016 for group 521265163 Gap, Inc. Community Child Development Center.  

---

app/models/benefit_group_assignment.rb
app/models/broker_agency_staff_role.rb
app/models/broker_role.rb
app/models/census_employee.rb
app/models/consumer_role.rb
app/models/coverage_household.rb
app/models/employer_profile.rb
app/models/employer_profile_account.rb
app/models/general_agency_staff_role.rb
app/models/hbx_enrollment.rb
app/models/lawful_presence_determination.rb
app/models/plan_year.rb
app/models/workflow_state_transition.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16029](https://devops.dchbx.org/redmine/issues/16029) |
| Ticket Author | @lisyk |

16029: record current event for all state transitions

---

app/models/hbx_enrollment.rb
features/employee/employee_hired_during_renewal_period.feature
features/step_definitions/new_hire_steps.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17094](https://devops.dchbx.org/redmine/issues/17094) |

17094: Investigate Why EEs are not Allowed to Plan Shop during Renewal OE 
